### PR TITLE
Clang fix all code

### PR DESCRIPTION
**Pull request by garimellagowtham**
Fix all the c++ code to follow clang format manually. Since the git clang format script checks only the commited changes, the old code in the files is causing problems when commiting. This commit ensures all the code is clang formatted so that from now on we do not have issues with clang formatting difference between commited and uncommited code

Note: Before merging this branch, merge doxygen_documentation PR.

This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/19)

### CODE REVIEW

**Comment by msheckells** [comment]
This includes all of the changes in the documentation coverage branch.  Are you going to rebase this on top of master after merging so those won't be in this PR?

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/19#-:-KeVHV4af7S5tO636ufq:b-dhe3o1)*

**Comment by msheckells** [comment]
After merging the documentation coverage branch that is...

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/19#-:-KeVHlU6MBRJNErEm7SQ:b-c9xps6)*

**Comment by garimellagowtham** [comment]
After merging documentation coverage branch, the PR should adjust automatically to remove old commits. Its already rebased on documentation coverage branch.

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/19#-:-KeW_nKYJw7GBMUHfwrE:bfrozix)*

**Comment by msheckells** [comment]
Doesn't look like it adjusted.  May have to merge again?

---

Review status: 0 of 40 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/19#-:-KeWxFscVxSTlVEyEMwn:b-q1f1vf)*

**Comment by garimellagowtham** [comment]
Fixed

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/19#-:-KeXAIzzXH9yWn3Vc8_r:b-886gsx)*

**Comment by msheckells** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/19)*

**Pull request merged**
