### PR TITLE
Change tracking strategy

### PR DESCRIPTION
**Pull request by msheckells**
Adds the ability to change the TrackingStrategy of a Tracker

This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/130)

### CODE REVIEW

**Comment by msheckells** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/actions_guards/uav_basic_functor_tests.cpp, line 85 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2-BxuqU6FqBlb_rQq:-Ky2-BxuqU6FqBlb_rQr:bgw0xb4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/tests/actions_guards/uav_basic_functor_tests.cpp#L85)):*
> ```cpp
>   UAVLogicStateMachine sample_logic_state_machine(uav_system);
>   int dummy_event, dummy_start_state, dummy_target_state;
>   drone_hardware->flowControl(false);
> ```

I'm not sure why this is included here.... These changes are already in repeat-pick-place.  I might have messed something up

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130)*

**Comment by garimellagowtham** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 64 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky28bfC8ykV70e_jbUz:-Ky28bfC8ykV70e_jbV-:bpilshw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L64)):*
> ```objc
>         std::unique_ptr<TrackingStrategy>(new IdTrackingStrategy(MarkerId)));
>     Position tracking_vector;
>     if (!robot_system.getTrackingVector(tracking_vector)) {
> ```

Can use initialize here (Look at the comment in IdTrackingStrategy.h

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 225 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2-J7uKPpHAup4gPxS:-Ky2-J7uKPpHAup4gPxT:btzidpl) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L225)):*
> ```objc
> */
> template <class LogicStateMachineT>
> struct RelativePoseVisualServoing_
> ```

Can use `using` similar to other states i.e we don't need to subclass.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 50 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky29XFBvBczg95BmBfM:-Ky29XFBvBczg95BmBfN:b-28zd6s) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L50)):*
> ```objc
>   * @brief Check whether visual servoing is feasible currently
>   */
>   using VisualServoingTransitionGuard =
> ```

can reorder `RelativePoseVisualServoingTransitionGuard`

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 58 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A0zbjbgnfUCr0cx6:-Ky2A0zbjbgnfUCr0cx7:bw2fe9w) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L58)):*
> ```objc
>   * @brief Check whether relative pose visual servoing is feasible currently
>   */
>   // \todo Matt check goal index exists
> ```

Is this TODO still valid?

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 59 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A5S1in6GsP2wYIBO:-Ky2A5S1in6GsP2wYIBP:bdoqb1b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L59)):*
> ```objc
>   */
>   // \todo Matt check goal index exists
>   using RelativePoseVisualServoingTransitionGuard =
> ```

Why do we need a separate VisualServoingTransitionGuard, RelativePoseVisualServoingTransitionGuard, and ExplicitIdVisualServoingGuardFunctor?

---

*[include/aerial_autonomy/robot_systems/uav_vision_system.h, line 92 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2-lFs4i8ycS4Ka-fW:-Ky2-lFs4i8ycS4Ka-fX:bz6m3f) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/robot_systems/uav_vision_system.h#L92)):*
> ```objc
>   */
>   void
>   setTrackingStrategy(std::unique_ptr<TrackingStrategy> &&tracking_strategy) {
> ```

What does double ref do? This is for my knowledge than a comment :)

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky284Gc60c143As3rNo:-Ky284Gc60c143As3rNp:bqwnko4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/trackers/alvar_tracker.h#L16)):*
> ```objc
> public:
>   /**
>   * @brief Constructor
> ```

Add doc stating the default tracking strategy is closest tracking strategy. I don't know what the number 25 means.

---

*[include/aerial_autonomy/trackers/id_tracking_strategy.h, line 20 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky28JZFL3RaLokef42L:-Ky28JZFL3RaLokef42M:bbkhz7j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/trackers/id_tracking_strategy.h#L20)):*
> ```objc
>   * @return True if successful, false otherwise
>   */
>   virtual bool initialize(
> ```

Initialize can verify if tracking id exists. If the tracking id does not initialize can return false. This can be used in guards.

---

*[tests/trackers/simple_multi_tracker_tests.cpp, line 152 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky25iVhS8PMPW-SBBJ6:-Ky25iVhS8PMPW-SBBJ7:bxv1evc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/tests/trackers/simple_multi_tracker_tests.cpp#L152)):*
> ```cpp
> 
>   std::unordered_map<uint32_t, tf::Transform> tracking_vectors;
>   tracking_vectors[0] =
> ```

Where are these tracking vectors set for the simple multitracker?

---

*[tests/trackers/simple_multi_tracker_tests.cpp, line 180 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky27vNzNL5o3ZGsxQfo:-Ky27vNzNL5o3ZGsxQfp:bvxqdwp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/tests/trackers/simple_multi_tracker_tests.cpp#L180)):*
> ```cpp
>   std::unordered_map<uint32_t, tf::Transform> tracking_vectors;
>   tracking_vectors[0] =
>       tf::Transform(tf::Quaternion(0, 0, 0, 1), tf::Vector3(1, 1, 1));
> ```

Where are these vectors set for simple tracker?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 64 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky28bfC8ykV70e_jbUz:-Ky2MmpTNOjTXcKVHVXN:bvlkqx4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L64)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can use initialize here (Look at the comment in IdTrackingStrategy.h
</blockquote></details>

Initialize isn't really for checking if the tracking is valid, though usually it ends up checking the tracking validity in order to initialize.  I don't think initialize should be required to check if tracking is valid, so I'd rather just check the tracking validity directly here.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 225 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2-J7uKPpHAup4gPxS:-Ky2Lc37QumJbET2-_IT:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L225)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can use `using` similar to other states i.e we don't need to subclass.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 50 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky29XFBvBczg95BmBfM:-Ky2NOyXdjTmejmZJp5k:b-lbut5x) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L50)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

can reorder `RelativePoseVisualServoingTransitionGuard`
</blockquote></details>

What do you mean?

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 58 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A0zbjbgnfUCr0cx6:-Ky2ND8BJevFCj3dolyN:bpbbdha) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L58)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Is this TODO still valid?
</blockquote></details>

Yes.  I don't think we have a guard to check if the given goal index exists

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 59 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A5S1in6GsP2wYIBO:-Ky2Ne-AvF51p43-7Vwe:b99lilx) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L59)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why do we need a separate VisualServoingTransitionGuard, RelativePoseVisualServoingTransitionGuard, and ExplicitIdVisualServoingGuardFunctor?
</blockquote></details>

ExplicitIdVisualServoingGuardFunctor is templated on a particular marker id which gets passed to the IdTrackingStrategy constructor.  We could probably combine ExplicitIdVisualServoingGuardFunctor and RelativePoseVisualServoingTransitionGuard into one guard if there is a way to use variadic templates to pass in arguments to the constructor of the given TrackingStrategy.  Might be a pain though.

VisualServoingTransitionGuard is different because it sets the goal for the VisualServoingDroneConnector and also checks that the tracking vector norm is large enough for normalization.  We could move the goal setting part to a transition action functor and move the norm check to another separate guard.  However, the transition action functor would have to make the exact same calls as the current guard.  So, in the end we just end up changing VisualServoingTransitionGuard to a transition action, which really makes no difference in my opinion

---

*[include/aerial_autonomy/robot_systems/uav_vision_system.h, line 92 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2-lFs4i8ycS4Ka-fW:-Ky2KGVULd5v-Ww7ZQEs:bc1r0wg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/robot_systems/uav_vision_system.h#L92)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

What does double ref do? This is for my knowledge than a comment :)
</blockquote></details>

&& means that the function can only take an rvalue.  This https://stackoverflow.com/questions/3106110/what-are-move-semantics does a better job explaining it than I can.

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky284Gc60c143As3rNo:-Ky2QCmIe6e0lyKPyjMm:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/trackers/alvar_tracker.h#L16)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add doc stating the default tracking strategy is closest tracking strategy. I don't know what the number 25 means.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/trackers/id_tracking_strategy.h, line 20 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky28JZFL3RaLokef42L:-Ky2QEKBDSjU0CtEd1q5:bu6xv6u) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/trackers/id_tracking_strategy.h#L20)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Initialize can verify if tracking id exists. If the tracking id does not initialize can return false. This can be used in guards.
</blockquote></details>

See previous comment.

---

*[tests/trackers/simple_multi_tracker_tests.cpp, line 152 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky25iVhS8PMPW-SBBJ6:-Ky2LFLNVpr34owhgrbP:b-f7f991) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/tests/trackers/simple_multi_tracker_tests.cpp#L152)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Where are these tracking vectors set for the simple multitracker?
</blockquote></details>

line 156

---

*[tests/trackers/simple_multi_tracker_tests.cpp, line 180 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky27vNzNL5o3ZGsxQfo:-Ky2LCWXRHO_QQKzK33O:bt2vr1b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/tests/trackers/simple_multi_tracker_tests.cpp#L180)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Where are these vectors set for simple tracker?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 50 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky29XFBvBczg95BmBfM:-Ky2_1q3u51BQWmkQdC-:b-4mhnrw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L50)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

The RelativePoseVisualServoingTransitionGuard can be defined before this typdef. Then the InitializeTrackerGuardFunctor can be replaced by RelativePoseVisualServoingTransitionGuard typedef

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 59 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A5S1in6GsP2wYIBO:-Ky2XlYFuhGhq0v3HWkX:bfo8zdu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L59)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

ExplicitIdVisualServoingGuardFunctor is templated on a particular marker id which gets passed to the IdTrackingStrategy constructor.  We could probably combine ExplicitIdVisualServoingGuardFunctor and RelativePoseVisualServoingTransitionGuard into one guard if there is a way to use variadic templates to pass in arguments to the constructor of the given TrackingStrategy.  Might be a pain though.

VisualServoingTransitionGuard is different because it sets the goal for the VisualServoingDroneConnector and also checks that the tracking vector norm is large enough for normalization.  We could move the goal setting part to a transition action functor and move the norm check to another separate guard.  However, the transition action functor would have to make the exact same calls as the current guard.  So, in the end we just end up changing VisualServoingTransitionGuard to a transition action, which really makes no difference in my opinion
</blockquote></details>

Ok. We don't need variadic template stuff for now. We can use a default template argument for id to differentiate between explicitId and RelativePoseVisualServoing guards. Like we can set the default value of id in the template to -1 so that anything positive, implies user wants explicit id tracking maybe.

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 76 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2Zverm-rb2a6D7PO8:-Ky2Zverm-rb2a6D7PO9:b-nkl30r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/280bb5b7ce2ff5151280845e2b379cd12f7ba6e3/include/aerial_autonomy/trackers/alvar_tracker.h#L76)):*
> ```objc
>   * @brief Default number of retries for tracking a locked target
>   */
>   const int default_num_retries_ = 25;
> ```

Do we want a parameter for the number of retries?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 50 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky29XFBvBczg95BmBfM:-Ky2d32m9iln3s7iXeGj:b-j0xmlm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L50)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

The RelativePoseVisualServoingTransitionGuard can be defined before this typdef. Then the InitializeTrackerGuardFunctor can be replaced by RelativePoseVisualServoingTransitionGuard typedef
</blockquote></details>

In general, I wouldn't expect VisualServoingTransitionGuard (which is for the original 2D visual servoing controller) to always use the RelativePoseVisualServoingTransition Guard.  So, I wouldn't want to replace the Initialize guard with RelativePoseVisual guard just because they happen to be the same.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 59 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A5S1in6GsP2wYIBO:-Ky2dfETZp3xGhaM3v0q:b-b2vvde) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L59)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Ok. We don't need variadic template stuff for now. We can use a default template argument for id to differentiate between explicitId and RelativePoseVisualServoing guards. Like we can set the default value of id in the template to -1 so that anything positive, implies user wants explicit id tracking maybe.
</blockquote></details>

That doesn't really scale though.  What happens when we have more strategies with different constructor parameters?  We would just add more template params, some of which would get ignored depending on their value?  Seems too hacky.  

For now, I'm fine with just having a generic initializer guard for strategies with no arguments and specialized initializer guards for strategies with arguments.

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 76 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2Zverm-rb2a6D7PO8:-Ky2cuRgcU-6hQDHOI5u:b-91geyv) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/280bb5b7ce2ff5151280845e2b379cd12f7ba6e3/include/aerial_autonomy/trackers/alvar_tracker.h#L76)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Do we want a parameter for the number of retries?
</blockquote></details>

We might as well just give it a constructor that takes a tracking strategy in that case

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 50 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky29XFBvBczg95BmBfM:-Ky2eUS67m5-WoEUCHBT:bl9u0v8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L50)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

In general, I wouldn't expect VisualServoingTransitionGuard (which is for the original 2D visual servoing controller) to always use the RelativePoseVisualServoingTransition Guard.  So, I wouldn't want to replace the Initialize guard with RelativePoseVisual guard just because they happen to be the same.
</blockquote></details>

Ok, sure.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h, line 59 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2A5S1in6GsP2wYIBO:-Ky2eZxFg_x_lXQKGnng:bq8zslz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fc144a828cd4bc28e7da70fd2d822d543dfe001b/include/aerial_autonomy/actions_guards/visual_servoing_states_actions.h#L59)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

That doesn't really scale though.  What happens when we have more strategies with different constructor parameters?  We would just add more template params, some of which would get ignored depending on their value?  Seems too hacky.  

For now, I'm fine with just having a generic initializer guard for strategies with no arguments and specialized initializer guards for strategies with arguments.
</blockquote></details>

Ok. we can add a todo about finding a good solution for passing arguments to individual tracking strategies. One solution would be to pass in a config that is loaded from a file or something.

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 76 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-Ky2Zverm-rb2a6D7PO8:-Ky2fNdA5eArZCEIJ2HY:b2nhll9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/280bb5b7ce2ff5151280845e2b379cd12f7ba6e3/include/aerial_autonomy/trackers/alvar_tracker.h#L76)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We might as well just give it a constructor that takes a tracking strategy in that case
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130)*

**Comment by garimellagowtham** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/130#-:-Ky2fTaCfe9xDrRi8H6X:bnfp4nl)*

**Pull request merged**
