### PR TITLE
Integrate rpyt position controller

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/151)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[proto/uav_system_config.proto, line 45 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-F1UPhkbFH4lh1PLh3:-L-F1UPhkbFH4lh1PLh4:b-t1tdrl) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f7cc1fde10f85e1de4b8505b0d6fcd4f548b17f1/proto/uav_system_config.proto#L45)):*
> ```protobuf
>   optional VelocityControllerConfig velocity_controller_config = 6;
> 
>   optional RPYTBasedPositionControllerConfig
> ```

change param files to reflect this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151)*

**Comment by garimellagowtham** [comment]
Review status: 13 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[param/matrice_config.pbtxt, line 46 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HX5SzxW06HaerWiPo:-L-HX5T-BTXGNpzhrF3b:b-kjrh5a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_config.pbtxt#L46)):*
> ```
>       }
>     }
>     
> ```

spaces

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 34 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXUGiQliOA2rrzpmH:-L-HXUGiQliOA2rrzpmI:b-hkkkkr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L34)):*
> ```
>   rpyt_based_position_controller_config {
>     velocity_based_position_controller_config {
>       position_gain: 1.0
> ```

reduce 

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 44 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXctn4H9J_Zm1tZAm:-L-HXctn4H9J_Zm1tZAn:b-ew66jq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L44)):*
> ```
>       position_controller_config {
>         goal_position_tolerance {
>           x: 0.05
> ```

keep them same.

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 50 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXhpqyqI9UXhOkI1h:-L-HXhpqyqI9UXhOkI1i:b-kjrh5a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L50)):*
> ```
>       }
>     }
>     
> ```

spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151)*

**Comment by garimellagowtham** [comment]
Reviewed 2 of 4 files at r2.
Review status: 15 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[param/matrice_visual_servoing_config_pointgrey.pbtxt, line 32 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXpNxjcDmD-0SQYgM:-L-HXpNxjcDmD-0SQYgN:b-t43j67) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_visual_servoing_config_pointgrey.pbtxt#L32)):*
> ```
>   rpyt_based_position_controller_config {
>     velocity_based_position_controller_config {
>       position_gain: 1.0
> ```

set gains

---

*[param/matrice_visual_servoing_config_pointgrey.pbtxt, line 48 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXqUfgC_jmYn_MoI_:-L-HXqUfgC_jmYn_MoIa:b-kjrh5a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_visual_servoing_config_pointgrey.pbtxt#L48)):*
> ```
>       }
>     }
>     
> ```

spaces

---

*[param/simulator_config.pbtxt, line 27 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXuTRdsMaCSgHDmcP:-L-HXuTRdsMaCSgHDmcQ:b-7q6o0h) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/simulator_config.pbtxt#L27)):*
> ```
>   rpyt_based_position_controller_config {
>     velocity_based_position_controller_config {
>       position_gain: 1.0
> ```

gains

---

*[param/simulator_config.pbtxt, line 43 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXw2DCgP6NrvUIYrG:-L-HXw2DCgP6NrvUIYrH:b-kjrh5a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/simulator_config.pbtxt#L43)):*
> ```
>       }
>     }
>     
> ```

spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151)*

**Comment by msheckells** [comment]
Review status: 13 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[param/matrice_config.pbtxt, line 46 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HX5SzxW06HaerWiPo:-L-HZaNw8Zn09fmdS489:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_config.pbtxt#L46)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

spaces
</blockquote></details>

Done.

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 34 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXUGiQliOA2rrzpmH:-L-HZb0RO2MtmVggj46W:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L34)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

reduce 
</blockquote></details>

Done.

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 44 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXctn4H9J_Zm1tZAm:-L-HZbtv0h_bBbNyJjGa:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L44)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

keep them same.
</blockquote></details>

Done.

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 50 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXhpqyqI9UXhOkI1h:-L-HZDAM79RZ5k4SMK4D:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L50)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

spaces
</blockquote></details>

Done.

---

*[param/matrice_visual_servoing_config_pointgrey.pbtxt, line 32 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXpNxjcDmD-0SQYgM:-L-HZDgo8gPcyq-kytqS:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_visual_servoing_config_pointgrey.pbtxt#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

set gains
</blockquote></details>

Done.

---

*[param/matrice_visual_servoing_config_pointgrey.pbtxt, line 48 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXqUfgC_jmYn_MoI_:-L-HZO3hjZzO2cgxGykS:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/matrice_visual_servoing_config_pointgrey.pbtxt#L48)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

spaces
</blockquote></details>

Done.

---

*[param/simulator_config.pbtxt, line 27 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXuTRdsMaCSgHDmcP:-L-HZOhp8Ns0ohTB6qTG:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/simulator_config.pbtxt#L27)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

gains
</blockquote></details>

Done.

---

*[param/simulator_config.pbtxt, line 43 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-HXw2DCgP6NrvUIYrG:-L-HZPGJTFGdkfjx0SrE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/de58b1e7fad17f26c3581433aeee5545414d2ac9/param/simulator_config.pbtxt#L43)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

spaces
</blockquote></details>

Done.

---

*[proto/uav_system_config.proto, line 45 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151#-L-F1UPhkbFH4lh1PLh3:-L-HZQPVrHz23N-0b3LE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f7cc1fde10f85e1de4b8505b0d6fcd4f548b17f1/proto/uav_system_config.proto#L45)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

change param files to reflect this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151)*

**Comment by garimellagowtham** [comment]
Reviewed 2 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/151)*

**Pull request merged**
