### PR TITLE
Create onboard system handler

### PR DESCRIPTION
**Pull request by msheckells**
Create OnboardSystemHandler class and tests.  As part of that, I've created an AsyncTimer class which calls a function on a timer in its own thread.   This PR also adds proto configuration for UAVSystem and OnboardSystemHandler.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/21)

### CODE REVIEW

**Comment by msheckells** [comment]
Review status: 0 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 170 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-Kee2fRG6dctTzwOEJ59:-Kee2fRG6dctTzwOEJ5A:b-avakjt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/8c02ead08efd0589e7ed44539c18b6a874fd2868/CMakeLists.txt#L170)):*
> ```CMake
> )
> 
> target_link_libraries(aerial_autonomy ${Boost_LIBRARIES})
> ```

I was having an issue where if I linked Boost_LIBRARIES to async-timer-test below, I would get linker errors in regard to boost::system. From the output of catkin I could clearly see the -lboost_system flag, so I'm not sure what was happening.  Linking boost to aerial_autonomy fixed the issue.  Maybe you have some insight on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21)*

**Comment by garimellagowtham** [comment]
Reviewed 15 of 18 files at r1, 1 of 1 files at r2.
Review status: 16 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/common/async_timer.h, line 39 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-KehVzDE4stb1MdSgPYa:-KehVzDE4stb1MdSgPYb:b-2g8kd1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/include/aerial_autonomy/common/async_timer.h#L39)):*
> ```objc
>   std::chrono::duration<double>
>       timer_duration_; ///< The amount of time in between each function call
>   bool running_;       ///< True when the timer is running
> ```

You should use std::atomic<bool> here to ensure thread safety while accessing and writing the variable: 
http://www.cplusplus.com/reference/atomic/atomic/atomic/
http://stackoverflow.com/questions/15103053/is-this-function-with-atomic-thread-safe

---

*[proto/onboard_system_handler_config.proto, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-KehT7SGIRR3o5Mzuq92:-KehT7SGIRR3o5Mzuq93:b-s5htl6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/proto/onboard_system_handler_config.proto#L6)):*
> ```protobuf
>   required UAVSystemConfig uav_system_config = 1;
>   required string uav_parser_type = 2;
>   optional int32 uav_parser_load_timeout = 3 [ default = 5 ];
> ```

We will be moving this to parser.

---

*[tests/onboard_system_handler_tests.cpp, line 89 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-Kehs5VG0jbshDkYGiLw:-Kehs5VG0jbshDkYGiLx:b-jaq5kq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/tests/onboard_system_handler_tests.cpp#L89)):*
> ```cpp
>   ASSERT_EQ(onboard_system_handler_->getUAVData().localpos.z, 0.0);
>   // Check pose command works
>   publishEvent("Takeoff");
> ```

Separate pose command with takeoff into a separate test may be.

---

*[tests/common/async_timer_tests.cpp, line 23 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-KehpjEPtJ7tUXOlPCut:-KehpjEPtJ7tUXOlPCuu:bmtkif9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/tests/common/async_timer_tests.cpp#L23)):*
> ```cpp
>   timer.start();
>   std::this_thread::sleep_for(std::chrono::milliseconds(50));
>   ASSERT_EQ(1, this->x);
> ```

These may not be deterministic.  The timer may sleep for slightly more than 50 milli seconds etc. I saw that the asynctimertest failed multiple times on my computer when I ran it continously.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21)*

**Comment by msheckells** [comment]
Review status: 16 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/common/async_timer.h, line 39 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-KehVzDE4stb1MdSgPYa:-KeidKZsHW1vgF-aTYpw:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/include/aerial_autonomy/common/async_timer.h#L39)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

You should use std::atomic<bool> here to ensure thread safety while accessing and writing the variable: 
http://www.cplusplus.com/reference/atomic/atomic/atomic/
http://stackoverflow.com/questions/15103053/is-this-function-with-atomic-thread-safe



</blockquote></details>

Done.

---

*[tests/common/async_timer_tests.cpp, line 23 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-KehpjEPtJ7tUXOlPCut:-Keicatr8uNMAt6IS9Zi:b-et9t0x) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/tests/common/async_timer_tests.cpp#L23)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

These may not be deterministic.  The timer may sleep for slightly more than 50 milli seconds etc. I saw that the asynctimertest failed multiple times on my computer when I ran it continously.
</blockquote></details>

I had the timing wrong in the test.  Should be fixed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21)*

**Comment by msheckells** [comment]
Review status: 13 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/onboard_system_handler_tests.cpp, line 89 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-Kehs5VG0jbshDkYGiLw:-Keielkb2ERoML3PDxaF:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/tests/onboard_system_handler_tests.cpp#L89)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Separate pose command with takeoff into a separate test may be.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21)*

**Comment by msheckells** [comment]
Review status: 12 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[proto/onboard_system_handler_config.proto, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21#-KehT7SGIRR3o5Mzuq92:-Keij7gANjZt5h6FiN1a:bss4a2b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ba66526b3776cf53bd548d6c8646d909d2fc98f/proto/onboard_system_handler_config.proto#L6)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We will be moving this to parser.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 2 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/21)*

**Pull request merged**
