### PR TITLE
Create BuiltInVelocityController and connector.

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/5)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/controllers/builtin_velocity_controller.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5#-KcfJ_a340cwTYUNGsQc:-KcfJ_a4xeGSpX_xZTba:b-vnm45p) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1468d551899aad0a0eb56f9559fb065e835805a7/include/aerial_autonomy/controllers/builtin_velocity_controller.h#L1)):*
> ```objc
> #pragma once
> ```

We do not need a separate builtin_velocity_controller. The builtin_position_controller is the same. If we write common class like default_action_controller that passes the goal without doing anything, Then the controller templated on VelocityYaw becomes builtin velocity controller. For rpy controller, we have to implement a separate one though.

---

*[include/aerial_autonomy/types/velocity_yaw.h, line 7 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5#-KcfMKHhbQUptXLcWmBJ:-KcfMKHiGuWX4IijNM7D:bo4mzok) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1468d551899aad0a0eb56f9559fb065e835805a7/include/aerial_autonomy/types/velocity_yaw.h#L7)):*
> ```objc
>   VelocityYaw() : Velocity(), yaw(0) {}
>   VelocityYaw(double x, double y, double z, double yaw)
>       : Velocity(x, y, z), yaw(yaw) {}
> ```

add another constructor that takes in a velocity, yaw.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5)*

**Comment by msheckells** [comment]
*[include/aerial_autonomy/controllers/builtin_velocity_controller.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5#-KcfJ_a340cwTYUNGsQc:-KcfXkIxWh1_Qs_XSTpO:b-nzeshh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1468d551899aad0a0eb56f9559fb065e835805a7/include/aerial_autonomy/controllers/builtin_velocity_controller.h#L1)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We do not need a separate builtin_velocity_controller. The builtin_position_controller is the same. If we write common class like default_action_controller that passes the goal without doing anything, Then the controller templated on VelocityYaw becomes builtin velocity controller. For rpy controller, we have to implement a separate one though.
</blockquote></details>

I thought about that. We can do it for the controllers, but the same idea won't work for the connectors. The connectors require the sendHardwareCommands functions to be implemented differently depending on the control type. I'll go ahead and change it for the controllers though. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/controllers/builtin_velocity_controller.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5#-KcfJ_a340cwTYUNGsQc:-KcfYbluNspdwaFGodUP:b-w31odj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1468d551899aad0a0eb56f9559fb065e835805a7/include/aerial_autonomy/controllers/builtin_velocity_controller.h#L1)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I thought about that. We can do it for the controllers, but the same idea won't work for the connectors. The connectors require the sendHardwareCommands functions to be implemented differently depending on the control type. I'll go ahead and change it for the controllers though. 
</blockquote></details>

Yes thats true do this only for controllers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5)*

**Comment by msheckells** [comment]
Review status: 10 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/controllers/builtin_velocity_controller.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5#-KcfJ_a340cwTYUNGsQc:-KcoDCo73ZHq3z_60oQL:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1468d551899aad0a0eb56f9559fb065e835805a7/include/aerial_autonomy/controllers/builtin_velocity_controller.h#L1)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Yes thats true do this only for controllers
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5)*

**Comment by msheckells** [comment]
Review status: 9 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/types/velocity_yaw.h, line 7 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5#-KcfMKHhbQUptXLcWmBJ:-KcoDqcl3Q9-O7fMzAGj:beagoqt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1468d551899aad0a0eb56f9559fb065e835805a7/include/aerial_autonomy/types/velocity_yaw.h#L7)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

add another constructor that takes in a velocity, yaw.
</blockquote></details>

Done. Also did the same for PositionYaw

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5)*

**Comment by garimellagowtham** [comment]
Reviewed 9 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/5)*

**Pull request merged**
