### PR TITLE
Create state configs

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/125)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 6 of 57 files at r1.
Review status: 6 of 57 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAqGxrBIzaemBI9Xf5:-KxAqGxrBIzaemBI9Xf6:bw51fwq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L40)):*
> ```objc
>             << " for relative pose visual servoing drone connector!";
>     auto goal =
>         this->state_machine_config_.visual_servoing_state_machine_config()
> ```

Will the relative pose goals change in future to have more specific names instead of a goal-index?

---

*[include/aerial_autonomy/common/conversions.h, line 63 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAqtCVFXNFpiEBpSq9:-KxAqtCVFXNFpiEBpSqA:bfuqou2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/common/conversions.h#L63)):*
> ```objc
> 
> template <class T>
> std::vector<tf::Transform> protoTransformsToTfs(const T &proto_tfs) {
> ```

Add doc.

---

*[include/aerial_autonomy/common/system_handler_node_utils.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAs9O0AE8kWArrpelw:-KxAs9O0AE8kWArrpelx:b-blw7td) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/common/system_handler_node_utils.h#L1)):*
> ```objc
> #pragma once
> ```

This is not from your PR.

---

*[include/aerial_autonomy/common/thread_safe_state_machine.h, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAsG0Ece2KfXr6I9e1:-KxAsG0F29suGRN6AeRU:b-wfqp2i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/common/thread_safe_state_machine.h#L47)):*
> ```objc
>   thread_safe_state_machine<A0, A1, A2, A3, A4>(
>       Expr const &expr,
>       typename ::boost::enable_if<
> ```

Not from your PR!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125)*

**Comment by msheckells** [comment]
Sorry, I fixed it then forgot to push.... Should be good now

---

Review status: 6 of 24 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-:-KxDlqohz5QgqH8aBuOU:bel4kkk)*

**Comment by garimellagowtham** [comment]
Reviewed 20 of 57 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 155 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE6vEAbbIHKwMWO9Ib:-KxE6vEAbbIHKwMWO9Ic:b-t9lyc5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/include/aerial_autonomy/actions_guards/base_functors.h#L155)):*
> ```objc
>   * @brief Copy of state machine configuration which can be used in run function
>   */
>   BaseStateMachineConfig state_machine_config_;
> ```

I am fine with this hack of copying into a member variable. I think it will be nice to send it to run function although will be annoying to change the form for every single action functor.

 Maybe we can have two types of action functors. one that need the config. And ones we do not need the config. Most of the action functors do not need state config I assume.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 135 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE7rfAM6w8M2ndFlCu:-KxE7rfBP1Ihp7noXpmj:b9kj14m) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/include/aerial_autonomy/actions_guards/pick_place_functors.h#L135)):*
> ```objc
>             .pick_place_state_machine_config()
>             .arm_goal_transform()
>             .Get(TransformIndex);
> ```

The arm goals should ideally be associated with some state and not be common for all the states in a state machine.

---

*[proto/transform.proto, line 14 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE21kx-z-DxipknPs3:-KxE21kx-z-DxipknPs4:b-ny656r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/proto/transform.proto#L14)):*
> ```protobuf
>   * @brief Roll
>   */
>   optional double roll = 2 [ default = 0.0 ];
> ```

It might be better to have rotation field maybe. And in rotation message, we can have `oneof` to handle RPY, quaternion, matrix formats. But might be unnecessary...

---

*[proto/visual_servoing_state_machine_config.proto, line 10 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE1Ir6ywP3ep3VDM_E:-KxE1Ir7HKplHi8r4-mo:b-uv5rb4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/proto/visual_servoing_state_machine_config.proto#L10)):*
> ```protobuf
>   * @brief Relative pose goals for relative pose visual servoing
>   */
>   repeated config.PositionYaw relative_pose_goals = 1;
> ```

Instead of repeated goals, we can give specific names to each goal and associate them with the state somehow. For example, we can have `go_back_after_gripping` field.

---

*[proto/visual_servoing_state_machine_config.proto, line 13 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE1hxlzFsGG-v9YXdx:-KxE1hxmsWmdNQu5PPjH:bxft6cn) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/proto/visual_servoing_state_machine_config.proto#L13)):*
> ```protobuf
> 
>   oneof subclass {
>     PickPlaceStateMachineConfig pick_place_state_machine_config = 2;
> ```

I think making pickplace a subclass of visualservoing config is fine for now. But how will we deal with the case where pick place needs some fields from uavstate but are not in visualconfig?

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 52 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE3LOWHiVm7N6T-KAp:-KxE3LOWHiVm7N6T-KAq:b-pxxum4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/tests/actions_guards/pick_place_functor_tests.cpp#L52)):*
> ```cpp
>     // Arm transform
>     auto arm_tf = uav_arm_system_config->mutable_arm_transform();
>     arm_tf->mutable_position()->set_x(0.2);
> ```

Code duplication. Can create a function to write arm_tf using x,y,z, r,p,y

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 76 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE3csDBq60EzNOfhz2:-KxE3csE5wbOVSZgMFr3:b-2gvjhu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/tests/actions_guards/pick_place_functor_tests.cpp#L76)):*
> ```cpp
>         state_machine_config.mutable_visual_servoing_state_machine_config();
>     auto pose_goal = vision_state_machine_config->add_relative_pose_goals();
>     pose_goal->mutable_position()->set_x(pose_goal_.x);
> ```

Code duplication.

---

*[tests/common/math_tests.cpp, line 65 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE3v7-__Oa2poYCFMX:-KxE3v70uXftTn1ZugrP:b-rijfxw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/33fc793930fd48c11c35fe85949b3f333aaf11c4/tests/common/math_tests.cpp#L65)):*
> ```cpp
> }
> 
> TEST(TransformTests, StdVector) {
> ```

We do not have any tests for conversions. Maybe move these into a different file called conversion_tests and test the specific functions

---

*[tests/robot_systems/uav_vision_system_tests.cpp, line 17 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE4AqsQYKTdhZ0mh3e:-KxE4AqtL54Pip_XVpaX:b-4fxpd7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/tests/robot_systems/uav_vision_system_tests.cpp#L17)):*
> ```cpp
>   RoiToPositionConverter roi_to_position_converter(nh);
>   UAVSystemConfig config;
>   config.mutable_uav_vision_system_config();
> ```

Why are you accessing mutable_uav_vision_system_config? Will this create a default vision system config variable in the `oneof` field?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125)*

**Comment by msheckells** [comment]
Review status: 18 of 25 files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 155 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE6vEAbbIHKwMWO9Ib:-KxEzHHjRz8suwUEEwT4:b51ncv3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/include/aerial_autonomy/actions_guards/base_functors.h#L155)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I am fine with this hack of copying into a member variable. I think it will be nice to send it to run function although will be annoying to change the form for every single action functor.

 Maybe we can have two types of action functors. one that need the config. And ones we do not need the config. Most of the action functors do not need state config I assume.
</blockquote></details>

Ok. I added a TODO.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 135 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE7rfAM6w8M2ndFlCu:-KxEkBQUq6a477FMkCHV:bi4u41e) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/include/aerial_autonomy/actions_guards/pick_place_functors.h#L135)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

The arm goals should ideally be associated with some state and not be common for all the states in a state machine.
</blockquote></details>

But this is a transition action functor.  Thus, it has no associated state

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAqGxrBIzaemBI9Xf5:-KxEkKgfJOt2Dbi6jclq:b-jd9qj3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L40)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Will the relative pose goals change in future to have more specific names instead of a goal-index?
</blockquote></details>

I suppose in the future we could make a PoseGoal proto object that also has a name and then we could search for a specific goal by name

---

*[include/aerial_autonomy/common/conversions.h, line 63 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAqtCVFXNFpiEBpSq9:-KxEx8tNGbc_vACwlNgP:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/common/conversions.h#L63)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add doc.
</blockquote></details>

Done.

---

*[proto/transform.proto, line 14 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE21kx-z-DxipknPs3:-KxEys5IChqjfO7ONGnn:b19ftzh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/proto/transform.proto#L14)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

It might be better to have rotation field maybe. And in rotation message, we can have `oneof` to handle RPY, quaternion, matrix formats. But might be unnecessary...
</blockquote></details>

Done.  Just added rpy for now

---

*[proto/visual_servoing_state_machine_config.proto, line 10 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE1Ir6ywP3ep3VDM_E:-KxEkyEr7vYIJ1C_mzMJ:bhynenq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/proto/visual_servoing_state_machine_config.proto#L10)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Instead of repeated goals, we can give specific names to each goal and associate them with the state somehow. For example, we can have `go_back_after_gripping` field.
</blockquote></details>

See previous comment about named goals.  The transition action would then have to be templated on the state type to get the config associated with that particular state, which would be strange I think.

---

*[proto/visual_servoing_state_machine_config.proto, line 13 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE1hxlzFsGG-v9YXdx:-KxEkrXOifM7-inV71Wa:bgy00n0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/proto/visual_servoing_state_machine_config.proto#L13)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I think making pickplace a subclass of visualservoing config is fine for now. But how will we deal with the case where pick place needs some fields from uavstate but are not in visualconfig?
</blockquote></details>

We would just add the necessary fields to pick place config I think

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 52 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE3LOWHiVm7N6T-KAp:-KxEzEtYCFJJjre-jvJC:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/tests/actions_guards/pick_place_functor_tests.cpp#L52)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Code duplication. Can create a function to write arm_tf using x,y,z, r,p,y
</blockquote></details>

Done.

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 76 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE3csDBq60EzNOfhz2:-KxEzFO16WIgqfEhh_55:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/tests/actions_guards/pick_place_functor_tests.cpp#L76)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Code duplication.
</blockquote></details>

Done.

---

*[tests/common/math_tests.cpp, line 65 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE3v7-__Oa2poYCFMX:-KxElV5Wc7u5iwl8JMao:bdgbru3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/33fc793930fd48c11c35fe85949b3f333aaf11c4/tests/common/math_tests.cpp#L65)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We do not have any tests for conversions. Maybe move these into a different file called conversion_tests and test the specific functions
</blockquote></details>

These functions no longer exist since we read transforms from a Transform proto now.  I will create tests for the new functions.

---

*[tests/robot_systems/uav_vision_system_tests.cpp, line 17 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxE4AqsQYKTdhZ0mh3e:-KxElcgaFpXGLM_8Rjjr:bxe1ob) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/091df3455fe03fd53763c840f4a67cda184e9a0e/tests/robot_systems/uav_vision_system_tests.cpp#L17)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why are you accessing mutable_uav_vision_system_config? Will this create a default vision system config variable in the `oneof` field?
</blockquote></details>

Yes, exactly.  Otherwise the constructor will fail.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125)*

**Comment by garimellagowtham** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAqGxrBIzaemBI9Xf5:-KxFAfoclX3rA1PONTU9:b-ftn21e) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L40)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I suppose in the future we could make a PoseGoal proto object that also has a name and then we could search for a specific goal by name
</blockquote></details>

Add a todo maybe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125#-KxAqGxrBIzaemBI9Xf5:-KxFH25FEBILMP3i6mh3:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/372ac50984895d4a8963fa42ea8cb18ee00e9925/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L40)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add a todo maybe?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/125)*

**Pull request merged**
