### PR TITLE
Thread safe state machine

### PR DESCRIPTION
**Pull request by garimellagowtham**
Add a thread safe version of boost state machine

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/24)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/common/thread_safe_state_machine.h, line 43 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24#-Ket1Iw0GjE_Ii8I2BoR:-Ket1Iw1F-wjwOol8to_:b-xx3un1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7e2fe1dc590d738fe7fe4f98ecb7e34fa57e944c/include/aerial_autonomy/common/thread_safe_state_machine.h#L43)):*
> ```objc
> 
>   template <class, class, class, class, class>
>   friend class boost::msm::back::thread_safe_state_machine;
> ```

It has to be a friend with itself?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24)*

**Comment by msheckells** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24#-KetHLwOHhjTN-6aP4TI:-KetHLwOHhjTN-6aP4TJ:bbvo0jc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7e2fe1dc590d738fe7fe4f98ecb7e34fa57e944c/include/aerial_autonomy/actions_guards/base_functors.h#L49)):*
> ```objc
>         "Template Logic state machine arg is not subclass of provided FSM");
>     LogicStateMachineT *logic_state_machine_cast =
>         static_cast<LogicStateMachineT *>(&logic_state_machine);
> ```

I guess this is what you had to do to get the template stuff to work correctly?  Is there no way around the static_casting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24)*

**Comment by garimellagowtham** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24#-KetHLwOHhjTN-6aP4TI:-KetHajZlj7MrdJFW3r-:bu61use) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7e2fe1dc590d738fe7fe4f98ecb7e34fa57e944c/include/aerial_autonomy/actions_guards/base_functors.h#L49)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I guess this is what you had to do to get the template stuff to work correctly?  Is there no way around the static_casting?
</blockquote></details>

For future reference: Rewrite how state machine is forwarded to action functors. Which may require rewriting the functor row class in boost. 

The current method is compile-time safe since it has a static assert inside.

---

*[include/aerial_autonomy/common/thread_safe_state_machine.h, line 43 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24#-Ket1Iw0GjE_Ii8I2BoR:-KetHU4NHB-8jfgapJNv:b-up00q9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7e2fe1dc590d738fe7fe4f98ecb7e34fa57e944c/include/aerial_autonomy/common/thread_safe_state_machine.h#L43)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

It has to be a friend with itself?
</blockquote></details>

Check line 203 in /usr/include/boost/msm/back/state_machine.hpp

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24)*

**Comment by msheckells** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/24)*

**Pull request merged**
