### PR TITLE
Add joystick control state machine

### PR DESCRIPTION
**Pull request by sohampatkar10**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/107)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, 9 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/joystick_control_functors.h, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ6XcXjpce0sVQMBZr:-KtJ6XcXjpce0sVQMBZs:b1qfvn6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/actions_guards/joystick_control_functors.h#L18)):*
> ```objc
> template <class LogicStateMachineT, class AbortEventT = ManualControlEvent>
> struct JoystickControlInternalActionFunctor_
>     : HoveringInternalActionFunctor_<LogicStateMachineT, AbortEventT> {};
> ```

Internal action functor should check controller status for critical and check uav status (see other controller internal action functors for examples)

---

*[include/aerial_autonomy/actions_guards/joystick_control_functors.h, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ2KNiLyzxqN0hF9OQ:-KtJ2KNjdQjKMsI7iHHe:b-h18715) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/actions_guards/joystick_control_functors.h#L47)):*
> ```objc
>       LOG(WARNING) << "Sensor Status INVALID";
>     }
>     return sensor_status_to_bool(robot_system.getSensorStatus());
> ```

Can we just make the sensor status a class that has a boolean conversion function and the == operator overloaded for the enum type we would compare it to?  This would work nicer than having to use `sensor_status_to_bool`

---

*[include/aerial_autonomy/robot_systems/uav_sensor_system.h, line 10 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ2wb_ozMqbr0rd9FG:-KtJ2wb_ozMqbr0rd9FH:b-ar4e7n) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/robot_systems/uav_sensor_system.h#L10)):*
> ```objc
> #include "rpyt_based_velocity_controller_config.pb.h"
> /**
> * @ brief UAV system with external sensor
> ```

external velocity sensor

---

*[include/aerial_autonomy/robot_systems/uav_sensor_system.h, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ38MgEqxkjz39F29w:-KtJ38MgEqxkjz39F29x:bd8asn9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/robot_systems/uav_sensor_system.h#L31)):*
> ```objc
>       Atomic<RPYTBasedVelocityControllerConfig>
>           &rpyt_velocity_controller_config,
>       JoystickVelocityControllerConfig joystick_velocity_controller_config,
> ```

Why does it get this separately? Can't it be obtained from uav_system_config?

---

*[include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h, line 43 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ4THwUooQfVdPLYAU:-KtJ4THwUooQfVdPLYAV:bb9xzuo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h#L43)):*
> ```objc
>             config.uav_system_handler_config().uav_system_config(),
>             rpyt_velocity_controller_config_,
>             config.joystick_velocity_controller_config(),
> ```

should be in the uav_system_config, not system handler config

---

*[include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h, line 91 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ4bTI_og-oS7DHLpl:-KtJ4bTI_og-oS7DHLpm:bz9l9yr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h#L91)):*
> ```objc
>                                     ///< and associated connections.
>   AsyncTimer uav_controller_timer_; ///< Timer for running uav controller
>   bool use_dynamic_reconfigure;     ///< flag to use dynamic reconfigure
> ```

member variables end in _

---

*[proto/uav_sensor_system_handler_config.proto, line 12 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ5Mww-x4u22KI9JkC:-KtJ5Mww-x4u22KI9JkD:bwtrrz1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/proto/uav_sensor_system_handler_config.proto#L12)):*
> ```protobuf
>   * @brief rpyt based velocity controller config 
>   */
>   required RPYTBasedVelocityControllerConfig rpyt_velocity_controller_config = 1;
> ```

Should be part of the UAVSensorSystemConfig, not the handler config

---

*[src/system_handler_nodes/uav_joystick_control_node.cpp, line 36 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ5U03kRsxosKlYfEK:-KtJ5U03kRsxosKlYfEL:b-22jhu3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/src/system_handler_nodes/uav_joystick_control_node.cpp#L36)):*
> ```cpp
>   }
> 
>   UAVSensorSystemHandlerConfig uav_system_config;
> ```

use the config loader in proto_utils.h

---

*[tests/actions_guards/joystick_control_functor_tests.cpp, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ6FH1ev5fYjoDA0f8:-KtJ6FH1ev5fYjoDA0f9:b-x9vpuz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/tests/actions_guards/joystick_control_functor_tests.cpp#L88)):*
> ```cpp
> 
>   ASSERT_EQ(uav_system.getStatus<JoystickVelocityControllerDroneConnector>(),
>             ControllerStatus::Active);
> ```

Check uav velocity matches expected

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107)*

**Comment by sohampatkar10** [comment]
I stiil have to convert SensorStatus to a class. Please check the rest.

---

Review status: 7 of 17 files reviewed at latest revision, 9 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/joystick_control_functors.h, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ6XcXjpce0sVQMBZr:-KtK3D-Ez2nd8Rm-4wh9:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/actions_guards/joystick_control_functors.h#L18)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Internal action functor should check controller status for critical and check uav status (see other controller internal action functors for examples)
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/uav_sensor_system.h, line 10 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ2wb_ozMqbr0rd9FG:-KtK3Fd2Omp29pEl0g1m:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/robot_systems/uav_sensor_system.h#L10)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

external velocity sensor
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/uav_sensor_system.h, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ38MgEqxkjz39F29w:-KtK3Hig3cEvRoZQwdmD:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/robot_systems/uav_sensor_system.h#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why does it get this separately? Can't it be obtained from uav_system_config?
</blockquote></details>

Done.

---

*[include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h, line 43 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ4THwUooQfVdPLYAU:-KtK3LiJAJ93lkGEDDpX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h#L43)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

should be in the uav_system_config, not system handler config
</blockquote></details>

Done.

---

*[include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h, line 91 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ4bTI_og-oS7DHLpl:-KtK3QUnuhFf80SnmeRb:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/system_handlers/uav_sensor_system_handler.h#L91)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

member variables end in _
</blockquote></details>

Done.

---

*[proto/uav_sensor_system_handler_config.proto, line 12 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ5Mww-x4u22KI9JkC:-KtK3THqhUhlzVQGl7ar:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/proto/uav_sensor_system_handler_config.proto#L12)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be part of the UAVSensorSystemConfig, not the handler config
</blockquote></details>

Done.

---

*[src/system_handler_nodes/uav_joystick_control_node.cpp, line 36 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ5U03kRsxosKlYfEK:-KtK3WFnEkPwK0MXKLI8:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/src/system_handler_nodes/uav_joystick_control_node.cpp#L36)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

use the config loader in proto_utils.h
</blockquote></details>

Done.

---

*[tests/actions_guards/joystick_control_functor_tests.cpp, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ6FH1ev5fYjoDA0f8:-KtK3YdMOA9ce7-WbKNi:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/tests/actions_guards/joystick_control_functor_tests.cpp#L88)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Check uav velocity matches expected
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-:-KtK3gJf-UI7ZajurnJi:b-7ioc50)*

**Comment by sohampatkar10** [comment]
Review status: 7 of 20 files reviewed at latest revision, 9 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/joystick_control_functors.h, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ2KNiLyzxqN0hF9OQ:-KtKMLPmcuPKRho9GVO5:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/actions_guards/joystick_control_functors.h#L47)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Can we just make the sensor status a class that has a boolean conversion function and the == operator overloaded for the enum type we would compare it to?  This would work nicer than having to use `sensor_status_to_bool`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107)*

**Comment by msheckells** [comment]
Reviewed 7 of 13 files at r2.
Review status: 14 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/joystick_control_functors.h, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ2KNiLyzxqN0hF9OQ:-KtMYrrJ7ngFasdqayOA:buw8y6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/actions_guards/joystick_control_functors.h#L47)):*
<details><summary><i>Previously, sohampatkar10 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice.  Do you need to explicitly cast it to bool?  I think it might do so implicitly without the explicit cast.

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 18 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtMZFo01QCfdQU8i7-N:-KtMZFo1QZ0dcwlOUmiV:b-mxrj6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ba45b11fbac52b23a0541f1b39b4af335d3a8e90/include/aerial_autonomy/sensors/base_sensor.h#L18)):*
> ```objc
>   * @brief Types of Statuses
>   */
>   enum Status { INVALID, VALID };
> ```

enum class

---

*[proto/uav_sensor_system_config.proto, line 19 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtMZtWIHqSb19MGAznG:-KtMZtWIHqSb19MGAznH:bisz414) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ba45b11fbac52b23a0541f1b39b4af335d3a8e90/proto/uav_sensor_system_config.proto#L19)):*
> ```protobuf
>   * @brief uav system config
>   */
>   required UAVSystemConfig uav_system_config = 3;
> ```

This should not contain a UAVSystemConfig.  UAVSystem config should have UAVSensorSystemConfig as a possible subclass.  See UAVSystemConfig and UAVVisionSystemConfig for an example

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107)*

**Comment by sohampatkar10** [comment]
Review status: 11 of 22 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/joystick_control_functors.h, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtJ2KNiLyzxqN0hF9OQ:-KtN9MleEeagtPXCU23L:b-mausng) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/939a394768c3156aa8e2ac9dac169a949e4d4889/include/aerial_autonomy/actions_guards/joystick_control_functors.h#L47)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Nice.  Do you need to explicitly cast it to bool?  I think it might do so implicitly without the explicit cast.
</blockquote></details>

It doesnt. We have to use bool(). 

---

*[proto/uav_sensor_system_config.proto, line 19 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtMZtWIHqSb19MGAznG:-KtN8ttXNv9vSrg4Y4Gd:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ba45b11fbac52b23a0541f1b39b4af335d3a8e90/proto/uav_sensor_system_config.proto#L19)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

This should not contain a UAVSystemConfig.  UAVSystem config should have UAVSensorSystemConfig as a possible subclass.  See UAVSystemConfig and UAVVisionSystemConfig for an example
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107)*

**Comment by sohampatkar10** [comment]
Review status: 10 of 24 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 18 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107#-KtMZFo01QCfdQU8i7-N:-KtNs-3XRNMeI2g-Lpha:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ba45b11fbac52b23a0541f1b39b4af335d3a8e90/include/aerial_autonomy/sensors/base_sensor.h#L18)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

enum class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/107)*

**Pull request closed without merging**
