### PR TITLE
Move grip timeout into state config

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/127)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 418 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiLrNCoRn53YqlAxzC:-KxiLrNCoRn53YqlAxzD:bgf7n7y) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/include/aerial_autonomy/actions_guards/pick_place_functors.h#L418)):*
> ```objc
>   void on_entry(Event const &, FSM &logic_state_machine) {
>     // log start time
>     this->entry_time_ = std::chrono::high_resolution_clock::now();
> ```

Call base class on_entry function instead of copy/pasting it from TimedSTate

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 434 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiLjTix7sb6oH8JnCD:-KxiLjTjVGiFK9iaOoU9:b-ts8f3p) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/include/aerial_autonomy/actions_guards/pick_place_functors.h#L434)):*
> ```objc
> private:
>   std::chrono::time_point<std::chrono::high_resolution_clock> grip_start_time_;
>   std::chrono::milliseconds required_grip_duration_ =
> ```

can also make required_grip_duration_ a state parameter

---

*[include/aerial_autonomy/logic_states/timed_state.h, line 42 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiM8uytNhpKu4c0eSS:-KxiM8uzUDCdVFPMUtJq:bs0989s) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/include/aerial_autonomy/logic_states/timed_state.h#L42)):*
> ```objc
>   virtual ~TimedState() {}
> 
> protected:
> ```

Can leave private if TimedState::on_entry is called in PickState::on_entry 

---

*[param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt, line 140 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiMdRZm-sq7oPrH6SJ:-KxiMdR_KqE5ypMtx7ER:b-3qmayt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt#L140)):*
> ```
>     }
>     uav_arm_system_config {
>       grip_timeout: 30000
> ```

No longer needed in proto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127)*

**Comment by garimellagowtham** [comment]
Review status: 20 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 418 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiLrNCoRn53YqlAxzC:-KxijWiTf8J0VgN2nHOb:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/include/aerial_autonomy/actions_guards/pick_place_functors.h#L418)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Call base class on_entry function instead of copy/pasting it from TimedSTate
</blockquote></details>

Done.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 434 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiLjTix7sb6oH8JnCD:-KxijYAmYddTHp-NphS7:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/include/aerial_autonomy/actions_guards/pick_place_functors.h#L434)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

can also make required_grip_duration_ a state parameter
</blockquote></details>

Done.

---

*[param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt, line 140 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiMdRZm-sq7oPrH6SJ:-KxijZIKDyUc5GmlzOpH:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt#L140)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

No longer needed in proto
</blockquote></details>

Done.

---

*[include/aerial_autonomy/logic_states/timed_state.h, line 42 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxiM8uytNhpKu4c0eSS:-KxijaXx9za8o7kyqLIO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/include/aerial_autonomy/logic_states/timed_state.h#L42)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Can leave private if TimedState::on_entry is called in PickState::on_entry 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127)*

**Comment by msheckells** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt, line 140 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxjHVAd-JGXnlrWBvIF:-KxjHVAedxEqX70IICJY:b4oj3af) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt#L140)):*
> ```
>     }
>     uav_arm_system_config {
>       grip_timeout: 30000
> ```

Also remove from corresponding .proto file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127)*

**Comment by garimellagowtham** [comment]
Review status: 27 of 28 files reviewed at latest revision, 1 unresolved discussion.

---

*[param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt, line 140 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127#-KxjHVAd-JGXnlrWBvIF:-KxoQFJUjL_bR0vUQcZ0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/83923e72a83f838c81efac3746fdc1180e7555a2/param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt#L140)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Also remove from corresponding .proto file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/127)*

**Pull request merged**
