### PR TITLE
Chaining action sequences

### PR DESCRIPTION
**Pull request by garimellagowtham**
Create a class for short circuiting action sequences. This class evaluates actions until one of them returns false. The actions should return bool based on whether they processed events or not! Created InternalActionFunctor for this purpose. Remove state machine from another action functor implementations

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/71)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 139 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOpif7VT_PmML2NtV:-KqYOpigyUOXQvTtgnBg:bi73kxk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L139)):*
> ```objc
>       VLOG(1) << "Completed Folding arm!";
>       logic_state_machine.process_event(Completed());
>       return true;
> ```

return false

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 143 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOr_QAvHk1v99iYng:-KqYOr_RkEJ2lgl6mE5t:bi73kxk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L143)):*
> ```objc
>       LOG(WARNING) << "Arm not enabled!";
>       logic_state_machine.process_event(be::Abort());
>       return true;
> ```

return false

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 145 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOzXbDGNXtXT1FaqR:-KqYOzXbDGNXtXT1FaqS:bpsr3vd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L145)):*
> ```objc
>       return true;
>     }
>     return false;
> ```

return true

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 76 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYRKZDmuS_uDWSkica:-KqYRKZDmuS_uDWSkicb:bi73kxk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/land_functors.h#L76)):*
> ```objc
>       VLOG(1) << "Switching to Manual UAV state";
>       logic_state_machine.process_event(ManualControlEvent());
>       return true;
> ```

return false

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 78 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYRLiYJ3BkfpAtw4WM:-KqYRLiYJ3BkfpAtw4WN:bpsr3vd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/land_functors.h#L78)):*
> ```objc
>       return true;
>     }
>     return false;
> ```

return true

---

*[include/aerial_autonomy/actions_guards/shorting_action_sequence.h, line 133 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYTrEWf8o9_kbeUpBK:-KqYTrEWf8o9_kbeUpBL:b-y0kokv) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/shorting_action_sequence.h#L133)):*
> ```objc
>    */
>   template <class EVT, class FSM, class SourceState, class TargetState>
>   struct Call2 {
> ```

Maybe use a more descriptive name than Call2 to differentiate from Call

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 84 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYXdmdbjXNLD2aD1SX:-KqYXdmdbjXNLD2aD1SY:b-se3og2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L84)):*
> ```objc
>     VLOG(1) << "entering: PickPlace system";
>     int dummy_source_state = 0, dummy_target_state = 0;
>     psa::ArmPoweron()(evt, fsm, dummy_source_state, dummy_target_state);
> ```

This is only called when the state machine starts running right?

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 95 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYXgv-YalOFEg16d1h:-KqYXgv-YalOFEg16d1i:b-269pxg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L95)):*
> ```objc
>     VLOG(1) << "leaving: PickPlace system";
>     int dummy_source_state = 0, dummy_target_state = 0;
>     psa::ArmPoweroff()(evt, fsm, dummy_source_state, dummy_target_state);
> ```

and this is only called when the state machine is stopped?

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 11 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYa3eWiNNPW_DFhJYg:-KqYa3eXshFvIxJ__Y0k:b-9ud5zg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/tests/system_handlers/uav_arm_system_handler_tests.cpp#L11)):*
> ```cpp
> #include <std_msgs/String.h>
> 
> #define TIMEOUT_WAIT 20
> ```

just make this a variable in the UAVArmSystemHandlerTests class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 139 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOpif7VT_PmML2NtV:-KqZ7mMOID94uWjgv4nK:bh22v5e) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L139)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

return false
</blockquote></details>

Should also add tests that check the return value of these functors to make sure they are correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71)*

**Comment by msheckells** [comment]
All tests pass on my system

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-:-KqZ9M7EvGqyEW7DSIs-:b-ru4lki)*

**Comment by garimellagowtham** [comment]
Review status: 23 of 31 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 139 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOpif7VT_PmML2NtV:-KqZB_-33OIIKjpgzZj6:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L139)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should also add tests that check the return value of these functors to make sure they are correct.
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 143 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOr_QAvHk1v99iYng:-KqZBZIaZpQi5mL3KoGE:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L143)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

return false
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/arm_functors.h, line 145 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYOzXbDGNXtXT1FaqR:-KqZBa8Ozm5egWEm53Pu:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/arm_functors.h#L145)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

return true
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 76 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYRKZDmuS_uDWSkica:-KqZBbJxbkeUEjZfwWdx:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/land_functors.h#L76)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

return false
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 78 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYRLiYJ3BkfpAtw4WM:-KqZCaSs05ZTopnx-KZi:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/land_functors.h#L78)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

return true
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/shorting_action_sequence.h, line 133 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYTrEWf8o9_kbeUpBK:-KqZCxRet7QqweP0P8oZ:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/actions_guards/shorting_action_sequence.h#L133)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Maybe use a more descriptive name than Call2 to differentiate from Call
</blockquote></details>

Done

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 84 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYXdmdbjXNLD2aD1SX:-KqZ7WlA7csxMK-0z1Xj:b2nhswy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L84)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

This is only called when the state machine starts running right?
</blockquote></details>

Yes

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 95 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYXgv-YalOFEg16d1h:-KqZ7Y79vyoKxx0gcKd-:b2nhswy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L95)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

and this is only called when the state machine is stopped?
</blockquote></details>

Yes

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 11 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-KqYa3eWiNNPW_DFhJYg:-KqZFhHcHqZgNMQBM_El:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c97fe00e4a14cb21da6ff56848f156c29be6a3e4/tests/system_handlers/uav_arm_system_handler_tests.cpp#L11)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

just make this a variable in the UAVArmSystemHandlerTests class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71)*

**Comment by msheckells** [comment]
Reviewed 1 of 30 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71)*

**Comment by msheckells** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71#-:-KqZMtsOcfsoKx89ulyE:bnfp4nl)*

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/71)*

**Pull request merged**
