### PR TITLE
Added sensor implementation to joystick drone connector

### PR DESCRIPTION
**Pull request by sohampatkar10**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/159)

### CODE REVIEW

**Comment by msheckells** [comment]
Is this PR only tests?  Or did you add sensor to the joystick drone connector in a different PR?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-:-L-ZjSTwRR3MsrmCjUCt:bu61zro)*

**Comment by sohampatkar10** [comment]
I meant to. Not sure how that file got skipped. Added it now 

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-:-L-_S_m2bUGOoCvyOIoA:beshca8)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp, line 21 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-L-b7ZJdev8L-yQ3VoLh:-L-b7ZJeTx06oiVu2tlt:bg244yc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dbf4e5f7d9b0f08529fae78d5842a1bd19a22efe/src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp#L21)):*
> ```cpp
>                     quad_data.servo_in[2], quad_data.servo_in[3]);
> 
>   Velocity velocity_sensor_data = velocity_sensor_->getSensorData();
> ```

should check the sensor status is valid and return false if it is invalid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159)*

**Comment by sohampatkar10** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp, line 21 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-L-b7ZJdev8L-yQ3VoLh:-L-bVRJAZw2lNG5fZZQk:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dbf4e5f7d9b0f08529fae78d5842a1bd19a22efe/src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp#L21)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

should check the sensor status is valid and return false if it is invalid
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp, line 20 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-L-bWRmmpI333s2oxHhn:-L-bWRmn5Ahv8Y6Ek2KC:bb8e8bp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/90ffc5dce54ba532a65e46ca6411da8fa4d68640/src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp#L20)):*
> ```cpp
>   Joystick joy_data(quad_data.servo_in[0], quad_data.servo_in[1],
>                     quad_data.servo_in[2], quad_data.servo_in[3]);
> ```

you can just set a variable with the sensor status bool, which you can use in the if statement and in the return statement.  That way you don't have to call getSensorStatus twice

---

*[tests/controller_hardware_connectors/joystick_velocity_controller_drone_connector_tests.cpp, line 135 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-L-bWhJMq79SIuSMB4ix:-L-bWhJO8bT_YzTTtujM:bu8ezfo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/90ffc5dce54ba532a65e46ca6411da8fa4d68640/tests/controller_hardware_connectors/joystick_velocity_controller_drone_connector_tests.cpp#L135)):*
> ```cpp
>   ros::Duration(1.0).sleep();
>   connector.run();
>   ASSERT_FALSE(connector.getStatus() == ControllerStatus::Active);
> ```

assert that it is critical

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159)*

**Comment by sohampatkar10** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp, line 20 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-L-bWRmmpI333s2oxHhn:-L-bYv4pBl1iqJ8TYVk8:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/90ffc5dce54ba532a65e46ca6411da8fa4d68640/src/controller_hardware_connectors/joystick_velocity_controller_drone_connector.cpp#L20)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

you can just set a variable with the sensor status bool, which you can use in the if statement and in the return statement.  That way you don't have to call getSensorStatus twice
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/joystick_velocity_controller_drone_connector_tests.cpp, line 135 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159#-L-bWhJMq79SIuSMB4ix:-L-bYw79YU5REFVGYUsF:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/90ffc5dce54ba532a65e46ca6411da8fa4d68640/tests/controller_hardware_connectors/joystick_velocity_controller_drone_connector_tests.cpp#L135)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

assert that it is critical
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/159)*

**Pull request merged**
