### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by garimellagowtham**
1. Changes to README. 
2. Fix documentation for different files. 
3. Additional markdown scripts to explain background and how to add new state machine

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/33)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 12 of 17 files at r1, 1 of 3 files at r2.
Review status: 11 of 18 files reviewed at latest revision, 9 unresolved discussions.

---

*[README.md, line 15 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf81fZszT5J47Pur1Q_:-Kf81fZszT5J47Pur1Qa:b-yok6uc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L15)):*
> ```Markdown
> Additionally, run the following
> 
>     sudo apt-get install protobuf-compiler
> ```

Add this to install command above

---

*[README.md, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf81mn-CbmMYBiNWl6w:-Kf81mn-CbmMYBiNWl6x:b-usc7xu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L18)):*
> ```Markdown
> 
> ## Running executables
> The package provides a `aerial_autonomy_node` executable which loads a state machine and hardware and wait for event commands from rostopic. The `rqt_aerial_autonomy_gui` script
> ```

an `aerial_autonomy_node`
waits for event commands from a ROS topic
in the rqt_gui framework

---

*[README.md, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf82917CDir9eS1tpsi:-Kf82917CDir9eS1tpsj:b-63ybh3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L21)):*
> ```Markdown
> provides a GUI to generate events for the state machine. The rqt plugin can be loaded along with `rqt_rviz` in `rqt_gui` framework.
> 
> The `simulator.launch` file in the launch folder executes the state machine node using a simulated hardware. The GUI can be launched individually using rosrun. The steps to launch a simulated quadrotor with the state machine are
> ```

using simulated hardware

---

*[README.md, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf82LnXJJkrXJLJspeI:-Kf82LnXJJkrXJLJspeJ:b-ebr0im) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L31)):*
> ```Markdown
> 
> ## Logging
> GLOG is used to log messages from state machine. The messages are divided into different levels (INFO, WARNING, ERROR) etc. The information messages are divided into different verbosity levels 0,1,2 and so on. Th verbosity level can be adjusted using the environment variable `GLOG_v`. If the environment variable is set to 1 (`export GLOG_V=1`), then all the messages with verbosity 0 and 1 are streamed to stderr output.
> ```

from the state machine
(INFO, WARNING, ERROR, etc.)
(0, 1, 2, and so on)
GLOG_V or GLOG_v? just be consistent
the logs folder
using the GLOG_log_dir 
in the Google Log 

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf83EXjwj1maY5f9a8R:-Kf83EXk2kh9J4BtONZv:b8ghzct) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L44)):*
> ```Markdown
> 
> ## Documentation Coverage
> Using coverxygen to generate documentation coverage for the doc: https://github.com/psycofdj/coverxygen
> ```

We use coverxygen to

---

*[README.md, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf83_ZfIgWhtB5rNO2v:-Kf83_ZfIgWhtB5rNO2w:b8wt0ja) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L49)):*
> ```Markdown
> Check the html page in `documentation_coverage_info/index.html` to verify the documentation coverage of the code.
> 
> Documentation coverage is also added as a `pre-push` hook. This verifies that 99% of the code is covered with documentation before pushing to remote. It can be skipped for branches with their name starting with `develop*` and also by using `git push --no-verify` command.
> ```

is it still 99%?

---

*[README.md, line 52 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf83HjdlGKb7rxZSoBT:-Kf83HjdlGKb7rxZSoBU:b-b4hu4w) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L52)):*
> ```Markdown
> 
> ## Test Coverage
> Using `lcov` to generate test coverage report for the project. The script `scripts/generate_test_coverage.bash` is used to run tests in the project and generate test coverage report
> ```

We use lcov to 
generate the test coverage report into the test_coverage_info folder

---

*[README.md, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf846dwxFUZN97W-8SM:-Kf846dwxFUZN97W-8SN:bsv6dvs) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L56)):*
> ```Markdown
> by running CMake using `catkin build aerial_autonomy`.
> 
> The test generation is integrated into `pre-push` commit hook. This runs the above test coverage generation script and verifies that the coverage level is above 95% threshold. This can be skipped by either naming the branch as `develop[your_branch_name]` or using `git push --no-verify`.
> ```

the pre-push 

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 4 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf84Sayid_dO75S1wr6:-Kf84Sayid_dO75S1wr7:bmjwy4b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/src/aerial_autonomy/aerial_autonomy_gui.py#L4)):*
> ```Python
> """
> @package aerial_autonomy GUI source code
> to provide user, the ability to
> ```

no comma

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
I had issues with tests getting stuck, but deleting build seemed to fix it.

---

Review status: 11 of 18 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-:-Kf84vZM_mmSCaE4Mais:b-c0eeap)*

**Comment by msheckells** [comment]
Reviewed 2 of 17 files at r1.
Review status: 13 of 18 files reviewed at latest revision, 11 unresolved discussions.

---

*[markdown_scripts/class_groups.md, line 14 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85D9NKDtAx4dAErGx:-Kf85D9Obf1DPBE_XaNw:b-sa5bk1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/class_groups.md#L14)):*
> ```Markdown
> 
> ## States
> - BaseState
> ```

Did you make this manually or was it generated automatically by Doxygen?

---

*[markdown_scripts/class_groups.md, line 23 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85OwO_r2FxH-hsk8j:-Kf85OwO_r2FxH-hsk8k:b-2qgd71) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/class_groups.md#L23)):*
> ```Markdown
> ## Action Functors
> - ActionFunctor
>     - LandTransitionActionFunctor_
> ```

Shouldn't there be a PositionControlActionFunctor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
Reviewed 2 of 17 files at r1.
Review status: 15 of 18 files reviewed at latest revision, 17 unresolved discussions.

---

*[markdown_scripts/background.md, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85szbvo8GvL8ZpdiJ:-Kf85szcCAMnwM_qGP02:b-ynl4ne) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L1)):*
> ```Markdown
> ## Aerial autonomy Introduction 
> ```

Single #
Capitalize Autonomy

---

*[markdown_scripts/background.md, line 19 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf868lYXd8Hk8DQKYaK:-Kf868lYXd8Hk8DQKYaL:b-qr1v4o) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L19)):*
> ```Markdown
> 2. LogicStateMachineFrontEnd
> 3. StateMachineGUIConnector
> 4. GUIFrontEnd
> ```

Can add OnboardSystemHandler

---

*[markdown_scripts/background.md, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87gbhyQgz7Y0cNiyh:-Kf87gbhyQgz7Y0cNiyi:b-1yalgt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L27)):*
> ```Markdown
> | Component                      | Description                                                                                                                                                           |  Link               |
> | ------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------- |
> | Hardware                       | Send commands to hardware and retrieve raw sensor data                                                                                                                | UAVSystem           |
> ```

Are these supposed to link to the source code?

---

*[markdown_scripts/background.md, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf86TyTe4coIB72964g:-Kf86TyTe4coIB72964h:b-d48rdq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L47)):*
> ```Markdown
> ## GUIFrontEnd (aerial_autonomy.aerial_autonomy_gui.EventTransmissionGUI)
> 
> The GUI should have 1 text box per hardware plugin to get the status + health information of the hardware. It also needs a state text box for getting the current state and status updates towards progress of the goal.  The GUI should be able to send manual triggers to the state machine that are generated by the user. Here is an example GUI FrontEnd:
> ```

Now we have 1 text box for the whole system

---

*[markdown_scripts/background.md, line 52 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87X5DMbL8_ETaC_ZX:-Kf87X5DMbL8_ETaC_ZY:bvurxws) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L52)):*
> ```Markdown
> 
> The Triggers should be connected to the `StateMachine` using `StateMachineGUIConnector` class.
> The triggers are events without any information. There can also be commands with information using `Rviz`  goalpose callbacks to send the drone to a specific location.
> ```

Maybe add something about event generation?

---

*[markdown_scripts/background.md, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87uVXHn0InwD6OsHS:-Kf87uVYzcTEsiaETlka:b-khyymu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L56)):*
> ```Markdown
> ## Classes segregated into groups
> 
> The classes created in this project can be found [here](markdown_scripts/class_groups.md)
> ```

link is broken

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
Reviewed 1 of 17 files at r1.
Review status: 16 of 18 files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
Review status: 16 of 18 files reviewed at latest revision, 19 unresolved discussions.

---

*[README.md, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf88IiPQUK6_KXIUX0M:-Kf88IiPQUK6_KXIUX0N:b-cbdfgm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L17)):*
> ```Markdown
>     sudo apt-get install protobuf-compiler
> 
> ## Running executables
> ```

Capitalize Executables

---

*[README.md, line 26 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf88FQ3J3Ina0k2mJMO:-Kf88FQ3J3Ina0k2mJMP:bss48g3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L26)):*
> ```Markdown
>     rosrun aerial_autonomy rqt_aerial_autonomy_gui  # In a separate tab
> 
> ## Running Tests:
> ```

Remove :

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
Review status: 16 of 18 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[README.md, line 3 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf88rq6JNbZRnIDbxg6:-Kf88rq6JNbZRnIDbxg7:bk7unk4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b53b14a608d350bd86dd4f9a8a6e3c141628121f/README.md#L3)):*
> ```Markdown
> # ASCO Aerial Autonomy
> ```

Perhaps move the link to backround.md to here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by garimellagowtham** [comment]
Deleting build helped me too. Let's see if this helps further.

---

Review status: 13 of 18 files reviewed at latest revision, 21 unresolved discussions, some commit checks failed.

---

*[README.md, line 15 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf81fZszT5J47Pur1Q_:-Kf8D57yo5cL9Ge85fnp:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L15)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Add this to install command above
</blockquote></details>

Done.

---

*[README.md, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf88IiPQUK6_KXIUX0M:-Kf8D02NMfFVZkrxcUz-:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L17)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Capitalize Executables
</blockquote></details>

Done.

---

*[README.md, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf81mn-CbmMYBiNWl6w:-Kf8CyfuAUOvi8EZolCb:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L18)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

an `aerial_autonomy_node`
waits for event commands from a ROS topic
in the rqt_gui framework
</blockquote></details>

Done.

---

*[README.md, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf82917CDir9eS1tpsi:-Kf8CyDQCvacCNns-T6u:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L21)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

using simulated hardware
</blockquote></details>

Done.

---

*[README.md, line 26 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf88FQ3J3Ina0k2mJMO:-Kf8CxpbAnMKfFFNK8TE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L26)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Remove :
</blockquote></details>

Done.

---

*[README.md, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf82LnXJJkrXJLJspeI:-Kf8CxRiaH4Y74DbbwDw:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

from the state machine
(INFO, WARNING, ERROR, etc.)
(0, 1, 2, and so on)
GLOG_V or GLOG_v? just be consistent
the logs folder
using the GLOG_log_dir 
in the Google Log 
</blockquote></details>

Done.

---

*[README.md, line 44 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf83EXjwj1maY5f9a8R:-Kf8CwufJh2mm8pVdIl6:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L44)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We use coverxygen to
</blockquote></details>

Done.

---

*[README.md, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf83_ZfIgWhtB5rNO2v:-Kf8CwKg5cg45QfswoEB:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L49)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

is it still 99%?
</blockquote></details>

Done.

---

*[README.md, line 52 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf83HjdlGKb7rxZSoBT:-Kf8Cv22qtkHQtMoWvwX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L52)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We use lcov to 
generate the test coverage report into the test_coverage_info folder
</blockquote></details>

Done.

---

*[README.md, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf846dwxFUZN97W-8SM:-Kf8CuXrdbOuB0fW--3l:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/README.md#L56)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

the pre-push 
</blockquote></details>

Done.

---

*[README.md, line 3 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf88rq6JNbZRnIDbxg6:-Kf8DIzqMmilwxuY1evX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b53b14a608d350bd86dd4f9a8a6e3c141628121f/README.md#L3)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Perhaps move the link to backround.md to here
</blockquote></details>

Done.

---

*[markdown_scripts/background.md, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85szbvo8GvL8ZpdiJ:-Kf8CsuZuJO8LGMsD9FL:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L1)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Single #
Capitalize Autonomy
</blockquote></details>

Done.

---

*[markdown_scripts/background.md, line 19 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf868lYXd8Hk8DQKYaK:-Kf8DQIIyr_ed_TWH48_:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L19)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Can add OnboardSystemHandler
</blockquote></details>

Done.

---

*[markdown_scripts/background.md, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87gbhyQgz7Y0cNiyh:-Kf8AgCCi8-Te_aq-NKg:b-th51k7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Are these supposed to link to the source code?
</blockquote></details>

The link part of the table should link to source code.

---

*[markdown_scripts/background.md, line 47 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf86TyTe4coIB72964g:-Kf8CrDd4od9SW93S1ne:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L47)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Now we have 1 text box for the whole system
</blockquote></details>

Done.

---

*[markdown_scripts/background.md, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87uVXHn0InwD6OsHS:-Kf8Ck6d4yu2sGA1jDXf:b-vacj58) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L56)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

link is broken
</blockquote></details>

Seems to work fine on my computer. Can you try deleting the docs folder and regenerate everything

---

*[markdown_scripts/class_groups.md, line 14 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85D9NKDtAx4dAErGx:-Kf8Bzd0D87vNI4CS99s:b8hpbq9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/class_groups.md#L14)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Did you make this manually or was it generated automatically by Doxygen?
</blockquote></details>

I created this manually

---

*[markdown_scripts/class_groups.md, line 23 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85OwO_r2FxH-hsk8j:-Kf8CaY1kgzZs77CTSoP:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/class_groups.md#L23)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Shouldn't there be a PositionControlActionFunctor?
</blockquote></details>

Done.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 4 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf84Sayid_dO75S1wr6:-Kf8DaUKv9L0bMON5Vz4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/src/aerial_autonomy/aerial_autonomy_gui.py#L4)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

no comma
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-:-Kf85CjxEbLQy85_UgW2:b-xymo8a)*

**Comment by garimellagowtham** [comment]
Review status: 8 of 18 files reviewed at latest revision, 20 unresolved discussions.

---

*[markdown_scripts/background.md, line 52 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87X5DMbL8_ETaC_ZX:-Kf8GYL88t1wo_MH_9ol:b-9mpzo9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L52)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Maybe add something about event generation?
</blockquote></details>

I will do this tomorrow morning since it requires writing a section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
Reviewed 1 of 3 files at r2, 8 of 9 files at r3.
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[markdown_scripts/background.md, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87gbhyQgz7Y0cNiyh:-Kf8JEPatODscq_y9DMK:b-h0vo5z) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L27)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

The link part of the table should link to source code.
</blockquote></details>

You haven't added any links though

---

*[markdown_scripts/background.md, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87uVXHn0InwD6OsHS:-Kf8JRQyTcZofcQyF067:b-9x9sbn) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L56)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Seems to work fine on my computer. Can you try deleting the docs folder and regenerate everything
</blockquote></details>

It's broken when I click it on github

---

*[markdown_scripts/class_groups.md, line 14 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85D9NKDtAx4dAErGx:-Kf8Ja3PvqUR_DMYYc8H:b-wmckna) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/class_groups.md#L14)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I created this manually
</blockquote></details>

Seeing as we already of doxygen for doing automatic documentation and class list generation, this file probably isn't necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by msheckells** [comment]
Reviewed 1 of 9 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[markdown_scripts/background.md, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87gbhyQgz7Y0cNiyh:-Kf9eAWXxY6YINAomfmy:b-ojw9e9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

You haven't added any links though
</blockquote></details>

The links only works in Doxygen because of auto-link generation

---

*[markdown_scripts/background.md, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf87uVXHn0InwD6OsHS:-Kf9iDoO0udAyqzkihqH:bawpsfz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/background.md#L56)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

It's broken when I click it on github
</blockquote></details>

It works with Doxygen. Doxygen requires that the links are relative to source folder. Markdown uses true relative paths. So unless I write a markdown filter, I could not get both of them working.

I am thinking we might want to host the documentation somehow and link it in the readme file for github. So both github and doxygen need not share the same code.

---

*[markdown_scripts/class_groups.md, line 14 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33#-Kf85D9NKDtAx4dAErGx:-Kf9ijeqntzYKFv4ky87:b5k637x) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b4a899da481c38f2116e14ee059690b00d4864e/markdown_scripts/class_groups.md#L14)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Seeing as we already of doxygen for doing automatic documentation and class list generation, this file probably isn't necessary
</blockquote></details>

I like this file since it arranges the classes by groups. It is hard to understand the class list from Doxygen.  If I can change the way the class list is organized, it will be fine. I am not sure how to do that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/33)*

**Pull request merged**
