### PR TITLE
Integrate log

### PR DESCRIPTION
**Pull request by msheckells**
Review the time stamp one first

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/90)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/common/proto_utils.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOLKuSjJQWDbJBgxep:-KsOLKuSjJQWDbJBgxeq:b-t6gb9c) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/include/aerial_autonomy/common/proto_utils.h#L16)):*
> ```objc
> * @tparam T Class of proto to load
> */
> template <class T> bool loadProtoText(std::string path, T &proto) {
> ```

Add tests for this function

---

*[include/aerial_autonomy/controllers/builtin_controller.h, line 70 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOFpRhXUHmxPNb7RZi:-KsOFpRi27_xuJJLqNbN:bzbak1h) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/include/aerial_autonomy/controllers/builtin_controller.h#L70)):*
> ```objc
>     status << "PositionYawDiff: " << position_yaw_diff.x << position_yaw_diff.y
>            << position_yaw_diff.z << position_yaw_diff.yaw;
>     Log::instance()["builtin_position_controller"]
> ```

Can we create a macro like LOG("string") to mean  Log:: instance ("string')<<startl

---

*[param/log_config.pbtxt, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOGwPG43Gn2I7-z0xv:-KsOGwPG43Gn2I7-z0xw:b-r0hnxf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/param/log_config.pbtxt#L1)):*
> ```
> directory: "/tmp/aerial_autonomy"
> ```

We should make this project directory using cmake  configure function

---

*[src/controllers/relative_pose_controller.cpp, line 30 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOKDm9tpHyOFYdKDdj:-KsOKDm9tpHyOFYdKDdk:bcq5ol8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/src/controllers/relative_pose_controller.cpp#L30)):*
> …src/system_handler_nodes/uav_vision_system_node.cppsrc/system_handler_nodes/
Should log sensor data and controls and state information

---

*[src/controllers/velocity_based_position_controller.cpp, line 30 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOKsv4N-GLqn5fTTSA:-KsOKsv4N-GLqn5fTTSB:bjankvy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/src/controllers/velocity_based_position_controller.cpp#L30)):*
> ```cpp
>          << position_diff.z << position_diff.yaw;
>   Log::instance()["velocity_based_position_controller"]
>       << DataStream::startl << position_diff.x << position_diff.y
> ```

Where are the headers for the log messages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by garimellagowtham** [comment]
We should also add the git commit tag to log directory if possible. This will help locate /identify the version of code used to produce the log data. This can be a todo for later also.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-:-KsOlvBM5OAgY1nuVx0O:bnzlq2q)*

**Comment by garimellagowtham** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by msheckells** [comment]
Yeah, that would be useful.  Added TODO.

---

Review status: 11 of 21 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/common/proto_utils.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOLKuSjJQWDbJBgxep:-KsPpyZxkoo1EUcczye9:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/include/aerial_autonomy/common/proto_utils.h#L16)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add tests for this function
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/builtin_controller.h, line 70 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOFpRhXUHmxPNb7RZi:-KsPwCveXXuP4nz14Lqv:bs7wumx) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/include/aerial_autonomy/controllers/builtin_controller.h#L70)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can we create a macro like LOG("string") to mean  Log:: instance ("string')<<startl
</blockquote></details>

Done. 

---

*[src/controllers/relative_pose_controller.cpp, line 30 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOKDm9tpHyOFYdKDdj:-KsPwLG8wPj5lsnxgw7U:bsajkw3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/src/controllers/relative_pose_controller.cpp#L30)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

> …src/system_handler_nodes/uav_vision_system_node.cppsrc/system_handler_nodes/
Should log sensor data and controls and state information
</blockquote></details>

Why? Does that give us anything that the error does not give us already?

---

*[src/controllers/velocity_based_position_controller.cpp, line 30 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOKsv4N-GLqn5fTTSA:-KsPtwLyVWmyrORODe_u:b-o2d2tb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/src/controllers/velocity_based_position_controller.cpp#L30)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Where are the headers for the log messages?
</blockquote></details>

I didn't add any yet.  

---

*[param/log_config.pbtxt, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOGwPG43Gn2I7-z0xv:-KsPtmYaE6i_CQeUZO4X:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/param/log_config.pbtxt#L1)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We should make this project directory using cmake  configure function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-:-KsPU3wTUGB9GDNOWWra:bj2oh05)*

**Comment by garimellagowtham** [comment]
Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[param/log_config.pbtxt.in, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsQAdrFNYCONQJMX1nD:-KsQAdrGOoCerB4j3nYQ:b-6ughem) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ce483444460c39ca568f9362203e3d05b9c852c1/param/log_config.pbtxt.in#L3)):*
> ```
> # This file is automatically generated! Make changes to log_config.pbtxt.in
> 
> directory: "${PROJECT_SOURCE_DIR}/logs"
> ```

There is a logs folder already that is being used for GLOG. We can use that or make a new one. Do we have to create this folder for the logging to work?

---

*[src/controllers/relative_pose_controller.cpp, line 30 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOKDm9tpHyOFYdKDdj:-KsQAs3Hn82rYNKttDQQ:b-y8fuij) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/src/controllers/relative_pose_controller.cpp#L30)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why? Does that give us anything that the error does not give us already?
</blockquote></details>

Like what if the error is significant? Is the sensor data wrong or state bad? Is sensor data noisy?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[param/log_config.pbtxt.in, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsQAdrFNYCONQJMX1nD:-KsQHqJH3U43pov6jBv3:biyyilw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ce483444460c39ca568f9362203e3d05b9c852c1/param/log_config.pbtxt.in#L3)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

That is the same folder used by glog.  The folder is created automatically by Log if it does not exist
</blockquote></details>

I was thinking we might want a separate folder for these stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[param/log_config.pbtxt.in, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsQAdrFNYCONQJMX1nD:-KsQI-i8ghDDfbsSBrmq:bx4girg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ce483444460c39ca568f9362203e3d05b9c852c1/param/log_config.pbtxt.in#L3)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I was thinking we might want a separate folder for these stuff.
</blockquote></details>

How about /logs/data?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[param/log_config.pbtxt.in, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsQAdrFNYCONQJMX1nD:-KsQJ4BhZH7u6T64dig1:b2nhll9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ce483444460c39ca568f9362203e3d05b9c852c1/param/log_config.pbtxt.in#L3)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

How about /logs/data?
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by msheckells** [comment]
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[param/log_config.pbtxt.in, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsQAdrFNYCONQJMX1nD:-KsdGgO868hVPNQz1gp_:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ce483444460c39ca568f9362203e3d05b9c852c1/param/log_config.pbtxt.in#L3)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

Done.

---

*[src/controllers/relative_pose_controller.cpp, line 30 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsOKDm9tpHyOFYdKDdj:-KsdPFiX3fJSdcNSV3AW:b-l4fpfr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9efc59dabfacee32d2e42f44720c1dafcb6d88c3/src/controllers/relative_pose_controller.cpp#L30)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Like what if the error is significant? Is the sensor data wrong or state bad? Is sensor data noisy?
</blockquote></details>

Ok. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 11 files at r3, 4 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/relative_pose_controller.cpp, line 29 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsdzSUXCz5g8McuflDB:-KsdzSUXCz5g8McuflDC:b-wvebul) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/31f82a5919c8a65e531d0ebbbb875a161e5f9795/src/controllers/relative_pose_controller.cpp#L29)):*
> ```cpp
>   status << "Error Position, Rotation: " << abs_error_position.x()
>          << abs_error_position.y() << abs_error_position.z() << rot_diff;
>   tf::Quaternion current_rot = current_pose.getRotation();
> ```

Use const references

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/relative_pose_controller.cpp, line 29 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90#-KsdzSUXCz5g8McuflDB:-Kse-mcKvtB5GF-LNhw4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/31f82a5919c8a65e531d0ebbbb875a161e5f9795/src/controllers/relative_pose_controller.cpp#L29)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Use const references
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/90)*

**Pull request merged**
