### PR TITLE
Make position tolerance a vector

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/85)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 29 of 29 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/controllers/relative_pose_controller_tests.cpp, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/85#-Ks5h8MZSf4XRCdoRsas:-Ks5h8MZSf4XRCdoRsat:b-ppecg4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a33ddbd05e5e0a64f66b71a2c470913f6f67cc31/tests/controllers/relative_pose_controller_tests.cpp#L5)):*
> ```cpp
> #include <gtest/gtest.h>
> 
> class RelativePoseControllerTests : public ::testing::Test {
> ```

Add test for unequal tolerances in x, y, z positions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/85)*

**Comment by msheckells** [comment]
Review status: 24 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/controllers/relative_pose_controller_tests.cpp, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/85#-Ks5h8MZSf4XRCdoRsas:-Ks5jd5N49g-cNu26i5d:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a33ddbd05e5e0a64f66b71a2c470913f6f67cc31/tests/controllers/relative_pose_controller_tests.cpp#L5)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add test for unequal tolerances in x, y, z positions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/85)*

**Comment by garimellagowtham** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r2.
Review status: 25 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/85#-:-Ks5kEc7qNXOV1tgSVVa:bnfp4nl)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/85)*

**Pull request merged**
