### PR TITLE
Add interface mpc connector

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h, line 7 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXju16u3pPLBJN1AN:-LCdXju16u3pPLBJN1AO:bgyw07i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h#L7)):*
> ```objc
> * @brief Generates obstacles based on sensor data
> */
> struct AbstractConstraintGenerator {
> ```

why a struct?

---

*[include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h, line 9 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdY0nh7brMTYEc7zlt:-LCdY0nh7brMTYEc7zlu:b-pi3apw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h#L9)):*
> ```objc
> struct AbstractConstraintGenerator {
>   /**
>   * @brief Generate constraint vector based on sensor data
> ```

nothing requires this to be based on sensor data

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 11 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXpTGBVbEdC_cAL7d:-LCdXpTGBVbEdC_cAL7e:b-e04583) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L11)):*
> ```objc
> * @tparam ControlT The type of control
> */
> template <class StateT, class ControlT> struct AbstractControlSelector {
> ```

why struct?

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 22 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdYDPd131_jQHQaJrz:-LCdYDPd131_jQHQaJs-:b-j7c73b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L22)):*
> ```objc
>   virtual ControlT
>   selectControl(const ReferenceTrajectory<StateT, ControlT> &trajectory,
>                 StateT current_state) = 0;
> ```

time is explicitly not included in the state.  Shouldn't it be given as a param here?

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 22 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdYP6fE_3rjrzKWflD:-LCdYP6fE_3rjrzKWflE:b-1zww0o) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L22)):*
> ```objc
>   virtual ControlT
>   selectControl(const ReferenceTrajectory<StateT, ControlT> &trajectory,
>                 StateT current_state) = 0;
> ```

current_state can also be const ref

---

*[include/aerial_autonomy/controllers/mpc_controller.h, line 9 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdb2AV-01RhgHrRwlD:-LCdb2AV-01RhgHrRwlE:b-bli9sk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controllers/mpc_controller.h#L9)):*
> ```objc
> * @brief Generic MPC Controller.
> *
> * Specifies the sensordata, Goal and Control for the controller. Other
> ```

sensor data,  goal, and control

---

*[include/aerial_autonomy/estimators/state_estimator.h, line 15 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbFpV86BeV4STAW1L:-LCdbFpV86BeV4STAW1M:bj9euhf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/estimators/state_estimator.h#L15)):*
> ```objc
>   * @brief Run estimator loop. Propagates the estimator loop
>   *
>   * @param t Current time
> ```

current time or the duration of the control?

---

*[include/aerial_autonomy/estimators/state_estimator.h, line 26 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbLPKEAdgJH6U7sYy:-LCdbLPL4D6GTPDWrOY7:bln1xvo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/estimators/state_estimator.h#L26)):*
> ```objc
>   * @return The initial state estimate
>   */
>   virtual StateT getState() = 0;
> ```

does get state need to be called with a current time, as well,  since you may have to propagate the state if it was updated some time ago?

---

*[include/aerial_autonomy/types/generic_constraint.h, line 40 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbitc5OXiyeEV7V8I:-LCdbitc5OXiyeEV7V8J:b-o0w6ad) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/generic_constraint.h#L40)):*
> ```objc
>   tf::Transform transform;
>   /**
>   * @brief The lenght of the obstacle along the body x, y, z axes
> ```

length

---

*[include/aerial_autonomy/types/quad_state.h, line 19 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbqwa8L6ofiyyh2Eo:-LCdbqwa8L6ofiyyh2Ep:b-c1x2g0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/quad_state.h#L19)):*
> ```objc
>   * @brief The derivative of roll, pitch, yaw
>   */
>   tf::Vector3 rpydot;
> ```

rpy_dot

---

*[include/aerial_autonomy/types/quad_state.h, line 23 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbrsV4IFMavQfFzIo:-LCdbrsV4IFMavQfFzIp:b-7kgz4f) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/quad_state.h#L23)):*
> ```objc
>   * @brief The desired roll, pitch, yaw
>   */
>   tf::Vector3 rpyd;
> ```

rpy_desired

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/controller_connectors/mpc_controller_connector.h, line 85 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdgiWQ-BNpnFGh6bGZ:-LCdgiWRAhzC6TqVtry9:b-rqrc4r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/mpc_controller_connector.h#L85)):*
> ```objc
>     auto relative_time = std::chrono::duration<double>(
>         std::chrono::high_resolution_clock::now() - t0_);
>     state_estimator_.propagate(relative_time, control);
> ```

make timing internal to estimator

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by msheckells** [comment]
*[include/aerial_autonomy/types/generic_constraint.h, line 1 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCe2CfZAHDhSzM5Zy6l:-LCe2CfZAHDhSzM5Zy6m:b-8m45a6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/generic_constraint.h#L1)):*
> ```objc
> #pragma once
> ```

name the file constraint

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by garimellagowtham** [comment]
Review status: 5 of 12 files reviewed at latest revision, 13 unresolved discussions.

---

*[include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h, line 7 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXju16u3pPLBJN1AN:-LCe8_TZ4jAuaOzh0tDH:b-d65ck7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h#L7)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

why a struct?
</blockquote></details>

Currently, all the functions in this abstract class are public. I can use the class declaration with a public declaration if you want me to!

---

*[include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h, line 9 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdY0nh7brMTYEc7zlt:-LCe8rSCAOYqe-1bcSVp:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h#L9)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

nothing requires this to be based on sensor data
</blockquote></details>

Done

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 11 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXpTGBVbEdC_cAL7d:-LCe9UaE27qY2YpejHBO:b-jyod6n) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L11)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

why struct?
</blockquote></details>

Again all the members are public. I can use the class declaration if you want. I don't see any difference.

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 22 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdYDPd131_jQHQaJrz:-LCe9ffVBM8WHmIay87O:b-x9uorb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L22)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

time is explicitly not included in the state.  Shouldn't it be given as a param here?
</blockquote></details>

The reference trajectory contains times as a vector.

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 22 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdYP6fE_3rjrzKWflD:-LCe9nMO76XbNpavNEN6:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L22)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

current_state can also be const ref
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_connectors/mpc_controller_connector.h, line 85 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdgiWQ-BNpnFGh6bGZ:-LCeCEDZAnLBdQRy7aDa:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/mpc_controller_connector.h#L85)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

make timing internal to estimator
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/mpc_controller.h, line 9 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdb2AV-01RhgHrRwlD:-LCeCOIM0466RmGEOWFs:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controllers/mpc_controller.h#L9)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

sensor data,  goal, and control
</blockquote></details>

Done.

---

*[include/aerial_autonomy/estimators/state_estimator.h, line 15 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbFpV86BeV4STAW1L:-LCeCQeJCrKSxEojefqS:b-i0tsfk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/estimators/state_estimator.h#L15)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

current time or the duration of the control?
</blockquote></details>

Removed the time. The estimator will use the time when the control is received.

---

*[include/aerial_autonomy/estimators/state_estimator.h, line 26 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbLPKEAdgJH6U7sYy:-LCeCYx19BMokvFTDWTQ:b5sh2o2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/estimators/state_estimator.h#L26)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

does get state need to be called with a current time, as well,  since you may have to propagate the state if it was updated some time ago?
</blockquote></details>

It will produce the state based on when the function is called i.e use it's own internal clock to figure out when getState is called and use that time.

---

*[include/aerial_autonomy/types/quad_state.h, line 19 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbqwa8L6ofiyyh2Eo:-LCeDBTK5am58RJ-7VQY:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/quad_state.h#L19)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

rpy_dot
</blockquote></details>

Done.

---

*[include/aerial_autonomy/types/quad_state.h, line 23 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbrsV4IFMavQfFzIo:-LCeDBDcCgmt61q6D8v0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/quad_state.h#L23)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

rpy_desired
</blockquote></details>

Done.

---

*[include/aerial_autonomy/types/generic_constraint.h, line 1 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCe2CfZAHDhSzM5Zy6l:-LCeCmYx5yKc_pzNTrjn:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/generic_constraint.h#L1)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

name the file constraint
</blockquote></details>

Done

---

*[include/aerial_autonomy/types/generic_constraint.h, line 40 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdbitc5OXiyeEV7V8I:-LCeD0jU2nvCb7qLEowj:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/types/generic_constraint.h#L40)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

length
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by msheckells** [comment]
Reviewed 4 of 9 files at r2.
Review status: 8 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h, line 7 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXju16u3pPLBJN1AN:-LCexabVEG0LcUns1U4J:bv2dcid) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h#L7)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Currently, all the functions in this abstract class are public. I can use the class declaration with a public declaration if you want me to!
</blockquote></details>

Yeah i think it makes more sense for it to be a class.  It's safer to have it default everything to private since it is possible that we won't want everything to be public.

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 11 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXpTGBVbEdC_cAL7d:-LCexraRAs9nMj-W10Er:bbxgkzp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L11)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Again all the members are public. I can use the class declaration if you want. I don't see any difference.
</blockquote></details>

Same comment as above

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 22 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdYDPd131_jQHQaJrz:-LCexvRB6urVy8XfyWhf:b-n2unph) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L22)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

The reference trajectory contains times as a vector.
</blockquote></details>

I mean the the time associated with the current_state i.e. the current time

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by msheckells** [comment]
Reviewed 4 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by garimellagowtham** [comment]
Review status: 9 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h, line 7 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXju16u3pPLBJN1AN:-LCf2rRJ-ZoNAXoVRPLC:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_constraint_generator.h#L7)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Yeah i think it makes more sense for it to be a class.  It's safer to have it default everything to private since it is possible that we won't want everything to be public.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 11 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdXpTGBVbEdC_cAL7d:-LCf2sCQDWDGh4bTya8H:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L11)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_connectors/abstract_control_selector.h, line 22 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181#-LCdYDPd131_jQHQaJrz:-LCf2snw04CQfUDzjI3E:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/460db8b35e4fba9350de8c1cad4c5162db04dc0f/include/aerial_autonomy/controller_connectors/abstract_control_selector.h#L22)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I mean the the time associated with the current_state i.e. the current time
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Comment by msheckells** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/181)*

**Pull request merged**
