### PR TITLE
Append datetime string to log path

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/89)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/log/log.cpp, line 13 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89#-KsMBtQm5_OYbB_HA1wj:-KsMBtQnu-fy8kcc45vL:bbucg59) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7ad472fecd251bd7b1b29710fd8db24048ffdd6d/src/log/log.cpp#L13)):*
> ```cpp
>   std::time_t t = std::time(nullptr);
>   char time_str[100];
>   if (std::strftime(time_str, sizeof(time_str), "_%y_%m_%d_%H_%M_%S",
> ```

We can create a util function that adds a timestamp to end of a string. That way we can test the function easily.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89)*

**Comment by msheckells** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/log/log.cpp, line 13 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89#-KsMBtQm5_OYbB_HA1wj:-KsOwre8pzjmrOJlNCkE:b-1u708i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2991fb6fc20a3bc87f3708a4d2dbb2e7f21e5122/src/log/log.cpp#L13)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We can create a util function that adds a timestamp to end of a string. That way we can test the function easily.
</blockquote></details>

Moved to a function in a common header.  Not really sure how to test the function for correctness though given that its hard to know the exact time the string was generated.  Without knowing the time, we can't guarantee it is correct.  I check the string to make sure it contains numbers in the proper places with the current number of digits per number

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89)*

**Comment by garimellagowtham** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/log/log.cpp, line 13 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89#-KsMBtQm5_OYbB_HA1wj:-KsP1FDsAx5od8LmhUpf:b-g5gj6c) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2991fb6fc20a3bc87f3708a4d2dbb2e7f21e5122/src/log/log.cpp#L13)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Moved to a function in a common header.  Not really sure how to test the function for correctness though given that its hard to know the exact time the string was generated.  Without knowing the time, we can't guarantee it is correct.  I check the string to make sure it contains numbers in the proper places with the current number of digits per number
</blockquote></details>

You can use `ASSERT_MATCH` to check the string has the right format. You can also check for the day, hour, year, etc. But seconds, etc. you can leave for now.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89)*

**Comment by garimellagowtham** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/89)*

**Pull request merged**
