### PR TITLE
Html tables

### PR DESCRIPTION
**Pull request by garimellagowtham**
Add HTML scripts to display status nicely

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/76)

### CODE REVIEW

**Comment by msheckells** [comment]
This includes the changes from the matrice-grasping-changes branch?

---

Reviewed 1 of 16 files at r3, 1 of 11 files at r4.
Review status: 2 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-:-Kqj8A7P9fKWfytPnjhm:bgy8y9j)*

**Comment by garimellagowtham** [comment]
I merged that branch in here since I had to update tracker status. I am merging the matrice-grasping-changes branch first
That should fix the diff hopefully

---

Review status: 2 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-:-Kqj8ONxWfyFjfLh7OGR:b9symiv)*

**Comment by garimellagowtham** [comment]
Check the review now!

---

Review status: 1 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-:-KqjA7loL6mhvMPiXBSf:b-6s09kp)*

**Comment by msheckells** [comment]
Reviewed 1 of 9 files at r1, 9 of 16 files at r3, 9 of 11 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/common/html_utils_tests.cpp, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-KqjBLVWAV4WEvGs0K03:-KqjBLVXggsS4IVpZEss:b-2eudnn) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7dc5ce48916e16bb563fe5a4852dc039e6b9a129/tests/common/html_utils_tests.cpp#L16)):*
> ```cpp
>   table_writer.addCell("Data");
>   table_writer.addCell("Data", "Hello", Colors::white);
>   std::cout << "Table: \n" << table_writer.getTableString() << std::endl;
> ```

Hard to test this kind of thing... maybe we can somehow verify if the text string is valid html? Not too important for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/common/html_utils_tests.cpp, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-KqjBLVWAV4WEvGs0K03:-KqjCrCmEPhQsLCJyGTP:b-bpr7he) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7dc5ce48916e16bb563fe5a4852dc039e6b9a129/tests/common/html_utils_tests.cpp#L16)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Hard to test this kind of thing... maybe we can somehow verify if the text string is valid html? Not too important for now
</blockquote></details>

There is an online HTML validator I used to check if the string is ok or not http://www.htmlhelp.com/tools/validator/direct.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/common/html_utils_tests.cpp, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-KqjBLVWAV4WEvGs0K03:-KqjDGIE5raxd7PqMlZP:b-wy21ym) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7dc5ce48916e16bb563fe5a4852dc039e6b9a129/tests/common/html_utils_tests.cpp#L16)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

There is an online HTML validator I used to check if the string is ok or not http://www.htmlhelp.com/tools/validator/direct.html
</blockquote></details>

Gothca, it would be nice if there were a way to test it programatically, maybe add a todo for it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76)*

**Comment by garimellagowtham** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/common/html_utils_tests.cpp, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76#-KqjBLVWAV4WEvGs0K03:-KqjE08P1GYQFJwkvDr8:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7dc5ce48916e16bb563fe5a4852dc039e6b9a129/tests/common/html_utils_tests.cpp#L16)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Gothca, it would be nice if there were a way to test it programatically, maybe add a todo for it
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76)*

**Comment by msheckells** [comment]
Reviewed 1 of 11 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/76)*

**Pull request merged**
