### PR TITLE
Added acado controller

### PR DESCRIPTION
**Pull request by sohampatkar10**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/169)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/common/acado_higher_level_controller.h, line 13 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L96wpRq5SW_aKDTf3mc:-L96wpRq5SW_aKDTf3md:b-koajy9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/include/aerial_autonomy/common/acado_higher_level_controller.h#L13)):*
> ```objc
> #include "aerial_autonomy/types/trajectory.h"
> /**
> * Class of Acado-Related functions for
> ```

for what?

---

*[include/aerial_autonomy/common/acado_higher_level_controller.h, line 39 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9BWaZ3A5TrSNV_ajIF:-L9BWaZ3A5TrSNV_ajIG:bjyayc5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/include/aerial_autonomy/common/acado_higher_level_controller.h#L39)):*
> ```objc
>   bool
>   solve(const std::tuple<QuadFlatOutput, std::vector<Obstacle>> &sensor_data,
>         QuadFlatOutput goal, Trajectory<QuadFlatOutput> &control);
> ```

could we still have this class take a reference state and control trajectory (rather than just a goal state) so that it is more versatile?

---

*[include/aerial_autonomy/common/acado_higher_level_controller.h, line 53 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L96H4ix6OUkQtZ0AJ5t:-L96H4ix6OUkQtZ0AJ5u:b-pcpc6q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/include/aerial_autonomy/common/acado_higher_level_controller.h#L53)):*
> ```objc
>   * @param goal Desired Final State
>   */
>   void setInitialandGoalState(QuadFlatOutput initial, QuadFlatOutput goal);
> ```

setInitialAndGoalState

---

*[src/common/acado_higher_level_controller.cpp, line 72 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9BWyVJ3nksPwtlvXdS:-L9BWyVJ3nksPwtlvXdT:bub79gd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/src/common/acado_higher_level_controller.cpp#L72)):*
> ```cpp
>   algorithm_->getDifferentialStates(xi);
>   algorithm_->getControls(ui);
>   std::vector<Obstacle> obstacle_list = std::get<1>(sensor_data);
> ```

If obstacle list is empty, we don't have to solve problem twice.

---

*[tests/common/acado_higher_level_controller_tests.cpp, line 45 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9BYrJXDFqWfF_3u4ja:-L9BYrJXDFqWfF_3u4jb:blqslmi) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/tests/common/acado_higher_level_controller_tests.cpp#L45)):*
> ```cpp
> 
>   ASSERT_TRUE(result);
> }
> ```

will need a test to verify trajectory takes you to goal

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169)*

**Comment by sohampatkar10** [comment]
Review status: 7 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/common/acado_higher_level_controller.h, line 39 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9BWaZ3A5TrSNV_ajIF:-L9GwIsCCr2S6jGnocrq:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/include/aerial_autonomy/common/acado_higher_level_controller.h#L39)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

could we still have this class take a reference state and control trajectory (rather than just a goal state) so that it is more versatile?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169)*

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/common/acado_higher_level_controller.cpp, line 178 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9HD2f91yu2yqgV58rn:-L9HD2f91yu2yqgV58ro:b3oh8sg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b13fab3ffd520ba5da70cc925ffd3e0d645b1afc/src/common/acado_higher_level_controller.cpp#L178)):*
> ```cpp
> 
>   if (config_.terminal_constraint()) {
>     QuadFlatOutput final_state = goal.trajectory[0];
> ```

isn't this getting the first state, not the last state?

---

*[src/common/acado_higher_level_controller.cpp, line 209 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9HDDFH6Kt2oHutZVu2:-L9HDDFH6Kt2oHutZVu3:b-xi48a8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b13fab3ffd520ba5da70cc925ffd3e0d645b1afc/src/common/acado_higher_level_controller.cpp#L209)):*
> ```cpp
>     ocp_.minimizeLSQ(Q, eta, offset);
>   } else {
>     // \todo Add cost for deviation from reference trajectory
> ```

print some warning here until it is implemented.  Also the reference cost is not mutually exclusive from the terminal constraint.  It can have both a terminal constraint and a reference state/control cost.

---

*[tests/common/acado_higher_level_controller_tests.cpp, line 45 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9BYrJXDFqWfF_3u4ja:-L9HDZiZ9Ns3uBs_kdHk:bphj9le) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/dfbce3e7434f94240155c338c9f9a4d3a7d6e01e/tests/common/acado_higher_level_controller_tests.cpp#L45)):*
<details><summary><i>Previously, sohampatkar10 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That's good.  What I meant was that applying the controls to a simulated system gets you to the goal.  Can probably save that test for the Controller that uses this class.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169)*

**Comment by msheckells** [comment]
Reviewed 1 of 2 files at r3.
Review status: 11 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/common/acado_higher_level_controller.h, line 39 at r3](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9IUVVC93nd8m7J2yhj:-L9IUVVC93nd8m7J2yhk:b-ymw6yi) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2e7d9bc9a2e35cf90cabb00683525e933f016082/include/aerial_autonomy/common/acado_higher_level_controller.h#L39)):*
> ```objc
>   bool
>   solve(const std::tuple<QuadFlatOutput, std::vector<Obstacle>> &sensor_data,
>         Trajectory<QuadFlatOutput> &goal, Trajectory<QuadFlatOutput> &control);
> ```

why not const?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169)*

**Comment by msheckells** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169)*

**Comment by sohampatkar10** [comment]
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/common/acado_higher_level_controller.h, line 39 at r3](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169#-L9IUVVC93nd8m7J2yhj:-L9RGdcIAcA1lIGlFv0I:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2e7d9bc9a2e35cf90cabb00683525e933f016082/include/aerial_autonomy/common/acado_higher_level_controller.h#L39)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

why not const?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/169)*

**Pull request merged**
