### PR TITLE
Add macro and tests to event manager

### PR DESCRIPTION
**Pull request by garimellagowtham**
1. Add tests for event manager class
2. Create event manager from event using cmake function
3. Save event files to devel space

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/2)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 5 of 6 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.xml, line 46 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOQfhm5cMEXbBweO0l:-KcOQfhm5cMEXbBweO0m:b3sd82t) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/package.xml#L46)):*
> ```XML
>   <build_depend>std_msgs</build_depend>
>   <build_depend>rqt_gui_py</build_depend>
>   <run_depend>python-rospkg</run_depend>
> ```

does this need to be a build_depend as well?

---

*[package.xml, line 50 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOQj-5jROJlheG1lbI:-KcOQj-5jROJlheG1lbJ:b-5h08bq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/package.xml#L50)):*
> ```XML
>   <run_depend>rospy</run_depend>
>   <run_depend>std_msgs</run_depend>
>   <run_depend version_gte="0.2.12">rqt_gui</run_depend>
> ```

same here?

---

*[tests/event_manager_tests/event_manager_tests.cpp, line 29 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOT-LAD9eQw-92-WNG:-KcOT-LAD9eQw-92-WNH:b-gvn22j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/tests/event_manager_tests/event_manager_tests.cpp#L29)):*
> ```cpp
> 	}
> 	TEST(BasicEventManagerTest, TriggerEvents) {
> 		BasicEventManager<LSM> evt_manager;
> ```

Inconsistent indentation

---

*[tests/event_manager_tests/event_manager_tests.cpp, line 42 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOT4D5cdFb_7TgGgbJ:-KcOT4D5cdFb_7TgGgbK:b-gvn22j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/tests/event_manager_tests/event_manager_tests.cpp#L42)):*
> ```cpp
> 	TEST(VisualServoingEventManagerTest, TriggerEvents) {
> 		VisualServoingEventManager<LSM> evt_manager;
>     LSM lsm;
> ```

Inconsistent indentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2)*

**Comment by garimellagowtham** [comment]
Review status: 10 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[package.xml, line 46 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOQfhm5cMEXbBweO0l:-KcOUI7apa8Ekby9Kxb8:b-8sc7w) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/package.xml#L46)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

does this need to be a build_depend as well?
</blockquote></details>

python does not have build step. So I guess this is only run dependency. I copied this from rqt_top package: https://github.com/ros-visualization/rqt_common_plugins/blob/master/rqt_top/package.xml

---

*[package.xml, line 50 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOQj-5jROJlheG1lbI:-KcOUqWTAL7XQ-mGLzxD:bccu0o0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/package.xml#L50)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

same here?
</blockquote></details>

Explained above.

---

*[tests/event_manager_tests/event_manager_tests.cpp, line 29 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOT-LAD9eQw-92-WNG:-KcOUmrzD1JI_KWTokJ4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/tests/event_manager_tests/event_manager_tests.cpp#L29)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Inconsistent indentation
</blockquote></details>

Done.

---

*[tests/event_manager_tests/event_manager_tests.cpp, line 42 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcOT4D5cdFb_7TgGgbJ:-KcOUnkwS1FEbrsbMEur:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/76b8d6b6017e32f5ed777bd74a5e5f8557dbae58/tests/event_manager_tests/event_manager_tests.cpp#L42)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Inconsistent indentation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2)*

**Comment by msheckells** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-:-KcOXmQeqZGzPhNqfpyX:bnfp4nl)*

**Comment by msheckells** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-:-KcUGITWIJLa6e9Op84Q:bnfp4nl)*

**Comment by msheckells** [comment]
*[scripts/generate_event_file.py, line 83 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcUvrXW2Y5XY-vUqO3r:-KcUvrXW2Y5XY-vUqO3s:b-swiu1b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/633dc7549924ed374d6d7b059abe5f46ae241140/scripts/generate_event_file.py#L83)):*
> ```Python
>         "  Do not edit this file manually **/\n"
>         "#include<functional>\n"
>         "#include<iostream>\n"
> ```

Add spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2)*

**Comment by garimellagowtham** [comment]
Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/generate_event_file.py, line 83 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2#-KcUvrXW2Y5XY-vUqO3r:-KcV2qTosF9Q3WtWvBP7:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/633dc7549924ed374d6d7b059abe5f46ae241140/scripts/generate_event_file.py#L83)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Add spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/2)*

**Pull request merged**
