### PR TITLE
Basic statemachine gui connector

### PR DESCRIPTION
**Pull request by garimellagowtham**
Big branch to get a basic state machine. Still, some more tests to be completed.

I think each commit can be reviewed separately on github. Reviewable combines all commits and its not easy to review such a big PR

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/7)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 15 of 25 files at r1.
Review status: 15 of 25 files reviewed at latest revision, 13 unresolved discussions.

---

*[.gitignore, line 4 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaZ-RAluC4RqEPIya9:-KdaZ-RBh57SqpaBMkFt:biwvyop) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/.gitignore#L4)):*
> ```
> *.pyc
> *.swp
> include/aerial_autonomy/logic_states/robot_system_wrapper.h
> ```

Why is this necessary?

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 46 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaZV00T7BMwb33DrFB:-KdaZV00T7BMwb33DrFC:b-rpacnd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/base_functors.h#L46)):*
> ```objc
> /// Add the guard functor to be a friend to robot wrapper
> /// Put static assert to make sure logicstatemachine is supplying the same robot
> /// system
> ```

Are these supposed to be TODOs?

---

*[include/aerial_autonomy/actions_guards/hovering_functors.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kda_Qc9HsX_Q_rORdFF:-Kda_Qc9HsX_Q_rORdFG:b4gzc2r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/hovering_functors.h#L16)):*
> ```objc
>            LogicStateMachineT &logic_state_machine) {
>     parsernode::common::quaddata data = robot_system.getQuadData();
>     // Transition to hovering state once reached high altitude
> ```

Does it need to do anything like set a position controller to maintain current position?

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kda_Z96xGsbCONQxJoG:-Kda_Z96xGsbCONQxJoH:b-rhylsa) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/land_functors.h#L27)):*
> ```objc
>            LogicStateMachineT &logic_state_machine) {
>     parsernode::common::quaddata data = robot_system.getQuadData();
>     // Transition to hovering state once reached high altitude
> ```

Copy pasted comment

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaamEiJFt3nOyH7eSq:-KdaamEjYpdX_XpcOVsY:b-x3jh2h) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L38)):*
> ```objc
>     // Check goal is close to position before sending goal (Can use a geofence
>     // here)
>     double tolerance_pos =
> ```

This should be set by some parameter.  Add a TODO.

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 41 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kdab50iDXDiaWPOQMPr:-Kdab50iDXDiaWPOQMPs:b-eh48sr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L41)):*
> ```objc
>         100; // Ensure the goal is within 100 meters of the current position
>     bool result = true;
>     if (std::abs(current_position.x - goal.x) > tolerance_pos &&
> ```

Should be ||

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 44 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kdab6FZimIBBl70bcpa:-Kdab6FZimIBBl70bcpb:b-b92e42) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L44)):*
> ```objc
>         std::abs(current_position.y - goal.y) > tolerance_pos &&
>         std::abs(current_position.z - goal.z) > tolerance_pos) {
>       result = true;
> ```

Should be false

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 64 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdabUXiBghetv2rtFDU:-KdabUXiBghetv2rtFDV:bf6h0f) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L64)):*
> ```objc
>     double yaw = data.rpydata.z;
>     // Define tolerance and check if reached goal
>     double tolerance_pos = 1.0; // m
> ```

Should be defined in some parameters somehow.  Add a TODO.

---

*[include/aerial_autonomy/actions_guards/takeoff_functors.h, line 53 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdablMwKw26ky_JY3Zx:-KdablMwKw26ky_JY3Zy:b-yjt9iz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/takeoff_functors.h#L53)):*
> ```objc
>     parsernode::common::quaddata data = robot_system.getQuadData();
>     // If battery too low abort and goto landed mode
>     if (data.batterypercent < 40) {
> ```

Should be configurable.  Add TODO

---

*[include/aerial_autonomy/actions_guards/takeoff_functors.h, line 57 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdabjIWLomkpmzKtdkA:-KdabjIWLomkpmzKtdkB:b-obhtgb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/takeoff_functors.h#L57)):*
> ```objc
>     }
>     // Transition to hovering state once reached high altitude
>     if (data.altitude > 1.0) {
> ```

Should be configurable. Add TODO

---

*[include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h, line 8 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdacKROVFp_zIN-ZKhp:-KdacKROVFp_zIN-ZKhq:b-5gs16) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h#L8)):*
> ```objc
> */
> enum class HardwareType{
>   Quadrotor, // Only quadrotor
> ```

Since we aren't only using quadrotors (i.e. we have an octocopter), I think we need a better word.  Maybe Drone? UAV?

---

*[include/aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdactdbdJgnX9i0u9-8:-KdactdbdJgnX9i0u9-9:brl0fns) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h#L21)):*
> ```objc
>       parsernode::Parser &drone_hardware,
>       Controller<EmptySensor, VelocityYaw, VelocityYaw> &controller)
>       : ControllerHardwareConnector(controller, HardwareType::Quadrotor),
> ```

Maybe we should have a ControllerDroneConnector that takes hardwaretype of Quadrotor and all of the connectors we have so far can just derive from that.  Reduces code duplication a little bit.

---

*[include/aerial_autonomy/logic_states/base_state.h, line 24 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaktOnKIyrRerv9V5v:-KdaktOnKIyrRerv9V5w:b-x8hzyj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/logic_states/base_state.h#L24)):*
> ```objc
> 
> template <class RobotSystemT, class LogicStateMachineT, class ActionFctr>
> class BaseState : public msmf::state<> {
> ```

Why doesn't it need a guard functor anymore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7)*

**Comment by garimellagowtham** [comment]
Review status: 15 of 25 files reviewed at latest revision, 13 unresolved discussions.

---

*[.gitignore, line 4 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaZ-RAluC4RqEPIya9:-KdaojzlTOB_k3wsMZ37:bhp7cy5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/.gitignore#L4)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

Removed in commit

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 46 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaZV00T7BMwb33DrFB:-KdaohJHldjW1WfiYxqU:b-xzztot) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/base_functors.h#L46)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Are these supposed to be TODOs?
</blockquote></details>

They are already done stuff. Just notes for me

---

*[include/aerial_autonomy/actions_guards/hovering_functors.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kda_Qc9HsX_Q_rORdFF:-KdaolinfQWpkvyj18v_:b-gt7fev) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/hovering_functors.h#L16)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Does it need to do anything like set a position controller to maintain current position?
</blockquote></details>

If we send nothing, the quadrotor holds position by default right?

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kda_Z96xGsbCONQxJoG:-KdapJvS9CK91bRwotH_:ba3dfob) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/land_functors.h#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Copy pasted comment
</blockquote></details>

Removed

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaamEiJFt3nOyH7eSq:-KdapLFDoFAODJXRsMsH:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L38)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

This should be set by some parameter.  Add a TODO.
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 41 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kdab50iDXDiaWPOQMPr:-KdapXMGkCQV02jf_MhN:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L41)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be ||
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 44 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kdab6FZimIBBl70bcpa:-KdapmQlTNq7egb2GFJM:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L44)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be false
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 64 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdabUXiBghetv2rtFDU:-KdapvVAZLsfq2FVmskq:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/position_control_functors.h#L64)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be defined in some parameters somehow.  Add a TODO.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/actions_guards/takeoff_functors.h, line 53 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdablMwKw26ky_JY3Zx:-Kdatp464cxxdF7yuf2G:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/takeoff_functors.h#L53)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be configurable.  Add TODO
</blockquote></details>

Done

---

*[include/aerial_autonomy/actions_guards/takeoff_functors.h, line 57 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdabjIWLomkpmzKtdkA:-KdatpknVDjEaCSJGjWe:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/takeoff_functors.h#L57)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be configurable. Add TODO
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h, line 8 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdacKROVFp_zIN-ZKhp:-KdasZRpC53qxs8K87zt:bg8216d) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h#L8)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Since we aren't only using quadrotors (i.e. we have an octocopter), I think we need a better word.  Maybe Drone? UAV?
</blockquote></details>

Will do it once everything is merged. Since there are bunch of places where HardwareType is used and its distributed across commits

---

*[include/aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdactdbdJgnX9i0u9-8:-KdasgMgkhtf-yRCKwF6:b92znzw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h#L21)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Maybe we should have a ControllerDroneConnector that takes hardwaretype of Quadrotor and all of the connectors we have so far can just derive from that.  Reduces code duplication a little bit.
</blockquote></details>

This is your code. I just added hardware type to base controller constructor. Sure, we can do something like that but the the code duplication is minimal I think.

---

*[include/aerial_autonomy/logic_states/base_state.h, line 24 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdaktOnKIyrRerv9V5v:-Kdat0aewLu0g2CgkZ3Q:b-5mwust) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/logic_states/base_state.h#L24)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why doesn't it need a guard functor anymore?
</blockquote></details>

Internal actions do not need guard functors. They check the state logic and trigger different actions. I do not think it's necessary for most cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7)*

**Comment by msheckells** [comment]
Review status: 15 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/hovering_functors.h, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-Kda_Qc9HsX_Q_rORdFF:-Kdau_FKYKAUyzuM3EOU:bvlpbk3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/actions_guards/hovering_functors.h#L16)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

If we send nothing, the quadrotor holds position by default right?
</blockquote></details>

Yes, sounds good

---

*[include/aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-KdactdbdJgnX9i0u9-8:-KdaulgH9c2PVoDAncPR:bstv6xk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/397df78b87ae12969460b12b908ec7c6942e837f/include/aerial_autonomy/controller_hardware_connectors/builtin_velocity_controller_drone_connector.h#L21)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This is your code. I just added hardware type to base controller constructor. Sure, we can do something like that but the the code duplication is minimal I think.
</blockquote></details>

It is my code, but you added the HardwareType stuff to the constructor.  It did not need a ControllerDroneConnector base class before when there was no difference between the proposed ControllerDroneConnector and a ControllerHardwareConnector.  

I agree that the code duplication is minimal.  We can just leave as is until we have a better reason to change it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7)*

**Comment by msheckells** [comment]
Since we are doing everything in a staging branch, we can delete this review right?

---

Review status: 15 of 25 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/7#-:-KdiTkD3LvBFta1Ptn-w:b1nsr5s)*

**Pull request closed without merging**
