### PR TITLE
Vel based relative pose controller

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/101)

### CODE REVIEW

**Comment by msheckells** [comment]
Don't review until other PR is merged!

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-:-Kt08p0iuqcyHuZ4xo_7:b6u6krc)*

**Comment by garimellagowtham** [comment]
Reviewed 14 of 37 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 36 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2C6tbNH8bhpjJf9Bw:-Kt2C6tbNH8bhpjJf9Bx:b-dysuiy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6f4a45fc75f695f1ff7e2d179175735ac24a7720/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L36)):*
> ```objc
> 
>   /**
>    * @brief Get the tracking vector of the tracker in the global
> ```

get tracking transform of object in global frame

also params doc should be changed

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 48 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2Du6-w1vZqtqWWLV2:-Kt2Du6-w1vZqtqWWLV3:b-u56kp2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6f4a45fc75f695f1ff7e2d179175735ac24a7720/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L48)):*
> ```objc
>    * @brief Extracts pose data from ROI
>    *
>    * @param sensor_data Position and yaw of object tracked by ROI
> ```

update doc 

---

*[include/aerial_autonomy/controllers/velocity_based_relative_pose_controller.h, line 38 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3KiWu7sAmJh68KOmU:-Kt3KiWu7sAmJh68KOmV:bluiof8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/include/aerial_autonomy/controllers/velocity_based_relative_pose_controller.h#L38)):*
> ```objc
>    * @param sensor_data Pose of controlled point and tracked
>    * pose
>    * @param goal Goal relative pose in tracked pose frame
> ```

Note that only the yaw of the resulting goal in the global frame is tracked since quadrotor cannot achieve arbitrary roll, pitch while hovering. Also, we can modify the goal to be positionyaw where the position is in tracked pose frame and yaw is the offset from object yaw in the global frame.

---

*[src/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.cpp, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2FLSgVBxbLxe_oL8r:-Kt2FLSgVBxbLxe_oL8s:b4s8qgf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6f4a45fc75f695f1ff7e2d179175735ac24a7720/src/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.cpp#L49)):*
> ```cpp
> 
> tf::Matrix3x3
> RelativePoseVisualServoingControllerDroneConnector::getBodyFrameRotation() {
> ```

This function can return a tf transform with zero translation. This will simplify the usage in above functions.

---

*[src/controllers/velocity_based_position_controller.cpp, line 35 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2m-HAdpsBv935zuD4:-Kt2m-HBsKhoQ3ImYXjp:b22g542) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/src/controllers/velocity_based_position_controller.cpp#L35)):*
> ```cpp
>       << position_diff.x << position_diff.y << position_diff.z
>       << position_diff.yaw << DataStream::endl;
>   std::cout << position_diff.x << " " << position_diff.y << " "
> ```

Remove cout

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 32 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3EBX0TKeaEDu9_l4z:-Kt3EBX0TKeaEDu9_l5-:b8fufsx) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/src/controllers/velocity_based_relative_pose_controller.cpp#L32)):*
> ```cpp
>       << current_pose.getOrigin().getX() << current_pose.getOrigin().getY()
>       << current_pose.getOrigin().getZ() << current_yaw << control.x
>       << control.y << control.z << control.yaw_rate << DataStream::endl;
> ```

Can you add this logging to position controller instead?

---

*[tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp, line 86 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3LgQrVbzKdZR6ovBn:-Kt3LgQrVbzKdZR6ovBo:b2kot7x) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp#L86)):*
> ```cpp
>   drone_hardware_.takeoff();
>   // Set goal
>   tf::Transform goal_relative_pose(tf::createQuaternionFromRPY(0, 0, 0.5),
> ```

Show that if you add roll, pitch to goal_relative_pose, only the resulting goal yaw in global frame is tracked.

---

*[tests/controllers/velocity_based_relative_pose_controller_tests.cpp, line 28 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3NG7uohJTWfqGUm8c:-Kt3NG7uohJTWfqGUm8d:b-oyzdch) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/tests/controllers/velocity_based_relative_pose_controller_tests.cpp#L28)):*
> ```cpp
> }
> 
> TEST_F(VelocityBasedRelativePoseControllerTests, ConvergedNoOffset) {
> ```

Add converged offset with non-zero roll, pitch of goal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by msheckells** [comment]
Review status: 7 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 36 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2C6tbNH8bhpjJf9Bw:-Kt7UGaOr1heIm0oLwf-:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6f4a45fc75f695f1ff7e2d179175735ac24a7720/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L36)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

get tracking transform of object in global frame

also params doc should be changed
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 48 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2Du6-w1vZqtqWWLV2:-Kt7UZA9EGakmvleiC8_:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6f4a45fc75f695f1ff7e2d179175735ac24a7720/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L48)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

update doc 
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/velocity_based_relative_pose_controller.h, line 38 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3KiWu7sAmJh68KOmU:-Kt7ZwOwRXmFKCYtz637:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/include/aerial_autonomy/controllers/velocity_based_relative_pose_controller.h#L38)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Note that only the yaw of the resulting goal in the global frame is tracked since quadrotor cannot achieve arbitrary roll, pitch while hovering. Also, we can modify the goal to be positionyaw where the position is in tracked pose frame and yaw is the offset from object yaw in the global frame.
</blockquote></details>

Done.

---

*[src/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.cpp, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2FLSgVBxbLxe_oL8r:-Kt7Zy9AlefvCVqdpM3E:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6f4a45fc75f695f1ff7e2d179175735ac24a7720/src/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.cpp#L49)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This function can return a tf transform with zero translation. This will simplify the usage in above functions.
</blockquote></details>

Done.

---

*[src/controllers/velocity_based_position_controller.cpp, line 35 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt2m-HAdpsBv935zuD4:-Kt7avxBq_qHgEJ_R4_C:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/src/controllers/velocity_based_position_controller.cpp#L35)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Remove cout
</blockquote></details>

Done.

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 32 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3EBX0TKeaEDu9_l4z:-Kt7b0O7P3v9BEowP7UB:b-c3vgrc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/src/controllers/velocity_based_relative_pose_controller.cpp#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can you add this logging to position controller instead?
</blockquote></details>

I can.  However, there is an issue I did not forsee with the controller logging... If we are using the same controller in different places, that controller will always log to the same file.  So, I logged the data to a different stream here to make sure we knew which data was coming from this controller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by garimellagowtham** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/common/conversions.h, line 29 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7uYCklvRSGCfbsRIA:-Kt7uYCklvRSGCfbsRIB:b-5i6aoz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/include/aerial_autonomy/common/conversions.h#L29)):*
> ```objc
>  * @param tf The equivalent tf::Transform
>  */
> void positionYawToTf(const PositionYaw &p, tf::Transform &tf);
> ```

Add tests

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 48 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7npM9tu7eaQ97SWkJ:-Kt7npMACKZdD0B4hZzi:b-cpir5y) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L48)):*
> ```objc
> protected:
>   /**
>    * @brief Extracts pose data from ROI
> ```

from tracker output

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7rgNqGN_gr5g60qJf:-Kt7rgNqGN_gr5g60qJg:bx0lwd6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/src/controllers/velocity_based_relative_pose_controller.cpp#L13)):*
> ```cpp
>   conversions::positionYawToTf(goal, goal_tf);
>   tf::Transform current_pose = std::get<0>(sensor_data);
>   tf::Transform desired_pose = std::get<1>(sensor_data) * goal_tf;
> ```

The conversion will be slightly more complicated than this, I think!  I did not think about this properly.

The goal_tf is the desired pose wrt to object frame. But if z axis of the object frame is not gravity aligned the yaw angle does not make sense. For example if z of the object is pointing outwards as in case of alvar marker, the yaw specified will be wrong and cannot be achieved. We might have to add an offset transformation that should be taken from proto that transforms object frame into gravity aligned frame before applying the goal transformation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/common/conversions.h, line 29 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7uYCklvRSGCfbsRIA:-Kt8d_NDPOXbu16O-0j6:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/include/aerial_autonomy/common/conversions.h#L29)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add tests
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 48 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7npM9tu7eaQ97SWkJ:-Kt8eVbj5PrilO-arLl4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L48)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

from tracker output
</blockquote></details>

Done.

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7rgNqGN_gr5g60qJf:-Kt8gjf4-ahQn_GtSEPY:b84z84s) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/src/controllers/velocity_based_relative_pose_controller.cpp#L13)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

The conversion will be slightly more complicated than this, I think!  I did not think about this properly.

The goal_tf is the desired pose wrt to object frame. But if z axis of the object frame is not gravity aligned the yaw angle does not make sense. For example if z of the object is pointing outwards as in case of alvar marker, the yaw specified will be wrong and cannot be achieved. We might have to add an offset transformation that should be taken from proto that transforms object frame into gravity aligned frame before applying the goal transformation.
</blockquote></details>

Great point.  The proto config transformation will work, but it is a little bit tedious to have to change that for each object when the object changes or when the object sits on a different side.   One idea is to just automatically use the gravity aligned frame of the object by setting its roll and pitch to zero in the rotation-compensated frame of the quadrotor.   The apply the goal transform to that frame as you mentioned

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7rgNqGN_gr5g60qJf:-KtC5PG0ZH2IP9cv2vbD:bp7vbga) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/src/controllers/velocity_based_relative_pose_controller.cpp#L13)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Great point.  The proto config transformation will work, but it is a little bit tedious to have to change that for each object when the object changes or when the object sits on a different side.   One idea is to just automatically use the gravity aligned frame of the object by setting its roll and pitch to zero in the rotation-compensated frame of the quadrotor.   The apply the goal transform to that frame as you mentioned
</blockquote></details>

sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7rgNqGN_gr5g60qJf:-KtCN8YX3vfP7Xi-6TWz:b8v1j5y) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/src/controllers/velocity_based_relative_pose_controller.cpp#L13)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

sounds good.
</blockquote></details>

I think we would still want the position to be with respect to the actual object frame though...but I'm not sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by msheckells** [comment]
Review status: 13 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp, line 86 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3LgQrVbzKdZR6ovBn:-KtCRCtK2sDBpH0cuqI0:b-idemhr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp#L86)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Show that if you add roll, pitch to goal_relative_pose, only the resulting goal yaw in global frame is tracked.
</blockquote></details>

It is no longer possible to specify a roll/pitch in the goal relative pose since the goal is now a PositionYaw

---

*[tests/controllers/velocity_based_relative_pose_controller_tests.cpp, line 28 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt3NG7uohJTWfqGUm8c:-KtD5mDEsz_ks95xzjnL:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52fecc97cd8edee5bf8ee310ef2c78cfa2338653/tests/controllers/velocity_based_relative_pose_controller_tests.cpp#L28)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add converged offset with non-zero roll, pitch of goal.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by msheckells** [comment]
Review status: 13 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controllers/velocity_based_relative_pose_controller.cpp, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-Kt7rgNqGN_gr5g60qJf:-KtD5qJhnF3cRODp3tkc:by0qn34) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1cf4c635cfc943f887c831537526d7323bf0031f/src/controllers/velocity_based_relative_pose_controller.cpp#L13)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I think we would still want the position to be with respect to the actual object frame though...but I'm not sure.
</blockquote></details>

Now using rotation-compensated tracked frame

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by garimellagowtham** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp, line 51 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-KtDFpckeQJG0mfFRnQE:-KtDFpckeQJG0mfFRnQF:b-wsry3c) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/50d3f551eab14acb28092cf7c17f3c914ad29fa6/tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp#L51)):*
> ```cpp
>     tracked_pose.getBasis().getRPY(roll, pitch, yaw);
>     tf::Transform rot_comp_tracked_pose = tracked_pose;
>     rot_comp_tracked_pose.getBasis().setRPY(0, 0, yaw);
> ```

gravity_aligned_tracked_pose is more meaningful maybe.

---

*[tests/controllers/velocity_based_relative_pose_controller_tests.cpp, line 49 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-KtDHSo-oEYgwPZVb7aa:-KtDHSo0Xn5fJb_YqhwI:b-e6o30n) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/50d3f551eab14acb28092cf7c17f3c914ad29fa6/tests/controllers/velocity_based_relative_pose_controller_tests.cpp#L49)):*
> ```cpp
>     ASSERT_NEAR(controls.y, position_diff.y() * position_gain_, 1e-6);
>     ASSERT_NEAR(controls.z, position_diff.z() * position_gain_, 1e-6);
>     ASSERT_NEAR(controls.yaw_rate, (goal_yaw - cur_yaw) * yaw_gain_, 1e-6);
> ```

Do you have to do angleWrap?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp, line 51 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-KtDFpckeQJG0mfFRnQE:-KtEtaQ2lypS96WD4kUs:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/50d3f551eab14acb28092cf7c17f3c914ad29fa6/tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp#L51)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

gravity_aligned_tracked_pose is more meaningful maybe.
</blockquote></details>

Done.

---

*[tests/controllers/velocity_based_relative_pose_controller_tests.cpp, line 49 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101#-KtDHSo-oEYgwPZVb7aa:-KtEtq2rFtz6LPuhyxA8:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/50d3f551eab14acb28092cf7c17f3c914ad29fa6/tests/controllers/velocity_based_relative_pose_controller_tests.cpp#L49)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Do you have to do angleWrap?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Comment by garimellagowtham** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/101)*

**Pull request merged**
