### PR TITLE
Add Sensor to UAV system

### PR DESCRIPTION
**Pull request by sohampatkar10**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/109)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/controllers/joystick_velocity_controller.h, line 92 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWukwlrs6coSLOekRq:-KtWukwlrs6coSLOekRr:blc7pcx) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/controllers/joystick_velocity_controller.h#L92)):*
> ```objc
>   * @ Config for rpyt velocity controller
>   */
>   RPYTBasedVelocityControllerConfig rpyt_velocity_controller_config_;
> ```

Do you need to store a copy of the config here? Can't JoystickVelocityControllerConfig contain a RPYTBasedVelocityControllerConfig which will get passed to the RPYTBasedVelocityController?

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 100 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWzcnADVxKCq19IuvF:-KtWzcnBReZlrfu-Pmp_:bcwobmp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/robot_systems/uav_system.h#L100)):*
> ```objc
>   */
>   UAVSystem(parsernode::Parser &drone_hardware, UAVSystemConfig config,
>             std::shared_ptr<Sensor<VelocityYaw>> velocity_sensor =
> ```

Let's make this a reference instead of a shared_ptr.  We aren't ever accounting for cases when its null and we don't expect it to be null, so let's avoid the possibility of passing null altogether

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 144 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWvnMAVVB303If6dIc:-KtWvnMBDaXE5aVM-KSS:b-65usin) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/robot_systems/uav_system.h#L144)):*
> ```objc
>   * @brief Get status of the sensor
>   */
>   SensorStatus getSensorStatus() { return velocity_sensor_->getSensorStatus(); }
> ```

Let's call this getVelocitySensorStatus

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 261 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWvsdS2LlfNvgqtDQi:-KtWvsdS2LlfNvgqtDQj:b-u720ou) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/robot_systems/uav_system.h#L261)):*
> ```objc
>   * extend for other controllers
>   */
>   void updateConfig(RPYTBasedVelocityControllerConfig &config) {
> ```

updateRPYTVelocityControllerConfig

---

*[include/aerial_autonomy/system_handlers/uav_system_handler.h, line 110 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWwN0DNglUnQ5C-z1E:-KtWwN0DNglUnQ5C-z1F:bh3j1yy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/system_handlers/uav_system_handler.h#L110)):*
> ```objc
>                                     ///< and associated connections.
>   AsyncTimer uav_controller_timer_; ///< Timer for running uav controller
>   bool use_dynamic_reconfigure_;    ///< flag to use dynamic reconfigure
> ```

Ideally, all of this reconfigure stuff will be in its own class and the robot system will have an instance of that class.  Add a TODO to fix it 

---

*[proto/uav_system_handler_config.proto, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWx2_j31ZTxWVGeGaQ:-KtWx2_j31ZTxWVGeGaR:b-hw2ja5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/proto/uav_system_handler_config.proto#L31)):*
> ```protobuf
>   * @brief type of velocity sensor 
>   */
>   optional string sensor_type = 5 [default = "Guidance"];
> ```

Can sensor_type be part of VelocitySensorConfig?

---

*[tests/robot_systems/uav_system_tests.cpp, line 187 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWzLfTujMTzI60zjpJ:-KtWzLfTujMTzI60zjpK:b-60bdsb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/tests/robot_systems/uav_system_tests.cpp#L187)):*
> ```cpp
> 
>   // run controller till it converges
>   while (uav_system.getActiveControllerStatus(HardwareType::UAV) ==
> ```

Use runUntilFalse with timeout

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Comment by sohampatkar10** [comment]
Review status: 8 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/controllers/joystick_velocity_controller.h, line 92 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWukwlrs6coSLOekRq:-KtXgTNslIbaYZzlm2Cj:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/controllers/joystick_velocity_controller.h#L92)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Do you need to store a copy of the config here? Can't JoystickVelocityControllerConfig contain a RPYTBasedVelocityControllerConfig which will get passed to the RPYTBasedVelocityController?
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 100 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWzcnADVxKCq19IuvF:-KtXgZv7hAv9LKg7fXYf:bj0v6bg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/robot_systems/uav_system.h#L100)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Let's make this a reference instead of a shared_ptr.  We aren't ever accounting for cases when its null and we don't expect it to be null, so let's avoid the possibility of passing null altogether
</blockquote></details>

I used a pointer so that a defualt value could be provided for that argument. Lot of stuff would break if we change the required arguments for uav system. 

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 144 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWvnMAVVB303If6dIc:-KtXgxP6Aq02HtaZClbl:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/robot_systems/uav_system.h#L144)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Let's call this getVelocitySensorStatus
</blockquote></details>

Done.

---

*[include/aerial_autonomy/system_handlers/uav_system_handler.h, line 110 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWwN0DNglUnQ5C-z1E:-KtXh3OL6KoYAsaBzll-:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/system_handlers/uav_system_handler.h#L110)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Ideally, all of this reconfigure stuff will be in its own class and the robot system will have an instance of that class.  Add a TODO to fix it 
</blockquote></details>

Done.

---

*[proto/uav_system_handler_config.proto, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWx2_j31ZTxWVGeGaQ:-KtXh4fBlrvdyijW3lBD:bo8n6dy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/proto/uav_system_handler_config.proto#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Can sensor_type be part of VelocitySensorConfig?
</blockquote></details>

VelocitySensorConfig is specific to the ros-based sensor.  

---

*[tests/robot_systems/uav_system_tests.cpp, line 187 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWzLfTujMTzI60zjpJ:-KtXhLcV2rEwpFBNbkJx:b-dicje2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/tests/robot_systems/uav_system_tests.cpp#L187)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Use runUntilFalse with timeout
</blockquote></details>

Takes too long to converge. Probably because of the 100 ms sleep. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Comment by sohampatkar10** [comment]
Review status: 7 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 261 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWvsdS2LlfNvgqtDQi:-KtXkZbwaZVKMZkMGgRl:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/include/aerial_autonomy/robot_systems/uav_system.h#L261)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

updateRPYTVelocityControllerConfig
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Comment by msheckells** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/robot_systems/uav_system_tests.cpp, line 187 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWzLfTujMTzI60zjpJ:-KtY-EGw9PSg91YF7amx:bav8esb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/tests/robot_systems/uav_system_tests.cpp#L187)):*
<details><summary><i>Previously, sohampatkar10 wrote…</i></summary><blockquote>

Takes too long to converge. Probably because of the 100 ms sleep. 
</blockquote></details>

There is an updated version of it now where you can set the sleep time as a parameter.  Just make the sleep time 0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Comment by sohampatkar10** [comment]
Review status: 14 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/robot_systems/uav_system_tests.cpp, line 187 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109#-KtWzLfTujMTzI60zjpJ:-KtY8ZyoVRTElPaL8c7T:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0cbd8aa47b57b0d1d0a6a7742f24f1c8aaedf441/tests/robot_systems/uav_system_tests.cpp#L187)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

There is an updated version of it now where you can set the sleep time as a parameter.  Just make the sleep time 0.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Comment by msheckells** [comment]
Reviewed 2 of 3 files at r3.
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Comment by msheckells** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/109)*

**Pull request merged**
