### PR TITLE
Create onboard node

### PR DESCRIPTION
**Pull request by msheckells**
Create an initial node that parses a config file and runs the basic state machine.  Also makes landing logic abort any running controller before landing to avoid position controller constantly running in the background while landed.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/26)

### CODE REVIEW

**Comment by msheckells** [comment]
See related PR in rqt_quadcopter_parsers for changes useful for testing/debugging

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26#-:-KeuRPZZ0C-htATk49Jk:bq5okm3)*

**Comment by garimellagowtham** [comment]
Its working great!

---

Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/aerial_autonomy_node.cpp, line 28 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26#-KevAxFYb1aWjZS61BQ3:-KevAxFYb1aWjZS61BQ4:b-gi39zr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a50d4644dc0e518d6a2cb2a1d099bd4195656fb6/src/aerial_autonomy_node.cpp#L28)):*
> ```cpp
>   if (!nh.getParam("onboard_system_config_filename",
>                    onboard_system_config_filename)) {
>     std::cout << "ROS param \"onboard_system_config_filename\" not found"
> ```

add todo for GLOG instead of couts, cerr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26#-:-KevOq6Ymu0E1xw9o5JE:bhxanog)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26)*

**Comment by msheckells** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/aerial_autonomy_node.cpp, line 28 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26#-KevAxFYb1aWjZS61BQ3:-KeviYKsJ8sIqXPYzj_i:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a50d4644dc0e518d6a2cb2a1d099bd4195656fb6/src/aerial_autonomy_node.cpp#L28)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

add todo for GLOG instead of couts, cerr
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/26)*

**Pull request merged**
