### PR TITLE
Change controller hardware connector to controller connector

### PR DESCRIPTION
**Pull request by garimellagowtham**
Add a dependent connector to controller connector. When a
controller connector becomes active, the dependent controller connector
also becomes active

TODO: Currently the connectors are passed around as raw pointers which is
not safe. Have to figure out a way to make it safe by using
unique pointers

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179)

### CODE REVIEW

**Comment by msheckells** [comment]
Tests for activating dependent controller?

---

Reviewed 101 of 138 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 56 at r2](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179#-LCZVY7c4eKI5JZocQUV:-LCZVY7d-tdHcBr0xiYm:b-cejjk6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ad3bc5b39c1d3821498e173632c8e6631d2b52b9/include/aerial_autonomy/robot_systems/base_robot_system.h#L56)):*
> ```objc
>       boost::mutex::scoped_lock lock(*thread_mutexes_[controller_group]);
>       active_controllers_.erase(controller_group);
>       active_controllers_.emplace(controller_group, controller_connector);
> ```

why not just do `active_controllers_[controller_group] = controller_connector`?

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 140 at r2](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179#-LCZX82wCfhoXS2N4cfv:-LCZX82wCfhoXS2N4cfw:b459ycp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ad3bc5b39c1d3821498e173632c8e6631d2b52b9/include/aerial_autonomy/robot_systems/base_robot_system.h#L140)):*
> ```objc
>     boost::mutex::scoped_lock lock(*thread_mutexes_[controller_group]);
>     active_controllers_.erase(controller_group);
>     active_controllers_.emplace(controller_group, nullptr);
> ```

is this more efficient or something?

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179#-:-LCZmeuw7OMUU6fZiTi-:bty78zx)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179)*

**Comment by garimellagowtham** [comment]
Review status: 63 of 66 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 56 at r2](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179#-LCZVY7c4eKI5JZocQUV:-LCdb_7G0D9ARF0p1Vg8:b-uw0ibs) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ad3bc5b39c1d3821498e173632c8e6631d2b52b9/include/aerial_autonomy/robot_systems/base_robot_system.h#L56)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

why not just do `active_controllers_[controller_group] = controller_connector`?
</blockquote></details>

Because of const pointer. Removed const pointer so now back to how it was.

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 140 at r2](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179#-LCZX82wCfhoXS2N4cfv:-LCdbc07AbRYLPJjCqKc:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ad3bc5b39c1d3821498e173632c8e6631d2b52b9/include/aerial_autonomy/robot_systems/base_robot_system.h#L140)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

is this more efficient or something?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179)*

**Comment by msheckells** [comment]
*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 76 at r4](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179#-LCdix-k7jzk3PM84oIR:-LCdix-k7jzk3PM84oIS:b-68kev3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b36d30617a790f800ab1a0c217cbc23795ad38b7/include/aerial_autonomy/robot_systems/base_robot_system.h#L76)):*
> ```objc
>     controller_connector->setGoal(goal);
>     activateControllerConnector(controller_connector);
>     runActiveController(controller_connector->getControllerGroup());
> ```

add initialize function to ControllerConnector interface

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/179)*

**Pull request merged**
