### PR TITLE
Added higher level controller

### PR DESCRIPTION
**Pull request by sohampatkar10**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/177)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/controllers/quad_higher_level_controller.cpp, line 22 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g3OKQDQTtFs-b9usm:-L9g3OKQDQTtFs-b9usn:b-9ggqt0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/src/controllers/quad_higher_level_controller.cpp#L22)):*
> ```cpp
> ControllerStatus QuadHigherLevelController::isConvergedImplementation(
>     std::tuple<QuadFlatOutput, std::vector<Obstacle>> sensor_data,
>     Trajectory<QuadFlatOutput> goal) {
> ```

Goal should be just a single QuadFlatOutput for higher level

---

*[src/controllers/quad_higher_level_controller.cpp, line 24 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g39lY4wrTB2DOBP9C:-L9g39lY4wrTB2DOBP9D:b87p896) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/src/controllers/quad_higher_level_controller.cpp#L24)):*
> ```cpp
>     Trajectory<QuadFlatOutput> goal) {
>   ControllerStatus result = ControllerStatus::Active;
>   QuadFlatOutput goal_state = goal.getAtTime(goal.horizon());
> ```

should be looking at the quad actual state vs goal state, not optimized trajectory final state vs goal state.

---

*[src/controllers/quad_higher_level_controller.cpp, line 27 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g4LCKCSBBNyOvckdK:-L9g4LCKCSBBNyOvckdL:bxeli6q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/src/controllers/quad_higher_level_controller.cpp#L27)):*
> ```cpp
>   QuadFlatOutput error = goal_state - final_state_;
>   double e = config_.tolerance();
>   if (abs(error.p.x) < e || abs(error.p.y) < e || abs(error.p.z) < e ||
> ```

these should be &&

---

*[tests/controllers/quad_higher_level_controller_tests.cpp, line 59 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g4Wo42O51tM87_90f:-L9g4Wo42O51tM87_90g:b-4ffeje) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/tests/controllers/quad_higher_level_controller_tests.cpp#L59)):*
> ```cpp
>   ASSERT_TRUE(result);
> 
>   ControllerStatus check = controller.isConverged(sensor_data);
> ```

Should not use isConverged to check optimization convergence.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177)*

**Comment by sohampatkar10** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/controllers/quad_higher_level_controller.cpp, line 22 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g3OKQDQTtFs-b9usm:-L9gRhnQ8_KrbOjZmhBy:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/src/controllers/quad_higher_level_controller.cpp#L22)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Goal should be just a single QuadFlatOutput for higher level
</blockquote></details>

Done.

---

*[src/controllers/quad_higher_level_controller.cpp, line 24 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g39lY4wrTB2DOBP9C:-L9gRiKl5wBRQWM9DQG0:be303de) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/src/controllers/quad_higher_level_controller.cpp#L24)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

should be looking at the quad actual state vs goal state, not optimized trajectory final state vs goal state.
</blockquote></details>

The quad isn't actually executing the trajectory so that won't be possible. The goal of the higher level controller is to just generate a trajectory whose final state is the goal state. 

---

*[src/controllers/quad_higher_level_controller.cpp, line 27 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g4LCKCSBBNyOvckdK:-L9gS4HrA9CXPv_NRY2y:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/src/controllers/quad_higher_level_controller.cpp#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

these should be &&
</blockquote></details>

Done.

---

*[tests/controllers/quad_higher_level_controller_tests.cpp, line 59 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9g4Wo42O51tM87_90f:-L9gS5Oh8lIONUAf8jGq:b-6adv2e) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf8554e9cbb59c1d4c609e6b7cfc43d1505340f4/tests/controllers/quad_higher_level_controller_tests.cpp#L59)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should not use isConverged to check optimization convergence.
</blockquote></details>

The run function internally checks for the convergence. This is just for the sake of completion.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177)*

**Comment by msheckells** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/controllers/quad_higher_level_controller.cpp, line 27 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9lLopx0BlwIMTqwqMk:-L9lLopx0BlwIMTqwqMl:b8qplmu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c6fed76532806f8c1144787dcb8c93b15edb8d0f/src/controllers/quad_higher_level_controller.cpp#L27)):*
> ```cpp
>     QuadFlatOutput goal) {
>   ControllerStatus result = ControllerStatus::Active;
>   QuadFlatOutput error = goal - final_state_;
> ```

change final_state_ to current quad state

---

*[tests/controllers/quad_higher_level_controller_tests.cpp, line 57 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9lM3SA7VTHBt2ybl_c:-L9lM3SA7VTHBt2ybl_d:b-lpd416) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c6fed76532806f8c1144787dcb8c93b15edb8d0f/tests/controllers/quad_higher_level_controller_tests.cpp#L57)):*
> ```cpp
>   ASSERT_TRUE(result);
> 
>   ControllerStatus check = controller.isConverged(sensor_data);
> ```

check after moving quad.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177)*

**Comment by sohampatkar10** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/controllers/quad_higher_level_controller.cpp, line 27 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9lLopx0BlwIMTqwqMk:-L9lXRtVDbxLAI4QkVEH:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c6fed76532806f8c1144787dcb8c93b15edb8d0f/src/controllers/quad_higher_level_controller.cpp#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

change final_state_ to current quad state
</blockquote></details>

Done.

---

*[tests/controllers/quad_higher_level_controller_tests.cpp, line 57 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177#-L9lM3SA7VTHBt2ybl_c:-L9lXTmu7hOgsnMwPs7w:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c6fed76532806f8c1144787dcb8c93b15edb8d0f/tests/controllers/quad_higher_level_controller_tests.cpp#L57)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

check after moving quad.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/177)*

**Pull request closed without merging**
