### PR TITLE
Add uav arm system handler

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/68)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
We need a launch file for running everything using Matrice/octocopter

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[proto/uav_system_handler_config.proto, line 28 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSWPzlWJzw1VgvivWZ:-KoSWPzlWJzw1VgvivW_:b5cyrh7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/proto/uav_system_handler_config.proto#L28)):*
> ```protobuf
>   optional CommonSystemHandlerConfig base_config = 4;
> 
>   oneof subclass {
> ```

Add comment

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSXbE3R-RH1yXr0Bh6:-KoSXbE3R-RH1yXr0Bh7:bpvm6cm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L49)):*
> ```cpp
>     status_subscriber_ = nh_receive_status_.subscribe(
>         "system_status", 1, &UAVArmSystemHandlerTests::statusCallback, this);
>     // uav_system_handler_->powerArm(true);
> ```

Remove commented code

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 53 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSXtRAbms82PHaOn3f:-KoSXtRAbms82PHaOn3g:b2jae9i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L53)):*
> ```cpp
>   }
> 
>   void publishEvent(std::string event) {
> ```

We should move these function to a common file. These are repeated across different uav system handler tests

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 63 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSY2-L8jfOKYcIDp2Q:-KoSY2-L8jfOKYcIDp2R:b-csqwn) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L63)):*
> ```cpp
>   }
> 
>   void publishPoseCommand(PositionYaw pose) {
> ```

This function too

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 76 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSYBgGK40RnK-R5LGs:-KoSYBgGK40RnK-R5LGt:b-csqwn) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L76)):*
> ```cpp
>   }
> 
>   bool isStatusConnected() { return status_subscriber_.getNumPublishers() > 0; }
> ```

This function too

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSYtwaL7O-SSSP3EP6:-KoSYtwaL7O-SSSP3EP7:b-w5dze3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L151)):*
> ```cpp
> }
> 
> /// \todo Matt Add visual servoing tests
> ```

We want to add pick place tests instead of visual servoing tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-:-KoSZ2NaKMqV3YWRBkKw:b-ulxedc)*

**Comment by msheckells** [comment]
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[proto/uav_system_handler_config.proto, line 28 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSWPzlWJzw1VgvivWZ:-KoUsNo6NSG7Pd9qrRM9:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/proto/uav_system_handler_config.proto#L28)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSXbE3R-RH1yXr0Bh6:-KoUsSz-B_SIyKXttRAE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L49)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Remove commented code
</blockquote></details>

Done.

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 53 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSXtRAbms82PHaOn3f:-KoUsVe80TGu8DIbFbaU:b-gq0xy4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L53)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We should move these function to a common file. These are repeated across different uav system handler tests
</blockquote></details>

Agreed. Will add todo

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 63 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSY2-L8jfOKYcIDp2Q:-KoUsYF2Tl3od45qy3cR:b-gq0xy4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L63)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This function too
</blockquote></details>

Agreed. Will add todo

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 76 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSYBgGK40RnK-R5LGs:-KoUsopaHyF-ZU44OM4p:b-gq0xy4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L76)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This function too
</blockquote></details>

Agreed. Will add todo

---

*[tests/system_handlers/uav_arm_system_handler_tests.cpp, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-KoSYtwaL7O-SSSP3EP6:-KoUstxALF3bForGW-kc:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/deebf9ab827b88cb3bca21bdec935dd6f5de1a5e/tests/system_handlers/uav_arm_system_handler_tests.cpp#L151)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We want to add pick place tests instead of visual servoing tests
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68)*

**Comment by garimellagowtham** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68#-:-KoUzFxsVKk_dXLZfdxD:bnfp4nl)*

**Comment by msheckells** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/68)*

**Pull request merged**
