### PR TITLE
Add rpyt position controller

### PR DESCRIPTION
**Pull request by msheckells**
Change controller timer durations to use std::chrono instead of double to avoid time unit bugs
Add RPYBasedPositionController

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/147)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 16 of 20 files at r1.
Review status: 16 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147#-L-DEayG0RVElAhSVurw:-L-DEayG0RVElAhSVurx:b-c24ztr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/226f8a68a6c7b4fdd82c2bab4b594722e7e136c0/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L151)):*
> ```objc
>   VelocityBasedPositionControllerConfig config_; ///< Controller configuration
>   PositionYaw cumulative_error_; ///< Error integrated over multiple runs
>   std::chrono::duration<double>
> ```

can make this const ref so that it cannot be changed by members.

---

*[src/controllers/rpyt_based_position_controller.cpp, line 22 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147#-L-DECQqIesWaMZPcUQH:-L-DECQr4yIrrHG4F_57:b-wt92pz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/226f8a68a6c7b4fdd82c2bab4b594722e7e136c0/src/controllers/rpyt_based_position_controller.cpp#L22)):*
> ```cpp
>   auto velocity = std::get<0>(sensor_data);
>   auto position = std::get<1>(sensor_data);
>   auto controller_status = rpyt_velocity_controller_.isConverged(
> ```

Create a separate controller status that is complete by default and add the sub-controllers to this parent controller status. This way we can see the status of the complete status, and the sub-controllers status.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 20 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/controllers/rpyt_based_velocity_controller.h, line 104 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147#-L-DFzAJ8d58eB8_3Qwl:-L-DFzAJ8d58eB8_3Qwm:b-apz622) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/226f8a68a6c7b4fdd82c2bab4b594722e7e136c0/include/aerial_autonomy/controllers/rpyt_based_velocity_controller.h#L104)):*
> ```objc
>       config_; ///< Controller configuration
>   VelocityYawRate cumulative_error;
>   std::chrono::duration<double> controller_timer_duration_;
> ```

Make const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/controllers/rpyt_based_velocity_controller.h, line 104 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147#-L-DFzAJ8d58eB8_3Qwl:-L-DJJMXSmYCJCZqvrZi:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/226f8a68a6c7b4fdd82c2bab4b594722e7e136c0/include/aerial_autonomy/controllers/rpyt_based_velocity_controller.h#L104)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Make const
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147#-L-DEayG0RVElAhSVurw:-L-DJMbkyf6ZbOO7bZL9:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/226f8a68a6c7b4fdd82c2bab4b594722e7e136c0/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L151)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

can make this const ref so that it cannot be changed by members.
</blockquote></details>

Done.

---

*[src/controllers/rpyt_based_position_controller.cpp, line 22 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147#-L-DECQqIesWaMZPcUQH:-L-DLIq5EP9mLNotwl-1:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/226f8a68a6c7b4fdd82c2bab4b594722e7e136c0/src/controllers/rpyt_based_position_controller.cpp#L22)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Create a separate controller status that is complete by default and add the sub-controllers to this parent controller status. This way we can see the status of the complete status, and the sub-controllers status.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147)*

**Comment by garimellagowtham** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/147)*

**Pull request merged**
