### PR TITLE
Add calib scripts

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/97)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[scripts/calib/arm_camera_calib.m, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspx38cQa5K-qngNc41:-Kspx38cQa5K-qngNc42:b-39ezbx) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/arm_camera_calib.m#L5)):*
> ```objc
> % parse marker data markers = load('marker_data.csv');
> marker_pos = [
>   (markers(
> ```

I think clang format destroyed your code

---

*[scripts/calib/arm_camera_calib.m, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspy5qXabToMo_lcqdn:-Kspy5qXabToMo_lcqdo:b47wg9j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/arm_camera_calib.m#L56)):*
> ```objc
> 
> % Nonlinear opt
> fun = @(x) marker_pos_hom*[eul2rotm([x(3),x(2),x(1)]), x(4:6)']' - fwd_kin_interp.Data; 
> ```

we should quaternions or Rodriguez expansion to avoid singularities

---

*[scripts/calib/arm_camera_calib.m, line 70 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspy4Z5_pc23qmwhqkV:-Kspy4Z5_pc23qmwhqkW:b-kjrh5a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/arm_camera_calib.m#L70)):*
> ```objc
> arm_quad = [[eul2rotm([pi, -pi/2, 0]), [.17; 0; -.109]];
>              [ 0, 0, 0, 1]];
>          
> ```

spaces

---

*[scripts/calib/mat2rpy.m, line 2 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-KspwroOSIqQvit9nwjc:-KspwroOSIqQvit9nwjd:b-ec9dyt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/mat2rpy.m#L2)):*
> ```objc
> function rpy = mat2rpy(mat) %
>                MAT2RPY converts Rotation matrix to euler zyx angles rpy : roll,
> ```

weird spacing

---

*[scripts/calib/mat2rpy.m, line 7 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspwuoha3DfEIls5qa4:-Kspwuoha3DfEIls5qa5:b-c31ttc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/mat2rpy.m#L7)):*
> ```objc
> % Check if cos(pitch) is close to zero : if abs(cos(rpy(2))) <
>     0.00001 disp('Pitch is very close to 90 degrees');
> rpy(1) = atan2(mat(1, 2), mat(1, 3));
> ```

No indentation?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[scripts/setup/hooks/pre-commit, line 3 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-KsuswsKLpOnjcCXiffd:-KsuswsKLpOnjcCXiffe:b-lny99m) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e7f5c1af8399a08de79c16e06268720ec515665e/scripts/setup/hooks/pre-commit#L3)):*
> ```
> #!/bin/sh
> # Check clang formatting
> git diff --cached --name-only --diff-filter=ACMRT | grep -E "\.([cmh]|cpp)$" | xargs -n1 clang-format -style=llvm -output-replacements-xml | grep "<replacement " >/dev/null
> ```

how about hpp,C, etc?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97)*

**Comment by msheckells** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[scripts/calib/arm_camera_calib.m, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspx38cQa5K-qngNc41:-Kt0Ac1ZnMQdaUaTEB4c:b-rkqm1s) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/arm_camera_calib.m#L5)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I think clang format destroyed your code
</blockquote></details>

Yes... fixed

---

*[scripts/calib/arm_camera_calib.m, line 70 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspy4Z5_pc23qmwhqkV:-Kt0Ajzhxz3nNt40vgQj:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/arm_camera_calib.m#L70)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

spaces
</blockquote></details>

Done.

---

*[scripts/calib/mat2rpy.m, line 2 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-KspwroOSIqQvit9nwjc:-Kt0Aky5Es76Q-YH0fTp:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/mat2rpy.m#L2)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

weird spacing
</blockquote></details>

Done.

---

*[scripts/calib/mat2rpy.m, line 7 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-Kspwuoha3DfEIls5qa4:-Kt0AlNOqN9ZBoh3AXAZ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b37c0a5f8687c9d6b5c3eab79ba468624765e83a/scripts/calib/mat2rpy.m#L7)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

No indentation?
</blockquote></details>

Done.

---

*[scripts/setup/hooks/pre-commit, line 3 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97#-KsuswsKLpOnjcCXiffd:-Kt0AqtPmSO8xl5g1CDQ:b-yth2a8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e7f5c1af8399a08de79c16e06268720ec515665e/scripts/setup/hooks/pre-commit#L3)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

how about hpp,C, etc?
</blockquote></details>

By convention, we don't have hpp or C extensions in our code base.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97)*

**Comment by garimellagowtham** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/97)*

**Pull request merged**
