### PR TITLE
Add reference trajectory interface

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/controllers/qrotor_backstepping_controller.h, line 75 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGwMGS73-cZeYi8B4s:-LDGwMGS73-cZeYi8B4t:bd3iik7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/controllers/qrotor_backstepping_controller.h#L75)):*
> ```objc
>   bool runImplementation(
>       std::pair<double, QrotorBacksteppingState> sensor_data,
>       std::shared_ptr<ReferenceTrajectory<ParticleState, Snap>> goal,
> ```

Is this a shared ptr to avoid copying the goal?

---

*[include/aerial_autonomy/types/discrete_reference_trajectory.h, line 15 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGw_Lc-HckTzIjA7Jc:-LDGw_Lc-HckTzIjA7Jd:bwu9o4m) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory.h#L15)):*
> ```objc
>     : public ReferenceTrajectory<StateT, ControlT> {
> public:
>   // TODO add constructor that verifies sizes of ts, states, controls are
> ```

Whats blocking this constructor TODO?

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_closest.h, line 20 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGy9Wp758ZAgOsxICx:-LDGy9WqBYYWa8U9dqF5:bhrp2ux) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_closest.h#L20)):*
> ```objc
> public:
>   /**
>   * @brief Gets the trajectory information at the specified time using linear
> ```

closest time

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_closest.h, line 30 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGyIcV0WEQ_ORxfPJi:-LDGyCKU7GLymNKJUJSs:bpb6wtp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_closest.h#L30)):*
> ```objc
>     }
>     auto closest_t = std::lower_bound(this->ts.begin(), this->ts.end(), t);
>     int closest_i = closest_t - this->ts.begin();
> ```

Maybe if we say the closest time less than equal to the specified value, then we will not need the logic below.

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h, line 32 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGytQu0oG4kNZTbgv5:-LDGytQu0oG4kNZTbgv6:bsy3opg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h#L32)):*
> ```objc
>     int i = closest_t - this->ts.begin();
> 
>     if (*closest_t == t) {
> ```

Is this comparision to speed up things? I think we can use the interpolation even when closest_t == t to keep the logic consistent as in easy toread

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h, line 37 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGz8r_Ck0mWgeJioGw:-LDGz8r_Ck0mWgeJioGx:b-axp2ok) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h#L37)):*
> ```objc
>     } else {
>       double weight =
>           (t - this->ts.at(i - 1)) / (this->ts.at(i) - this->ts.at(i - 1));
> ```

Check `this->ts.at(i) - this->ts.at(i-1) > epsilon`

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/controllers/qrotor_backstepping_controller.h, line 75 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGwMGS73-cZeYi8B4s:-LDIbwaMEoTZphbHR6D7:b-e9qnv6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/controllers/qrotor_backstepping_controller.h#L75)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Is this a shared ptr to avoid copying the goal?
</blockquote></details>

Its for polymorphism of ReferenceTrajectory

---

*[include/aerial_autonomy/types/discrete_reference_trajectory.h, line 15 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGw_Lc-HckTzIjA7Jc:-LDJECirCY-4DXeo8LTK:bn0hmn8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory.h#L15)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Whats blocking this constructor TODO?
</blockquote></details>

Nothing.  I was thinking ts, states, and controls would be set by the constructor where sizes could be verified.  I would make them private variables though to keep users from adding things to them without verifying sizes.  Is that ok?

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_closest.h, line 20 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGy9Wp758ZAgOsxICx:-LDJAQEIC-lY_wrl7V_0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_closest.h#L20)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

closest time
</blockquote></details>

Done.

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_closest.h, line 30 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGyIcV0WEQ_ORxfPJi:-LDJAR7xCWSGOsR-H5xk:bvorqao) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_closest.h#L30)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Maybe if we say the closest time less than equal to the specified value, then we will not need the logic below.
</blockquote></details>

Why not just get the closest one though?

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h, line 32 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGytQu0oG4kNZTbgv5:-LDJB-qn-t_7B2YTW81G:b-qt2i0y) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Is this comparision to speed up things? I think we can use the interpolation even when closest_t == t to keep the logic consistent as in easy toread
</blockquote></details>

Its for the case when you try to access the element at the very beginning of the trajectory, where an element at i-1 does not exist

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h, line 37 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGz8r_Ck0mWgeJioGw:-LDJEAYKEYw5Bdt5uieC:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h#L37)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Check `this->ts.at(i) - this->ts.at(i-1) > epsilon`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h, line 32 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGytQu0oG4kNZTbgv5:-LDck7aP15CSUCM8MqQD:bcl9k6o) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory_interpolate.h#L32)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Its for the case when you try to access the element at the very beginning of the trajectory, where an element at i-1 does not exist
</blockquote></details>

You can write the logic as `if (i == 0) {send the start state} else {compare}` This will make it more clearer than whats written

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/types/discrete_reference_trajectory.h, line 15 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-LDGw_Lc-HckTzIjA7Jc:-LDckfH-2Zg_CmWiiyFY:bf528s0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/39854fb0e65ceb36fcdce9e19d29b052dc636229/include/aerial_autonomy/types/discrete_reference_trajectory.h#L15)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Nothing.  I was thinking ts, states, and controls would be set by the constructor where sizes could be verified.  I would make them private variables though to keep users from adding things to them without verifying sizes.  Is that ok?
</blockquote></details>

Do you want to do that in a separate PR?

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186)*

**Comment by garimellagowtham** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/186#-:-LDmsE4aE6mBbAdnrTzH:bnfp4nl)*

**Pull request merged**
