### PR TITLE
Finish state machine gui connector

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/16)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 5 of 14 files at r1.
Review status: 5 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[CMakeLists.txt, line 229 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5HPWK7ftH1RLK9nSp:-Ke5HPWK7ftH1RLK9nSq:b-dy748q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/CMakeLists.txt#L229)):*
> ```CMake
> catkin_add_gtest(${PROJECT_NAME}-basic-state-machine-test tests/state_machines/basic_state_machine_tests.cpp)
> add_rostest_gtest(${PROJECT_NAME}-state-machine-gui-connector-event-test tests/state_machines/state_machine_gui_connector_event_tests.test tests/state_machines/state_machine_gui_connector_event_tests.cpp)
> add_dependencies(${PROJECT_NAME}-state-machine-gui-connector-event-test ${${PROJECT_NAME}_EXPORTED_TARGETS})
> ```

Also add pose_publish_node as dependency

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 60 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5IQu3cQIXNZk_yt7F:-Ke5IQu49oCg9Nj52Um1:b-88c88i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L60)):*
> ```Python
>             self._layout.addWidget(self.arm_textbox)
> 
>         # Create height slider
> ```

Need a way to reset slider height to the current quad height.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 70 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5IXJuROyXGHH6d962:-Ke5IXJuROyXGHH6d963:b-7ts4gk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L70)):*
> ```Python
>         self.height_slider.setValue(2)
>         self.height_slider.setTickPosition(QSlider.TicksBelow)
>         self.height_slider.setTickInterval(1)
> ```

Should this be configurable?
Same with max height, min height?

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5InVdUTrqfAc2iewl:-Ke5InVdUTrqfAc2iewm:bn7qcsb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L151)):*
> ```Python
>         """
>         pose.pose.position.z = self.height_slider.value()
>         self.event_trigger.triggerPoseCommand(pose)
> ```

Do we want a separate button for triggeringPoseCommand or just use rviz pose command directly?

---

*[tests/state_machines/state_machine_gui_connector_event_tests.cpp, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5J77U4H6svZiu71Tv:-Ke5J77VTb6xBQASNRyw:b-5aqsnd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/tests/state_machines/state_machine_gui_connector_event_tests.cpp#L31)):*
> ```cpp
> 
> TEST_F(StateMachineGUIConnectorTests, TriggerEvent) {
>   ros::Duration(0.5).sleep();
> ```

Same as below comment

---

*[tests/state_machines/state_machine_gui_connector_pose_tests.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5FtqGftU4Tzyn_jAj:-Ke5FtqHfocO6IyVu5Ja:bhmrycu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/tests/state_machines/state_machine_gui_connector_pose_tests.cpp#L32)):*
> ```cpp
> 
> TEST_F(StateMachineGUIConnectorTests, TriggerPose) {
>   ros::Duration(0.5).sleep();
> ```

Instead of sleep, you can wait until there is at least one publisher for the topic that is receiving the events. You can also add a timeout there to fail if no publisher found within that time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by msheckells** [comment]
Review status: 5 of 15 files reviewed at latest revision, 6 unresolved discussions.

---

*[CMakeLists.txt, line 229 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5HPWK7ftH1RLK9nSp:-Ke5SmZVeUzEOuqVgkMw:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/CMakeLists.txt#L229)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Also add pose_publish_node as dependency
</blockquote></details>

Done.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 60 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5IQu3cQIXNZk_yt7F:-Ke5LVHJZGv6RZIUmTSX:bw349ch) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L60)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Need a way to reset slider height to the current quad height.
</blockquote></details>

I'll add a TODO.  Instead of the quad status callback being a string, we could have it contain an actual object with pose info etc.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 70 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5IXJuROyXGHH6d962:-Ke5LgVS9V5LkZAEWRpK:bbkfnvp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L70)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Should this be configurable?
Same with max height, min height?
</blockquote></details>

Ideally yes.  We currently don't have a parameter file for the GUI.  I'll add a TODO

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5InVdUTrqfAc2iewl:-Ke5LrO8YMhGTClo5j4j:b-qyawdy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L151)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Do we want a separate button for triggeringPoseCommand or just use rviz pose command directly?
</blockquote></details>

We can do both, but the button would have to get x, y, yaw from somewhere.

---

*[tests/state_machines/state_machine_gui_connector_pose_tests.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5FtqGftU4Tzyn_jAj:-Ke5RyHukXc33mNGOgOe:b5dyzxh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/tests/state_machines/state_machine_gui_connector_pose_tests.cpp#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Instead of sleep, you can wait until there is at least one publisher for the topic that is receiving the events. You can also add a timeout there to fail if no publisher found within that time.
</blockquote></details>

As far as I can tell, I can't get that information from the NodeHandle.  I could check the subscriber owned by StateMachineGUIConnector to see if it has any publishers, but the subscriber is private.  Do you know of a different way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by garimellagowtham** [comment]
Reviewed 7 of 14 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5InVdUTrqfAc2iewl:-Ke6PD34xZWhvW6w_ZKJ:bu1jlo9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L151)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We can do both, but the button would have to get x, y, yaw from somewhere.
</blockquote></details>

the Posecommand callback will store the goal pose. Then the button will send the goal pose + height. This avoids accidental goal sending. The Posecommand callback can also publish a marker back to rviz to visualize where the goal is.

---

*[src/tests/pose_publish_node.cpp, line 5 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke6QqTJ1xkpCR4VDk7L:-Ke6QqTKPhMedFqDy3VZ:b-u59lyj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c07695522a096765a9142e4219ededefe0acb7b3/src/tests/pose_publish_node.cpp#L5)):*
> ```cpp
> #include <signal.h>
> 
> class PosePublisher {
> ```

It looks like pose_publish_node and event_publish_node are doing the same thing. Can we combine them and have a parameter to select which event to publish.

---

*[tests/state_machines/state_machine_gui_connector_pose_tests.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5FtqGftU4Tzyn_jAj:-Ke6RzUWDkOyD2v52VIk:b-bwu7pu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/tests/state_machines/state_machine_gui_connector_pose_tests.cpp#L32)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

As far as I can tell, I can't get that information from the NodeHandle.  I could check the subscriber owned by StateMachineGUIConnector to see if it has any publishers, but the subscriber is private.  Do you know of a different way?
</blockquote></details>

Sorry I was not clear. The idea would be to add a function to statemachineguiconnector such as `checkEventConnectivity' which checks if subscriber has atleast one publisher and returns true/false. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by msheckells** [comment]
Review status: 7 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/state_machines/state_machine_gui_connector_event_tests.cpp, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5J77U4H6svZiu71Tv:-Ke9u8y6RPC4DCf1Zv-J:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/tests/state_machines/state_machine_gui_connector_event_tests.cpp#L31)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Same as below comment
</blockquote></details>

Done.

---

*[tests/state_machines/state_machine_gui_connector_pose_tests.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5FtqGftU4Tzyn_jAj:-Ke9u7jqWkYvLw6WCRse:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/tests/state_machines/state_machine_gui_connector_pose_tests.cpp#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Sorry I was not clear. The idea would be to add a function to statemachineguiconnector such as `checkEventConnectivity' which checks if subscriber has atleast one publisher and returns true/false. 
</blockquote></details>

Done.

---

*[src/tests/pose_publish_node.cpp, line 5 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke6QqTJ1xkpCR4VDk7L:-KeA3lzh6b_K2CZ6YZbC:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c07695522a096765a9142e4219ededefe0acb7b3/src/tests/pose_publish_node.cpp#L5)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

It looks like pose_publish_node and event_publish_node are doing the same thing. Can we combine them and have a parameter to select which event to publish.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by msheckells** [comment]
Review status: 6 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 151 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-Ke5InVdUTrqfAc2iewl:-KeA4SyNgEuxgJAEbJBR:bevi9ms) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e6fb09fe915b58d21dbac59e9603fbcb3a1478d8/src/aerial_autonomy/aerial_autonomy_gui.py#L151)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

the Posecommand callback will store the goal pose. Then the button will send the goal pose + height. This avoids accidental goal sending. The Posecommand callback can also publish a marker back to rviz to visualize where the goal is.
</blockquote></details>

Done.  It's probably good to have a separate button for sending the command in the beginning for debugging/safety purposes.  If we decide to remove it, it should be easy.  I also added a display for viewing the pose command received by the GUI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by garimellagowtham** [comment]
After those minor fixes,  :lgtm: 

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 162 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-KeHELhqDf4d3BmFWaba:-KeHELhqDf4d3BmFWabb:bpf750z) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1be21c682efcf2e8f356fa6a0116213b6fce8f83/src/aerial_autonomy/aerial_autonomy_gui.py#L162)):*
> ```Python
>         """
>         self.pose_command = pose
>         self.pose_x.setText(str(self.pose_command.pose.position.x))
> ```

We can do two things here:
1. Round off the pose x and y to have same resolution as z
2. Round off the string  representation to maybe two digits. Otherwise, the display does not look good:


---

*[tests/state_machines/state_machine_gui_connector_event_tests.cpp, line 33 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-KeHI6Mr8h3xH45gOCWN:-KeHI6MsaSGXspMEGDtO:b-4hzwnz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1be21c682efcf2e8f356fa6a0116213b6fce8f83/tests/state_machines/state_machine_gui_connector_event_tests.cpp#L33)):*
> ```cpp
>   while (!state_machine_gui_connector.isEventManagerConnected()) {
>     ros::Duration(0.2)
>         .sleep(); // Rate must be slower than test node publish rate
> ```

Remove comment. 
You can also remove sleep line itself, since this is not performance oriented test.

---

*[tests/state_machines/state_machine_gui_connector_pose_tests.cpp, line 34 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-KeHIOFVrcE84neJL08s:-KeHIOFVrcE84neJL08t:b-6vumu5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1be21c682efcf2e8f356fa6a0116213b6fce8f83/tests/state_machines/state_machine_gui_connector_pose_tests.cpp#L34)):*
> ```cpp
>   while (!state_machine_gui_connector.isPoseCommandConnected()) {
>     ros::Duration(0.2)
>         .sleep(); // Rate must be slower than test node publish rate
> ```

Same as above comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-:-KeHImHai_IoEalDUN0T:b5av604)*

**Comment by msheckells** [comment]
Review status: 12 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/state_machines/state_machine_gui_connector_event_tests.cpp, line 33 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-KeHI6Mr8h3xH45gOCWN:-KeJxFNBhPDnfZAKoAFG:b-b22x6c) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1be21c682efcf2e8f356fa6a0116213b6fce8f83/tests/state_machines/state_machine_gui_connector_event_tests.cpp#L33)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Remove comment. 
You can also remove sleep line itself, since this is not performance oriented test.
</blockquote></details>

The sleep is actually necessary after the event manager is connected.  Just because it is connected does not mean it received a message.  The sleep ensures that a message is received before proceeding (and hence the comment about its rate).  

I moved the sleep and the spin outside of the loop since it only has to happen after the connection is made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by msheckells** [comment]
Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 162 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16#-KeHELhqDf4d3BmFWaba:-KeK-AnWiD7LsAJIhhNa:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/1be21c682efcf2e8f356fa6a0116213b6fce8f83/src/aerial_autonomy/aerial_autonomy_gui.py#L162)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We can do two things here:
1. Round off the pose x and y to have same resolution as z
2. Round off the string  representation to maybe two digits. Otherwise, the display does not look good:


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Comment by garimellagowtham** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/16)*

**Pull request merged**
