### PR TITLE
Create base states, ctrlrs, tests for them

### PR DESCRIPTION
**Pull request by garimellagowtham**
Create base state, controller, run functor. Added unit tests to ensure they can compile and run.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/1)

### CODE REVIEW

**Comment by msheckells** [comment]
Awesome!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h, line 2 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTP3TZfvm5kIVlkLY:-KcJTP3TZfvm5kIVlkLZ:b1l9gbk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h#L2)):*
> ```objc
> #ifndef BASE_CONTROL_HARDWARE_CONNECTOR_H
> #define BASE_CONTROL_HARDWARE_CONNECTOR_H
> ```

use #pragma once

---

*[include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h, line 29 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJSvBhAPfqD2Br1egh:-KcJSvBhAPfqD2Br1egi:b-u9p8mw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h#L29)):*
> ```objc
>     sendHardwareCommands(control);
>   }
>   // Can be made into a macro
> ```

remove comment

---

*[include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTRHXoJyQ3-cAxdVi:-KcJTRHXoJyQ3-cAxdVj:b-l6mwxj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h#L38)):*
> ```objc
>   Controller<SensorDataType, GoalType, ControlType> &ctrlr_;
> };
> #endif // BASE_CONTROL_HARDWARE_CONNECTOR_H
> ```

remove

---

*[include/aerial_autonomy/controllers/base_controller.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTSpRUDvS2iqzKYCH:-KcJTSpRUDvS2iqzKYCI:b-e70rpc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controllers/base_controller.h#L1)):*
> ```objc
> #ifndef BASE_CONTROLLER_H
> ```

pragma once

---

*[include/aerial_autonomy/controllers/base_controller.h, line 10 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTZdUctvuZb295avy:-KcJTZdUctvuZb295avz:b43wsjt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controllers/base_controller.h#L10)):*
> ```objc
>    * @brief Run the control loop and return control arguments
>    * @param sensor_data Data required for control loop. Can also be
>    * estimatordata
> ```

add space between estimator and data

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTmjPp6YoyNdyNri9:-KcJTmjPp6YoyNdyNriA:b-e70rpc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L1)):*
> ```objc
> #ifndef BASE_FUNCTORS_H
> ```

pragma once

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJULrWxETh_pIDl0aQ:-KcJULrWxETh_pIDl0aR:b8ondcc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L18)):*
> ```objc
> 
>   /**
>      * @brief operator () Internally calls guard function
> ```

calls the run function

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJUCf5Y__v0CaDaG_z:-KcJUCf5Y__v0CaDaGa-:b-xavd5r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L21)):*
> ```objc
>      * @param rs Provides sensor data and allows for controlling hardware
>      * @param lsm Backend of logic State Machine. can send events using this.
>      * @return output of guard function
> ```

there is no return though

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 42 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJUIig3LBzDmW8K10t:-KcJUIig3LBzDmW8K10u:bk65mjc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L42)):*
> ```objc
> 
>   /**
>    * @brief operator () Internally calls run function
> ```

calls the guard function, not run

---

*[tests/controller_hardware_connectors/control_hardware_tests.cpp, line 6 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJV7Ou8b5aHhJ-_pJU:-KcJV7Ov0CtKuCYanyA1:b1ad8b8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/tests/controller_hardware_connectors/control_hardware_tests.cpp#L6)):*
> ```cpp
> //// \brief Definitions
> ///  Define any necessary subclasses for tests here
> class SampleCtrlr : public Controller<int, int, int> {
> ```

We should try to write out the names of classes to keep it readable, i.e. SampleController instead of SampleCtrlr

---

*[tests/controller_hardware_connectors/control_hardware_tests.cpp, line 11 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJZBP9l8lQ_K2b-q2e:-KcJZBPDguDys8xT0Ah5:b-ja0ea7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/tests/controller_hardware_connectors/control_hardware_tests.cpp#L11)):*
> ```cpp
> };
> 
> class SampleHrdwrCntrlr : ControllerHardwareConnector<int, int, int> {
> ```

should write this out as SampleHardwareController

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-:-KcJZaTEpfDUbH0W1PQ1:bccpe83)*

**Comment by garimellagowtham** [comment]
Review status: 3 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h, line 2 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTP3TZfvm5kIVlkLY:-KcLPSGmeWWOdCR27F_x:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h#L2)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

use #pragma once
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h, line 29 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJSvBhAPfqD2Br1egh:-KcLPTFn1kyUb7i6xVm3:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h#L29)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

remove comment
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTRHXoJyQ3-cAxdVi:-KcLPTucMEDjURNSju59:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controller_hardware_connectors/base_control_hardware_connector.h#L38)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTSpRUDvS2iqzKYCH:-KcLPUJnwVlvtaqTg9c5:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controllers/base_controller.h#L1)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

pragma once
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 10 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTZdUctvuZb295avy:-KcLPUn3Dt4fS3hp8qKe:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/controllers/base_controller.h#L10)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

add space between estimator and data
</blockquote></details>

Done.

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJTmjPp6YoyNdyNri9:-KcLPWAIG6UHsg425xOI:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L1)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

pragma once
</blockquote></details>

Done.

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJULrWxETh_pIDl0aQ:-KcLPWmONwMGM-ukELl-:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L18)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

calls the run function
</blockquote></details>

Done.

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJUCf5Y__v0CaDaG_z:-KcLPXO8GpEsfOS_uNcF:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L21)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

there is no return though
</blockquote></details>

Done.

---

*[include/aerial_autonomy/logic_states/base_functors.h, line 42 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJUIig3LBzDmW8K10t:-KcLPXjTtk5GFoChiVuy:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/include/aerial_autonomy/logic_states/base_functors.h#L42)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

calls the guard function, not run
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/control_hardware_tests.cpp, line 6 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJV7Ou8b5aHhJ-_pJU:-KcLP_J0NGqm5PFwUa25:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/tests/controller_hardware_connectors/control_hardware_tests.cpp#L6)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We should try to write out the names of classes to keep it readable, i.e. SampleController instead of SampleCtrlr
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/control_hardware_tests.cpp, line 11 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-KcJZBP9l8lQ_K2b-q2e:-KcLPaVVCx4INRBidN_R:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a8c78c29e6554a24c813d3e0be57a9e82808e91f/tests/controller_hardware_connectors/control_hardware_tests.cpp#L11)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

should write this out as SampleHardwareController
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1)*

**Comment by marin-zoox** [comment]
Any chance we could use full words where possible, i.e. use Controller instead of Ctrlr; similarly for variables, i.e use controller instead of ctrlr

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-:-KcLUBHjCPNT6-5R2NGz:b-yb3cxo)*

**Comment by garimellagowtham** [comment]
Done

---

Review status: 2 of 8 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-:-KcLk86H81WKVTNDeYzN:bb6un1j)*

**Comment by garimellagowtham** [comment]
Do we care about test names being fully specified. For example I have a test called `aerial_autonomy-ctrlr-hrdwr-cnctr-test` but it is already pretty long.

---

Review status: 2 of 8 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-:-KcLq9HiDOz_XPZXnGCm:bqgnsc)*

**Comment by msheckells** [comment]
nah, that's fine.  I was more worried about code and class names that ourselves and others might be reading a lot.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/1#-:-KcOPf_v4VWjb8OhLCEW:b3odbik)*

**Pull request merged**
