### PR TITLE
Integrate relative pose controller

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/108)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 115 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtNboOi0pefxBw_oadp:-KtNboOi0pefxBw_oadq:btkip24) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L115)):*
> ```objc
> // VisualServoingTransitionGuardFunctior_
> template <class LogicStateMachineT>
> struct RelativePoseVisualServoingTransitionGuardFunctor_
> ```

can you subclass this from VisualServoingTransitionGuardFunctor and not implement anything?

---

*[proto/uav_arm_system_config.proto, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtOI560MJtqAMyrC4JT:-KtOI560MJtqAMyrC4JU:bbeppw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/proto/uav_arm_system_config.proto#L21)):*
> ```protobuf
>   * @brief Config for arm controller
>   */
>   optional PoseControllerConfig position_controller_config = 5;
> ```

why is this changed?

---

*[tests/actions_guards/visual_servoing_functor_tests.cpp, line 51 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtOEY1dsecolEP5JgCV:-KtOEY1eKAyHfEp7GNCQ:b6alz6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/tests/actions_guards/visual_servoing_functor_tests.cpp#L51)):*
> ```cpp
>     vs_position_tolerance->set_z(0.5);
> 
>     auto relative_pose_vs_position_tolerance =
> ```

This looks horrible. But that's because of the design of protobufs I guess?

---

*[tests/actions_guards/visual_servoing_functor_tests.cpp, line 125 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtOFClMzgdSV38M0raf:-KtOEnRXb48uxr9vxKmR:b-s7s28m) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/tests/actions_guards/visual_servoing_functor_tests.cpp#L125)):*
> ```cpp
> TEST_F(VisualServoingTests, InvalidTrackingRelativePoseGuardFunction) {
>   simple_tracker->setTrackingIsValid(false);
>   // Test action functors
> ```

Test Guard functors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108)*

**Comment by garimellagowtham** [comment]
I think we should add an object offset transform and a guard to ensure resulting transform is not wrong. It can refuse to track in that case.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-:-KtOzkHhJcr2gRQ2I4-t:b-5mct21)*

**Comment by msheckells** [comment]
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 115 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtNboOi0pefxBw_oadp:-KtPHHuNe5T4ttBU9Sys:bdokbzq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L115)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

can you subclass this from VisualServoingTransitionGuardFunctor and not implement anything?
</blockquote></details>

Not quite.  The VisualServoingTransitionGuardFunctor does some extra things, like starting the VisualServoingControllerDroneConnector.  I could do something like have a base class which does the guard check, then have VisualServoingTransitionGuardFunctor subclass from the base class and add additional functionality.  RelativePosVisualServoingTransitionGuard would simply be a typedef or subclass of the base without any overriding.

---

*[tests/actions_guards/visual_servoing_functor_tests.cpp, line 51 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtOEY1dsecolEP5JgCV:-KtPIQF68qvj1jMZ8x-a:b-jyov37) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/tests/actions_guards/visual_servoing_functor_tests.cpp#L51)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This looks horrible. But that's because of the design of protobufs I guess?
</blockquote></details>

Yup... not much we can do about it I think.

---

*[tests/actions_guards/visual_servoing_functor_tests.cpp, line 125 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtOFClMzgdSV38M0raf:-KtPIhQjrFb0vnlYjHjf:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/tests/actions_guards/visual_servoing_functor_tests.cpp#L125)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Test Guard functors.
</blockquote></details>

Done.

---

*[proto/uav_arm_system_config.proto, line 21 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtOI560MJtqAMyrC4JT:-KtPHwfHrOVd9VX1v9m8:brtab9w) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/proto/uav_arm_system_config.proto#L21)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

why is this changed?
</blockquote></details>

Was changed because of some copy/paste stuff that then got removed.  Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108)*

**Comment by msheckells** [comment]
Added object offset transform.  I'm not sure that the guard is necessary.  If we have a conservative max velocity and a safety pilot I would not be worried.

---

Review status: 9 of 32 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-:-KtQ3L-jwz0qEst7PqJs:b-flt35e)*

**Comment by garimellagowtham** [comment]
Is there a way to visualize the goal in rviz? Does controller connector have access to ros?

---

Reviewed 24 of 24 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 115 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtNboOi0pefxBw_oadp:-KtRTenYCklv02qkqYkE:bkxryd6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L115)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Not quite.  The VisualServoingTransitionGuardFunctor does some extra things, like starting the VisualServoingControllerDroneConnector.  I could do something like have a base class which does the guard check, then have VisualServoingTransitionGuardFunctor subclass from the base class and add additional functionality.  RelativePosVisualServoingTransitionGuard would simply be a typedef or subclass of the base without any overriding.
</blockquote></details>

We can have a initializeTrackingGuard functor. And then the visual transition Guard can use boost and for starting the controller and initializeTrackingGuard.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 40 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRKM3X1WGWJo7G_mtX:-KtRKM3Yl8ORzesrTw_n:bw22x6i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L40)):*
> ```objc
>         drone_hardware_(drone_hardware), tracker_(tracker),
>         camera_transform_(camera_transform),
>         tracking_offset_transform_(tracking_offset_transform) {}
> ```

this assumes the transform is same for all objects. I think thats ok for now. In future may not work.

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 53 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRKphiBDCH_6Wf18jH:-KtRKphiBDCH_6Wf18jI:b-jx8hze) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L53)):*
> ```
>     tracking_offset_transform: 0.0
>     tracking_offset_transform: 0.0
>     tracking_offset_transform: -1.5708
> ```

Have to test this transform in practice before merging.

---

*[tests/robot_systems/uav_arm_system_tests.cpp, line 23 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRPiXuZDEJRBvQHeol:-KtRPiXv-Hq5XwLgK8Uu:bg10g2q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/tests/robot_systems/uav_arm_system_tests.cpp#L23)):*
> ```cpp
>   }
>   for (int i = 0; i < 6; ++i) {
>     uav_vision_system_config->add_tracking_offset_transform(0.0);
> ```

can combine for loops

---

*[tests/state_machines/pick_place_state_machine_tests.cpp, line 40 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRRFhH5_bzGDN-WfZr:-KtRRFhIYQYA5CXXBGLz:brg5yv0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/tests/state_machines/pick_place_state_machine_tests.cpp#L40)):*
> ```cpp
>     }
>     for (int i = 0; i < 6; ++i) {
>       uav_vision_system_config->add_tracking_offset_transform(0.0);
> ```

Can we add non-zero offset for pick-place?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-:-KtRRjLwR6mQpY98df2R:b-i6wzrd)*

**Comment by msheckells** [comment]
Review status: 22 of 33 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 115 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtNboOi0pefxBw_oadp:-KtS9h4A5GTIFFyOtm9e:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6673dab723ec06dae8d2dab4436d20258bc3ad8e/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L115)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We can have a initializeTrackingGuard functor. And then the visual transition Guard can use boost and for starting the controller and initializeTrackingGuard.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 40 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRKM3X1WGWJo7G_mtX:-KtS10BpUAYJqdzb8T2v:bqog80t) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L40)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

this assumes the transform is same for all objects. I think thats ok for now. In future may not work.
</blockquote></details>

Agreed

---

*[tests/robot_systems/uav_arm_system_tests.cpp, line 23 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRPiXuZDEJRBvQHeol:-KtS4zbQNKVFuuR1mzET:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/tests/robot_systems/uav_arm_system_tests.cpp#L23)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

can combine for loops
</blockquote></details>

Done.

---

*[tests/state_machines/pick_place_state_machine_tests.cpp, line 40 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRRFhH5_bzGDN-WfZr:-KtS16DAINabPofE6OGn:b-wx8das) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/tests/state_machines/pick_place_state_machine_tests.cpp#L40)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can we add non-zero offset for pick-place?
</blockquote></details>

I tested non-zero offset in the controller connector tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108)*

**Comment by garimellagowtham** [comment]
Reviewed 10 of 10 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 40 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRKM3X1WGWJo7G_mtX:-KtSElBGWSlnDs56fQwM:b-byky6j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L40)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Agreed
</blockquote></details>

Add a Note. Forgot to mention that!

---

*[launch/matrice_pick_place_alvar.launch, line 43 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtSErDNUIuiwENf7skJ:-KtSErDO_jAJZF29jqM1:b-86vp9a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/495e02996a574213953c1649a5248c59d9121812/launch/matrice_pick_place_alvar.launch#L43)):*
> ```XML
>   </include>
>   <include file="$(find pointgrey_camera_driver)/launch/pointgrey_camera_single_indoors.launch"/>
>   <node pkg="tf" type="static_transform_publisher" name="camera_quad" args="0.18 0 -.08 1.5708 0 1.9199 /quad /pointgrey_camera 100"/>
> ```

Add comment on using config from protobuf or something

---

*[param/matrice_hil_pick_place_alvar_config.pbtxt, line 68 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtSFjmbnaFQu34Qd5cg:-KtSFjmbnaFQu34Qd5ch:batk63q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/495e02996a574213953c1649a5248c59d9121812/param/matrice_hil_pick_place_alvar_config.pbtxt#L68)):*
> ```
>       }
>     }
>     relative_pose_goals {
> ```

Should test before merging. Just a blocking comment!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108)*

**Comment by msheckells** [comment]
Review status: 29 of 35 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 40 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRKM3X1WGWJo7G_mtX:-KtSvsf_7xOx8tudyV4Y:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L40)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add a Note. Forgot to mention that!
</blockquote></details>

Done.

---

*[launch/matrice_pick_place_alvar.launch, line 43 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtSErDNUIuiwENf7skJ:-KtSwIXmXsoi4r01Tfqe:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/495e02996a574213953c1649a5248c59d9121812/launch/matrice_pick_place_alvar.launch#L43)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add comment on using config from protobuf or something
</blockquote></details>

Done.

---

*[param/matrice_hil_pick_place_alvar_config.pbtxt, line 68 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtSFjmbnaFQu34Qd5cg:-KtSwKAjyWf1CnzOyqby:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/495e02996a574213953c1649a5248c59d9121812/param/matrice_hil_pick_place_alvar_config.pbtxt#L68)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Should test before merging. Just a blocking comment!
</blockquote></details>

Done.

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 53 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108#-KtRKphiBDCH_6Wf18jH:-KtSwL16o2FcNpS-hAIt:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/27819c2a8cbfd9b7ba4454aa0cbaea9d5f381e88/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L53)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Have to test this transform in practice before merging.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108)*

**Comment by garimellagowtham** [comment]
Reviewed 6 of 6 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/108)*

**Pull request merged**
