### PR TITLE
Separate node namespace

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/74)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 20 of 20 files at r1.
Review status: 15 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/system_handlers/uav_arm_system_handler.h, line 96 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74#-Kqcj8G59L3P31NpsSoQ:-Kqcj8G664gF9TY4qqQY:b7d9qeu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cfb9346587a4efca5b916037dd50af704d4d8899/include/aerial_autonomy/system_handlers/uav_arm_system_handler.h#L96)):*
> ```objc
> 
> private:
>   ros::NodeHandle nh_uav_;
> ```

Add documentation

---

*[include/aerial_autonomy/system_handlers/uav_arm_system_handler.h, line 99 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74#-KqcjhZrG2X4dQSnIXFO:-KqcjhZsUeWaURtVGwj2:b-au8ob8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cfb9346587a4efca5b916037dd50af704d4d8899/include/aerial_autonomy/system_handlers/uav_arm_system_handler.h#L99)):*
> ```objc
>   ros::NodeHandle nh_arm_;
>   ros::NodeHandle nh_tracker_;
>   ros::NodeHandle nh_common_;
> ```

Push this into common handler class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 5 files at r2.
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74)*

**Comment by msheckells** [comment]
Review status: 15 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/system_handlers/uav_arm_system_handler.h, line 96 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74#-Kqcj8G59L3P31NpsSoQ:-KqcmZmNRuU05fm0n2yD:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cfb9346587a4efca5b916037dd50af704d4d8899/include/aerial_autonomy/system_handlers/uav_arm_system_handler.h#L96)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add documentation
</blockquote></details>

Done.

---

*[include/aerial_autonomy/system_handlers/uav_arm_system_handler.h, line 99 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74#-KqcjhZrG2X4dQSnIXFO:-Kqcm_cSkLenWZkJ3eU6:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cfb9346587a4efca5b916037dd50af704d4d8899/include/aerial_autonomy/system_handlers/uav_arm_system_handler.h#L99)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Push this into common handler class
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/74)*

**Pull request merged**
