### PR TITLE
Atomic Class

### PR DESCRIPTION
**Pull request by msheckells**
Add Atomic class and tests.  Replace mutex/variable pairs with Atomic.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/56)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Can you check if this is useful in this case: http://stackoverflow.com/questions/989795/example-for-boost-shared-mutex-multiple-reads-one-write

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/56#-:-Khxf7nRpmjMBwqEGZV5:blkgxpk)*

**Comment by msheckells** [comment]
Right now simultaneous reads are not possible.  Looks like I could use the shared_lock/unique_lock combo to do it.  Do we want to allow simultaneous reads?  I don't see an issue with allowing it.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/56#-:-KhxfmzoHVSxiC2OYRz3:beokwne)*

**Comment by garimellagowtham** [comment]
I was just wondering if this fits into our use case i.e are our members only occasionally written and read simultaneously from multiple threads? If so, we should use the shared mutex.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/56#-:-KhxgeAOAR6z7e4RxRbb:b-e405fc)*

**Comment by msheckells** [comment]
I don't think we get simultaneous reads that often.  It's mostly a write coming from the GUI that could happen when a read occurs in the control loop.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/56#-:-Khxk6LPHjrkc51gAfWl:b-jdr7he)*

**Comment by garimellagowtham** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/56)*

**Pull request merged**
