### PR TITLE
Add Alvar tracker

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/70)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 116 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK-aWu8QOXjpieAQuy:-KqK-aWu8QOXjpieAQuz:bu82poy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/include/aerial_autonomy/actions_guards/pick_place_functors.h#L116)):*
> ```objc
> */
> template <class LogicStateMachineT>
> struct PickTransitionGuardFunctor_
> ```

This should not be called PickTransitionGuard anymore! We can put this in arm functors and call this `ArmEnabledGuardFunctor`

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 46 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK274u6pJ3byZX7rCq:-KqK274vGnv6PJx4Y0Fi:b-3b2bos) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/include/aerial_autonomy/trackers/alvar_tracker.h#L46)):*
> ```objc
>   * @param marker_msg Marker message
>   */
>   void markerCallback(const ar_track_alvar::AlvarMarkers &marker_msg);
> ```

The namespace has to ar_track_alvar_msgs on my computer since the AlvarMarkers is defined as an ROS message in that package. This is also true in other places.

---

*[include/aerial_autonomy/trackers/simple_multi_tracker.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJmx6RzUw0hI-sJ6xp:-KqJmx6SKG8E5vNpMmYH:b31xeyf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/include/aerial_autonomy/trackers/simple_multi_tracker.h#L1)):*
> ```objc
> #pragma once
> ```

May be, we should call this test_multi_tracker

---

*[src/trackers/alvar_tracker.cpp, line 19 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJwSrAoGZCOErA5Za9:-KqJwSrAoGZCOErA5ZaA:bdox3re) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/alvar_tracker.cpp#L19)):*
> ```cpp
>   if (!valid)
>     VLOG(2) << "Alvar has not been updated for 0.5 seconds";
>   return valid;
> ```

Can also check if object_positions is not empty here!

---

*[src/trackers/alvar_tracker.cpp, line 28 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJp5YhplevBKJCvCaY:-KqJp5YhplevBKJCvCaZ:bwmhix1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/alvar_tracker.cpp#L28)):*
> ```cpp
>   for (unsigned int i = 0; i < marker_msg.markers.size(); i++) {
>     auto marker_pose = marker_msg.markers[i].pose.pose;
>     Position p(marker_pose.position.x, marker_pose.position.y,
> ```

In future, we may have to change this to pose. For example, octocopter with cyton arm will need object pose instead of just object position. I am not sure whats the best way to do this!

---

*[src/trackers/closest_tracking_strategy.cpp, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJs8Gh-AcgOYicE7Jw:-KqJs8Gh-AcgOYicE7Jx:bibebb8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/closest_tracking_strategy.cpp#L18)):*
> ```cpp
> 
> bool ClosestTrackingStrategy::getTrackingVector(
>     const std::vector<std::tuple<uint32_t, Position>> &tracking_vectors,
> ```

We should use `unordered_map` here http://en.cppreference.com/w/cpp/container/unordered_map

We do not have to iterate to find the position of the tracked object. 
If we are finding the closest object, we can still iterate with constant complexity similar to a vector. There is no drawback I think.

---

*[src/trackers/closest_tracking_strategy.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJsaA_IWrj9yCTAp8w:-KqJsaAaMuFos70QkZk0:bhv07gi) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/closest_tracking_strategy.cpp#L32)):*
> ```cpp
> 
>   // If was lost track of the target, strategy must be reinitialized
>   tracking_locked_ = false;
> ```

If we lost and regained tracking within 0.5 seconds, will tracking_locked be set to false?

---

*[src/trackers/multi_tracker.cpp, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJwbOW2z7ocsqnAG4_:-KqJwbOW2z7ocsqnAG4a:bn9uovx) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/multi_tracker.cpp#L17)):*
> ```cpp
>   }
>   std::vector<std::tuple<uint32_t, Position>> tracking_vectors;
>   if (!getTrackingVectors(tracking_vectors) || tracking_vectors.empty()) {
> ```

Can just use `trackingisValid` if we modify the function to check if the tracking vectors are empty or not!

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 86 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK1fsmacmqyI6SJ0am:-KqK1fsmacmqyI6SJ0an:bbmobh1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/tests/actions_guards/pick_place_functor_tests.cpp#L86)):*
> ```cpp
>   ASSERT_FALSE(uav_arm_system->isHomeLocationSpecified());
>   pick_place_transition_guard(NULL, *sample_logic_state_machine,
>                               dummy_start_state, dummy_target_state);
> ```

Check result of guard maybe?

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 130 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK1b_TdF8cbsQNjXKg:-KqK1b_TdF8cbsQNjXKh:bbmobh1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/tests/actions_guards/pick_place_functor_tests.cpp#L130)):*
> ```cpp
>   int dummy_start_state, dummy_target_state;
>   pick_place_transition_guard(NULL, *sample_logic_state_machine,
>                               dummy_start_state, dummy_target_state);
> ```

Check result of guard maybe?

---

*[tests/trackers/alvar_tracker_tests.cpp, line 69 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK2zCM3gWPL0Ot6jY7:-KqK2zCNqZ-u_4iwKryp:b18l8x0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/tests/trackers/alvar_tracker_tests.cpp#L69)):*
> ```cpp
>   ASSERT_NEAR(pos.y, 2, 1e-6);
>   ASSERT_NEAR(pos.z, 3, 1e-6);
> }
> ```

Need more tests like
1. Tracking vector published is empty after publishing a non-zero sized tracking vector
2. What happens to tracking_lock if we lost tracking and regained tracking within configured ROI time?
3. What happens if two tracking vectors have the same id? This should not happen ideally!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70)*

**Comment by msheckells** [comment]
Review status: 5 of 29 files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 116 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK-aWu8QOXjpieAQuy:-KqTrR1YaM1eGfajkdkv:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/include/aerial_autonomy/actions_guards/pick_place_functors.h#L116)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This should not be called PickTransitionGuard anymore! We can put this in arm functors and call this `ArmEnabledGuardFunctor`
</blockquote></details>

Done.

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 46 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK274u6pJ3byZX7rCq:-KqTraKYrkCP6vaQ3ngx:b-3nqg9i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/include/aerial_autonomy/trackers/alvar_tracker.h#L46)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

The namespace has to ar_track_alvar_msgs on my computer since the AlvarMarkers is defined as an ROS message in that package. This is also true in other places.
</blockquote></details>

Changed to use ar_track_alvar_msgs

---

*[include/aerial_autonomy/trackers/simple_multi_tracker.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJmx6RzUw0hI-sJ6xp:-KqTs9kwt-mCT6RafePO:b-1lgn4i) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/include/aerial_autonomy/trackers/simple_multi_tracker.h#L1)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

May be, we should call this test_multi_tracker
</blockquote></details>

I was just going off the convention we used before, i.e. SimpleTracker for testing BaseTracker.

---

*[src/trackers/alvar_tracker.cpp, line 19 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJwSrAoGZCOErA5Za9:-KqTsi-aPD7CC_YS-XQW:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/alvar_tracker.cpp#L19)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can also check if object_positions is not empty here!
</blockquote></details>

Done.

---

*[src/trackers/alvar_tracker.cpp, line 28 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJp5YhplevBKJCvCaY:-KqTskVOyhTLeOHmoKtv:b-vwux0u) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/alvar_tracker.cpp#L28)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

In future, we may have to change this to pose. For example, octocopter with cyton arm will need object pose instead of just object position. I am not sure whats the best way to do this!
</blockquote></details>

I agree. I had the same thought.  Not sure of the best way to do it either just yet, but we can discuss.

---

*[src/trackers/closest_tracking_strategy.cpp, line 18 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJs8Gh-AcgOYicE7Jw:-KqUSxkDTw55zYd1tIo9:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/closest_tracking_strategy.cpp#L18)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We should use `unordered_map` here http://en.cppreference.com/w/cpp/container/unordered_map

We do not have to iterate to find the position of the tracked object. 
If we are finding the closest object, we can still iterate with constant complexity similar to a vector. There is no drawback I think.
</blockquote></details>

Done.

---

*[src/trackers/closest_tracking_strategy.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJsaA_IWrj9yCTAp8w:-KqUT-DoJ94vBEattOgo:b-6q8zx2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/closest_tracking_strategy.cpp#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

If we lost and regained tracking within 0.5 seconds, will tracking_locked be set to false?
</blockquote></details>

No, we can implement this in a future TrackingStrategy

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 86 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK1fsmacmqyI6SJ0am:-KqTtM4UUOc_9oTCa0Ap:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/tests/actions_guards/pick_place_functor_tests.cpp#L86)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Check result of guard maybe?
</blockquote></details>

Done.

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 130 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK1b_TdF8cbsQNjXKg:-KqTtPnR1MsaD2UORBct:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/tests/actions_guards/pick_place_functor_tests.cpp#L130)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Check result of guard maybe?
</blockquote></details>

Done.

---

*[tests/trackers/alvar_tracker_tests.cpp, line 69 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqK2zCM3gWPL0Ot6jY7:-KqTyW04aPwfVlPpwzfN:b-zi1366) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/tests/trackers/alvar_tracker_tests.cpp#L69)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Need more tests like
1. Tracking vector published is empty after publishing a non-zero sized tracking vector
2. What happens to tracking_lock if we lost tracking and regained tracking within configured ROI time?
3. What happens if two tracking vectors have the same id? This should not happen ideally!
</blockquote></details>

1. Done
2. Tracking will be lost and getTrackingVector will return false.  A future TrackingStrategy can deal with this case
3. Using an unordered_map solves this issue on our end.  Idk if Alvar will give a message with multiples of a single ID

---

*[src/trackers/multi_tracker.cpp, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqJwbOW2z7ocsqnAG4_:-KqTt4RvgFKAOJN3C3A0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bae7eb1f0ab43fd51b57f8c7cae41200b0be1b07/src/trackers/multi_tracker.cpp#L17)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can just use `trackingisValid` if we modify the function to check if the tracking vectors are empty or not!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70)*

**Comment by garimellagowtham** [comment]
Reviewed 25 of 26 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/trackers/base_tracker.h, line 34 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUaXNG7oA_0awChkT9:-KqUaXNG7oA_0awChkTA:b-z337ch) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/include/aerial_autonomy/trackers/base_tracker.h#L34)):*
> ```objc
>    * @return True if successful, false otherwise
>    */
>   virtual bool getTrackingVector(std::tuple<uint32_t, Position> &pos);
> ```

Why do we need this version where we return the id along with the position. Maybe useful for future?

---

*[src/trackers/roi_to_position_converter.cpp, line 80 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUd4N_YmsFf9rIjYur:-KqUd4NaXCxhds8cBSwu:bdk7ku9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/src/trackers/roi_to_position_converter.cpp#L80)):*
> ```cpp
> bool RoiToPositionConverter::getTrackingVectors(
>     std::unordered_map<uint32_t, Position> &pos) {
>   pos.clear();
> ```

Why is this needed?

---

*[src/trackers/simple_tracker.cpp, line 14 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUdD0UR0iSx9Lv-u65:-KqUdD0UR0iSx9Lv-u66:b-b7cxh5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/src/trackers/simple_tracker.cpp#L14)):*
> ```cpp
> bool SimpleTracker::getTrackingVectors(
>     std::unordered_map<uint32_t, Position> &p) {
>   p.clear();
> ```

Why do we need to clear?

---

*[tests/system_handlers/uav_system_handler_tests.cpp, line 54 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUgs6BMojPrCui3fqk:-KqUgs6BMojPrCui3fql:b-hor2ic) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/tests/system_handlers/uav_system_handler_tests.cpp#L54)):*
> ```cpp
>     std::this_thread::sleep_for(std::chrono::milliseconds(50));
>     ros::spinOnce();
>     std::this_thread::sleep_for(std::chrono::milliseconds(50));
> ```

Will fix this to wait until ROS messages are received; I think!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/trackers/base_tracker.h, line 34 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUaXNG7oA_0awChkT9:-KqUhB8ibrD_xld0S72P:bkfncok) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/include/aerial_autonomy/trackers/base_tracker.h#L34)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why do we need this version where we return the id along with the position. Maybe useful for future?
</blockquote></details>

Yes, I figured the state machine might use it for something

---

*[src/trackers/roi_to_position_converter.cpp, line 80 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUd4N_YmsFf9rIjYur:-KqUhHtDJTVh6d55xL46:b2pm7bk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/src/trackers/roi_to_position_converter.cpp#L80)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why is this needed?
</blockquote></details>

In case the caller provides a map that is not empty.

---

*[src/trackers/simple_tracker.cpp, line 14 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUdD0UR0iSx9Lv-u65:-KqUhO79XORNNzROjDY6:b-ya5w2q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/src/trackers/simple_tracker.cpp#L14)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why do we need to clear?
</blockquote></details>

In case the caller provides a map that is not empty

---

*[tests/system_handlers/uav_system_handler_tests.cpp, line 54 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70#-KqUgs6BMojPrCui3fqk:-KqUhSZXoWTz9SYcmfLE:b-hfghm4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/35077fb2c85cae196c5e36ecd8d04678394ab845/tests/system_handlers/uav_system_handler_tests.cpp#L54)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Will fix this to wait until ROS messages are received; I think!
</blockquote></details>

Sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70)*

**Comment by msheckells** [comment]
Reviewed 5 of 24 files at r1, 25 of 26 files at r2.
Review status: 27 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/70)*

**Pull request merged**
