### PR TITLE
Updates to show hardware goal command in status

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/57)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 145 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/57#-Khz5ECNIaqX4Javc_XN:-Khz5ECNIaqX4Javc_XO:b-irnzad) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d16f2c12f16b86c948a6e9f5331e2b8e0b2214ed/include/aerial_autonomy/robot_systems/uav_system.h#L145)):*
> ```objc
>             "Magx: %2.2f\tMagy %2.2f\tMagz %2.2f\naccx: %2.2f\taccy "
>             "%2.2f\taccz %2.2f\nvelx: %2.2f\tvely %2.2f\tvelz %2.2f\n"
>             "Goalvx: %2.2f\tGoalvy: %2.2f\tGoalvz: %2.2f\tGoalvyaw: %2.2f\n"
> ```

We will also need goal yaw/yaw rate somehow right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/57)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/robot_systems/uav_system.h, line 145 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/57#-Khz5ECNIaqX4Javc_XN:-Ki0OkrPc2CmV55R7oya:bq40s71) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/da7a45f66617ad4d1d4f687cbf9cbba168c99790/include/aerial_autonomy/robot_systems/uav_system.h#L145)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We will also need goal yaw/yaw rate somehow right?
</blockquote></details>

Yeah... I guess I can add another field for that in quaddata

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/57)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/57)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/57)*

**Pull request merged**
