### PR TITLE
Host doxygen documentation

### PR DESCRIPTION
**Pull request by garimellagowtham**
Created gh-pages.
Added link to doxygen documentation from README. 

Added applydocs script which does the following:
1. Generate docs
2. Add html, xml files to gh-pages
3. Check if any changes to commit
4. If changes exist, commit using timestamp, and push to the branch
5. revert to the current branch

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/34)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[custom_footer.html, line 12 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34#-KfCgHo93HW0D6ONOmwI:-KfCgHoAicE_5Pjt2g9u:bgql2v0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0d6336cdc37c90172cb0daa8169ce64d90b9c580/custom_footer.html#L12)):*
> ```HTML
>   </ul>
> </div>
> 
> ```

Does this have to be in the root folder? It would be better if we could stick it in a its own folder or something.  We could also put the markdown_scripts file in the same folder.  Maybe we could put them in docs as long as they won't get deleted or something when generating docs

---

*[markdown_scripts/background.md, line 60 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34#-KfCiSgf_bbPQ8OY6Mtm:-KfCiSgf_bbPQ8OY6Mtn:b-kekogo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0d6336cdc37c90172cb0daa8169ce64d90b9c580/markdown_scripts/background.md#L60)):*
> ```Markdown
> 
> ##  Event Generation
> The events that trigger state machine transitions are created using event files in the `events` folder. The event header files are generated using CMakeLists similar to ros messages. The sysntax for the event files is as follows:
> ```

syntax

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34)*

**Comment by garimellagowtham** [comment]
Review status: 2 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[doxygen_files/custom_footer.html, line 12 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34#-KfCgHo93HW0D6ONOmwI:-KfCnNr6iynoIti0_vWM:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0d6336cdc37c90172cb0daa8169ce64d90b9c580/doxygen_files/custom_footer.html#L12)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Does this have to be in the root folder? It would be better if we could stick it in a its own folder or something.  We could also put the markdown_scripts file in the same folder.  Maybe we could put them in docs as long as they won't get deleted or something when generating docs
</blockquote></details>

Done.

---

*[markdown_scripts/background.md, line 60 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34#-KfCiSgf_bbPQ8OY6Mtm:-KfCnOkXzjL8-lZG1t0y:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0d6336cdc37c90172cb0daa8169ce64d90b9c580/markdown_scripts/background.md#L60)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

syntax
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34)*

**Comment by msheckells** [comment]
Reviewed 7 of 8 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34)*

**Comment by msheckells** [comment]
Reviewed 1 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/34)*

**Pull request merged**
