### PR TITLE
Remove velocity estimation from tracking vector estimator

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/164)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r1.
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/164)*

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/estimators/tracking_vector_estimator.cpp, line 70 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/164#-L-mrQO_BlIfQGByA_wu:-L-mrQOaqGx0z5B7kyL0:bp4q7j6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b65fdef997462cc802481b31be12891e9c96918c/src/estimators/tracking_vector_estimator.cpp#L70)):*
> ```cpp
>   double dt = std::chrono::duration<double>(
>                   std::chrono::high_resolution_clock::now() - marker_time_stamp)
>                   .count();
> ```

assert this is positive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/164)*

**Comment by garimellagowtham** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/estimators/tracking_vector_estimator.cpp, line 70 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/164#-L-mrQO_BlIfQGByA_wu:-L-n1wh7-f8tzbUJsUmw:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b65fdef997462cc802481b31be12891e9c96918c/src/estimators/tracking_vector_estimator.cpp#L70)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

assert this is positive
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/164)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/164)*

**Pull request merged**
