### PR TITLE
Add sinusoid controller to move arm for system ID

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/173)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 45 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9R0QPY7nnhI7oFmFhj:-L9R0QPY7nnhI7oFmFhk:bvngeu3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/8f38be1bb5e7a8f86f8047d9221ff180baedc5cf/include/aerial_autonomy/controllers/arm_sine_controller.h#L45)):*
> ```objc
> protected:
>   /**
>    * @brief Run the control loop.  Converts Joystick commands to RPYT.
> ```

incorrect docs

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/controllers/arm_sine_controller.cpp, line 15 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9R42W81GDLOO9-xqUW:-L9R42W81GDLOO9-xqUX:b-owbnzs) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/8f38be1bb5e7a8f86f8047d9221ff180baedc5cf/src/controllers/arm_sine_controller.cpp#L15)):*
> ```cpp
> }
> 
> void ArmSineController::setZeroTime() {
> ```

Can't you just override setGoal to set the time to zero?  Do you need to set the time to zero any other time besides when you turn on the controller?  Then you wouldn't need to add all that junk to robot system.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by msheckells** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 46 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9REkvp2j8g2VU99r-N:-L9REkvp2j8g2VU99r-O:bps1s89) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/df96b6edc479ef24946eead13fe6ca434c0e159f/include/aerial_autonomy/controllers/arm_sine_controller.h#L46)):*
> ```objc
>   /**
>    * @brief Move arm in sinusoid manner
>    * @param sensor_data Joystick commands to be converted into RPYT.
> ```

here too

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 48 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9REjx_7bobsBAuYDsQ:-L9REjx_7bobsBAuYDsR:bps1s89) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/df96b6edc479ef24946eead13fe6ca434c0e159f/include/aerial_autonomy/controllers/arm_sine_controller.h#L48)):*
> ```objc
>    * @param sensor_data Joystick commands to be converted into RPYT.
>    * @param goal Goal is not used here
>    * @param control RPYT to send to hardware
> ```

here too

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by garimellagowtham** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 45 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9R0QPY7nnhI7oFmFhj:-L9RCee_8Dpveeocwh4P:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/8f38be1bb5e7a8f86f8047d9221ff180baedc5cf/include/aerial_autonomy/controllers/arm_sine_controller.h#L45)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

incorrect docs
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 46 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9REkvp2j8g2VU99r-N:-L9RIBG74F9iov1u8gRX:bss4a2b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/df96b6edc479ef24946eead13fe6ca434c0e159f/include/aerial_autonomy/controllers/arm_sine_controller.h#L46)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Removed.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 48 at r2](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9REjx_7bobsBAuYDsQ:-L9RIC9u1xMJ-DaW8aN1:bss4a2b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/df96b6edc479ef24946eead13fe6ca434c0e159f/include/aerial_autonomy/controllers/arm_sine_controller.h#L48)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Removed.

---

*[src/controllers/arm_sine_controller.cpp, line 15 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9R42W81GDLOO9-xqUW:-L9RCnMN-hQo7qh1rFms:b-iv6n8b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/8f38be1bb5e7a8f86f8047d9221ff180baedc5cf/src/controllers/arm_sine_controller.cpp#L15)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Can't you just override setGoal to set the time to zero?  Do you need to set the time to zero any other time besides when you turn on the controller?  Then you wouldn't need to add all that junk to robot system.
</blockquote></details>

We can still keep the function. I updated the connector to set zero time during set goal function.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by msheckells** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 46 at r3](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9RKLDC3z4wJuMpzQg9:-L9RKLDC3z4wJuMpzQgA:b2ni2nk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a6aea96e53bb4370a4161d60801a52d5646e7023/include/aerial_autonomy/controllers/arm_sine_controller.h#L46)):*
> ```objc
>   /**
>    * @brief Move arm in sinusoid manner
>    * @param control RPYT to send to hardware
> ```

fix

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by msheckells** [comment]
Reviewed 2 of 3 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by garimellagowtham** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/controllers/arm_sine_controller.h, line 46 at r3](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173#-L9RKLDC3z4wJuMpzQg9:-L9RL-rZDoOaZvnsv7dc:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a6aea96e53bb4370a4161d60801a52d5646e7023/include/aerial_autonomy/controllers/arm_sine_controller.h#L46)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

fix
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/173)*

**Pull request merged**
