### PR TITLE
Test coverage branch

### PR DESCRIPTION
**Pull request by garimellagowtham**
Add test coverage tests to pre-push
Make sure clang-fix-all-code branch is merged first

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/20)

### CODE REVIEW

**Comment by msheckells** [comment]
I think this needs to merge master like the other PR

---

Review status: 0 of 34 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitignore, line 8 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZDKuGGOi8KumOS3eD:-KeZDKuH2V-ZBm0h9FPo:bjsechi) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6580883ff21da999fb4ace102ec1593a4f60eebb/.gitignore#L8)):*
> ```
> test_coverage_info/*
> docs/
> scripts/generate_test_coverage.bash
> ```

Why is the script in gitignore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-:-KeZDU7-wMgMn3rXv2ni:bmymd9a)*

**Comment by garimellagowtham** [comment]
Done merging.

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitignore, line 8 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZDKuGGOi8KumOS3eD:-KeZVdarI5D1gUBKGyMu:b-715ecw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/6580883ff21da999fb4ace102ec1593a4f60eebb/.gitignore#L8)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why is the script in gitignore
</blockquote></details>

The script is generated when you run CMake configure. I added a line to README

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-:-KeZVSvvaRTfL8vjFpBP:b4vu5de)*

**Comment by msheckells** [comment]
Reviewed 11 of 34 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/hovering_functors.h, line 8 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZZoIRwsmoEjRQLgDi:-KeZZoISOnPrE5WTazPr:b5hub26) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e0a5a1e73874c1714f204c9de8e33bfd66df05ab/include/aerial_autonomy/actions_guards/hovering_functors.h#L8)):*
> ```objc
> #include <parsernode/common.h>
> 
> using namespace basic_events;
> ```

shouldn't use a namespace in a header file.  All files which include the header will implicitly use the namespace when doing this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by garimellagowtham** [comment]
Review status: 10 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/hovering_functors.h, line 8 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZZoIRwsmoEjRQLgDi:-KeZd7c83l1_DMutip2O:b-euzsvq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e0a5a1e73874c1714f204c9de8e33bfd66df05ab/include/aerial_autonomy/actions_guards/hovering_functors.h#L8)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

shouldn't use a namespace in a header file.  All files which include the header will implicitly use the namespace when doing this
</blockquote></details>

Changed namespace basic_events to be everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Initial manual run of generate_test_coverage.bash fails, but subsequent tries succeed.  Error is `geninfo: ERROR: cannot create /home/matt/catkin_ws/src/aerial_autonomy/test_coverage_info/test_coverage.info!
genhtml: ERROR: cannot read file /home/matt/catkin_ws/src/aerial_autonomy/test_coverage_info/test_coverage.info!`

---

Review status: 10 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-:-KeZdupmZmVZ-5Tu9yIh:b-xzh9xp)*

**Comment by msheckells** [comment]
Other than that, test coverage pre-push hook works as intended :lgtm:

---

Review status: 10 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-:-KeZfK_Jgv3clJvG4DbX:b8gg00x)*

**Comment by msheckells** [comment]
Reviewed 2 of 4 files at r3.
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Reviewed 1 of 4 files at r3.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[setup/generate_test_coverage.bash.in, line 8 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZg8iYO6YKqovP9i4e:-KeZg8iYO6YKqovP9i4f:bfh3sz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f16b7c0a4a1065c943a6d8e31739059168bc6422/setup/generate_test_coverage.bash.in#L8)):*
> ```
>   echo "Catkin BUILD Failed"
>   exit 1
> fi
> ```

 Initial manual run of generate_test_coverage.bash fails, but subsequent tries succeed.  Error is 

`geninfo: ERROR: cannot create /home/matt/catkin_ws/src/aerial_autonomy/test_coverage_info/test_coverage.info! genhtml: ERROR: cannot read file /home/matt/catkin_ws/src/aerial_autonomy/test_coverage_info/test_coverage.info!`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by garimellagowtham** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/generate_test_coverage.bash.in, line 8 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZg8iYO6YKqovP9i4e:-KeZgx2zZD5Mi3kIKDyX:b373gj0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f16b7c0a4a1065c943a6d8e31739059168bc6422/setup/generate_test_coverage.bash.in#L8)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

 Initial manual run of generate_test_coverage.bash fails, but subsequent tries succeed.  Error is 

`geninfo: ERROR: cannot create /home/matt/catkin_ws/src/aerial_autonomy/test_coverage_info/test_coverage.info! genhtml: ERROR: cannot read file /home/matt/catkin_ws/src/aerial_autonomy/test_coverage_info/test_coverage.info!`

</blockquote></details>

Fixed. It could not create `test_coverage_info` folder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by garimellagowtham** [comment]
Can you check the test coverage report to see how it looks?

---

Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-:-KeZh8cnFvlFZsio0Hm_:bmvui4j)*

**Comment by msheckells** [comment]
Test coverage report looks good.  

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/generate_test_coverage.bash.in, line 8 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZg8iYO6YKqovP9i4e:-KeZhdiAcHEdm8TmngMF:bjctaoj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f16b7c0a4a1065c943a6d8e31739059168bc6422/setup/generate_test_coverage.bash.in#L8)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Fixed. It could not create `test_coverage_info` folder.
</blockquote></details>

After pulling the latest, I still get the same error.  If I start without a `test_coverage_info` folder and run it, it still fails, but a `test_coverage_info` folder is created in the process.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-:-KeZhv9AjaXrUZkgE277:b-w61iew)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/generate_test_coverage.bash.in, line 8 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZg8iYO6YKqovP9i4e:-KeZiDMnVGDEizUZntyz:bsqaznj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f16b7c0a4a1065c943a6d8e31739059168bc6422/setup/generate_test_coverage.bash.in#L8)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

After pulling the latest, I still get the same error.  If I start without a `test_coverage_info` folder and run it, it still fails, but a `test_coverage_info` folder is created in the process.
</blockquote></details>

According to this version, the `test_coverage_info`folder is present in the remote. I think you removed the folder. The folder should be present now if you pull the latest version automatically

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/generate_test_coverage.bash.in, line 8 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZg8iYO6YKqovP9i4e:-KeZj5_m5WfBQpqsDbRw:bi1tgv2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f16b7c0a4a1065c943a6d8e31739059168bc6422/setup/generate_test_coverage.bash.in#L8)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

According to this version, the `test_coverage_info`folder is present in the remote. I think you removed the folder. The folder should be present now if you pull the latest version automatically
</blockquote></details>

Couldn't we just create the test_coverage_info folder in the script instead of having it in remote?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by garimellagowtham** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/generate_test_coverage.bash.in, line 8 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20#-KeZg8iYO6YKqovP9i4e:-KeZkpzrNbxwcOxajaSg:b-x4p1c0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f16b7c0a4a1065c943a6d8e31739059168bc6422/setup/generate_test_coverage.bash.in#L8)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Couldn't we just create the test_coverage_info folder in the script instead of having it in remote?
</blockquote></details>

Done creating TEST_COVERAGE_DIR if it does not exist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Comment by msheckells** [comment]
Reviewed 2 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/20)*

**Pull request merged**
