### PR TITLE
Add hardware type to controller_hardware_connector

### PR DESCRIPTION
**Pull request by garimellagowtham**
Including hardware type is necessary to group the connectors
based on hardware. Only one type of connector is active per
hardware. This is only a software grouping and does not actually
check if the correct hardware is being used or not. This allows
for using optimal control connectors which use both quadrotor
and arm to be grouped under one of the existing hardware type
categories.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/13)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 33 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdgZeug-KRCys4Nfh1b:-KdgZeuhI3LOO-rGc0Gd:bgi7n5d) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L33)):*
> ```objc
>     }
>     // Get
>     template<class ControllerHardwareConnectorT>
> ```

I think it would be best to make a separate class called TypeMap or something that allows you to map from a type to an object.  It will need to be templated on the objects' base class. Then QuadrotorSystem can just own a TypeMap and call its get/set functions in getControllerHardwareConnector/addControllerHardwareConnector.  This will allow us to use the TypeMap elsewhere and to avoid code duplication in other robot systems.

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 81 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdgaOHt914NZ1pJAoSy:-KdgaOHt914NZ1pJAoSz:b-uexha8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L81)):*
> ```objc
>   }
> 
>   template <class ControllerHardwareContainerT, class GoalT>
> ```

Should be ControllerHardwareConnectorT

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 91 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdganS9Lq7arfmCaAAg:-KdganS9Lq7arfmCaAAh:b-uexha8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L91)):*
> ```objc
>     }
>   }
>   template <class ControllerHardwareContainerT, class GoalT>
> ```

Should be ControllerHardwareConnectorT

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 102 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdgbWCjkwHj6tnnILlX:-KdgbWCjkwHj6tnnILlY:b9phlsm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L102)):*
> ```objc
>   }
> 
>   void activeControllerRun(HardwareType hardware_type) {
> ```

How about calling it runActiveController to be consistent with other function names.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by garimellagowtham** [comment]
Review status: 1 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 33 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdgZeug-KRCys4Nfh1b:-Kdi0tNvqSVr3igIjWqj:b-k4fo00) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L33)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I think it would be best to make a separate class called TypeMap or something that allows you to map from a type to an object.  It will need to be templated on the objects' base class. Then QuadrotorSystem can just own a TypeMap and call its get/set functions in getControllerHardwareConnector/addControllerHardwareConnector.  This will allow us to use the TypeMap elsewhere and to avoid code duplication in other robot systems.
</blockquote></details>

Done in uav_system.h

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 81 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdgaOHt914NZ1pJAoSy:-Kdi0vWBPHaxhvv9Z9el:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L81)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be ControllerHardwareConnectorT
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 91 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdganS9Lq7arfmCaAAg:-Kdi0vxRITsfd0I7P0PP:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L91)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should be ControllerHardwareConnectorT
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/quadrotor_system.h, line 102 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdgbWCjkwHj6tnnILlX:-Kdi0wRy_knuqe6LBDxu:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c93c4461ae6403c04e38365074498ca116bd4e4e/include/aerial_autonomy/robot_systems/quadrotor_system.h#L102)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

How about calling it runActiveController to be consistent with other function names.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by garimellagowtham** [comment]
Check review each commit separately option. Otherwise, it thinks the quadrotor_system file is deleted.

---

Review status: 1 of 13 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-:-Kdi1WCNCg168mLeU4Bn:b-gmi4vn)*

**Comment by msheckells** [comment]
Reviewed 12 of 13 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/types/type_map.h, line 5 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdiICbjk2GWzMqgWbap:-KdiICbjk2GWzMqgWbaq:b-ghpusw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/09541c2bef28965bdae3eeff77bfe8eca1922d01/include/aerial_autonomy/types/type_map.h#L5)):*
> ```objc
> #include <typeindex>
> // store objects
> #include <unordered_map>
> ```

This looks good. would you mind putting it in a different folder though?  I think the types folder should hold data structs only.  We can have a folder called 'common' to put classes that aren't specific to any category.

---

*[tests/types/type_map_tests.cpp, line 31 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdiIpP4EbMlCCrJmmUu:-KdiIpP5ApY840CWw_k_:bvml671) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/09541c2bef28965bdae3eeff77bfe8eca1922d01/tests/types/type_map_tests.cpp#L31)):*
> ```cpp
>   ASSERT_EQ(object1->i, subclass1.i);
>   ASSERT_EQ(object2->i, subclass2.i);
> }
> ```

Would be good to have a test that overwrites an existing object to make sure it works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by msheckells** [comment]
Reviewed 1 of 13 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by msheckells** [comment]
Reviewed 1 of 13 files at r2.
Review status: 11 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by msheckells** [comment]
Reviewed 2 of 3 files at r3.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by garimellagowtham** [comment]
Review status: 9 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/common/type_map.h, line 5 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdiICbjk2GWzMqgWbap:-KdiM6gX1DFMf0UgCvaG:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/09541c2bef28965bdae3eeff77bfe8eca1922d01/include/aerial_autonomy/common/type_map.h#L5)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

This looks good. would you mind putting it in a different folder though?  I think the types folder should hold data structs only.  We can have a folder called 'common' to put classes that aren't specific to any category.
</blockquote></details>

Done.

---

*[tests/types/type_map_tests.cpp, line 31 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdiIpP4EbMlCCrJmmUu:-KdiM87KcI74uHsyHx0P:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/09541c2bef28965bdae3eeff77bfe8eca1922d01/tests/types/type_map_tests.cpp#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Would be good to have a test that overwrites an existing object to make sure it works.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by msheckells** [comment]
Review status: 9 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/types/type_map_tests.cpp, line 31 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdiIpP4EbMlCCrJmmUu:-KdiMmTTqjt10cF6Z-ZH:bvtfx85) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/09541c2bef28965bdae3eeff77bfe8eca1922d01/tests/types/type_map_tests.cpp#L31)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, what I meant was you should call addObject(subclass1) again with a different instance and then get the object to make sure it changed.  Also, maybe addObject is not the appropriate name.  It's more of a setter function for a particular object class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by msheckells** [comment]
Reviewed 1 of 3 files at r3, 2 of 4 files at r4.
Review status: 11 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by garimellagowtham** [comment]
Review status: 9 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/common/type_map_tests.cpp, line 31 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13#-KdiIpP4EbMlCCrJmmUu:-KdiPxmkFJ2MmEIMGTId:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/09541c2bef28965bdae3eeff77bfe8eca1922d01/tests/common/type_map_tests.cpp#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Sorry, what I meant was you should call addObject(subclass1) again with a different instance and then get the object to make sure it changed.  Also, maybe addObject is not the appropriate name.  It's more of a setter function for a particular object class.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Comment by msheckells** [comment]
Reviewed 1 of 3 files at r3, 1 of 5 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/13)*

**Pull request merged**
