### PR TITLE
Added velocity sensor and tests

### PR DESCRIPTION
**Pull request by sohampatkar10**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/148)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTUR51KVHo1SqXZud:-L-DTUR51KVHo1SqXZue:b-7n2i6o) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/base_sensor.h#L38)):*
> ```objc
>   * @brief gets the latest sensor data
>   */
>   virtual SensorDataT getSensorData() {
> ```

make pure virtual

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 45 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTVUTk1YrCJwWZax-:-L-DTVUTk1YrCJwWZax0:b-7n2i6o) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/base_sensor.h#L45)):*
> ```objc
>   * @brief gets the current status of the sensor
>   */
>   SensorStatus getSensorStatus() {
> ```

make pure virtual

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 58 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTX1G_htLy16Y5rkY:-L-DTX1G_htLy16Y5rkZ:b-ualr26) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/base_sensor.h#L58)):*
> ```objc
>   * @brief variable to store sensor data
>   */
>   Atomic<SensorDataT> sensor_data_;
> ```

remove members

---

*[include/aerial_autonomy/sensors/velocity_sensor.h, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DRVfO50eUNuedY10c:-L-DRVfO50eUNuedY10d:bq4mukv) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/velocity_sensor.h#L31)):*
> ```objc
>   * @brief callback for pose sensor
>   */
>   void odomCallback(const nav_msgs::Odometry::ConstPtr msg) {
> ```

store time message is received

---

*[include/aerial_autonomy/sensors/velocity_sensor.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTIdjFSVO_e58REuj:-L-DTIdjFSVO_e58REuk:b-iafh24) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/velocity_sensor.h#L38)):*
> ```objc
>     Velocity vel_sensor_data(global_vel[0], global_vel[1], global_vel[2]);
>     sensor_data_ = vel_sensor_data;
>   }
> ```

getSensorStatus should return false if (current time > last message time + configurable timeout)

---

*[proto/velocity_sensor_config.proto, line 13 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DR8p-DZAnSSItMrj7:-L-DR8p-DZAnSSItMrj8:bafnon6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/proto/velocity_sensor_config.proto#L13)):*
> ```protobuf
>   * along each axis in meters
>   */
>   optional double max_divergence = 3 [default = 0.5];
> ```

remove this if not used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148)*

**Comment by sohampatkar10** [comment]
Review status: 3 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTUR51KVHo1SqXZud:-L-DcZdl0pQFSFagR3Qz:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/base_sensor.h#L38)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

make pure virtual
</blockquote></details>

Done.

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 45 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTVUTk1YrCJwWZax-:-L-Dc_Gr-Mlp1pfjznyG:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/base_sensor.h#L45)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

make pure virtual
</blockquote></details>

Done.

---

*[include/aerial_autonomy/sensors/base_sensor.h, line 58 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTX1G_htLy16Y5rkY:-L-Dc_xQ_yuEWRvuvFc5:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/base_sensor.h#L58)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

remove members
</blockquote></details>

Done.

---

*[include/aerial_autonomy/sensors/velocity_sensor.h, line 31 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DRVfO50eUNuedY10c:-L-DcgY8FiJXdcbuCjYQ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/velocity_sensor.h#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

store time message is received
</blockquote></details>

Done.

---

*[include/aerial_autonomy/sensors/velocity_sensor.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DTIdjFSVO_e58REuj:-L-DcetllsjKtwQF8VHn:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/include/aerial_autonomy/sensors/velocity_sensor.h#L38)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

getSensorStatus should return false if (current time > last message time + configurable timeout)
</blockquote></details>

Done.

---

*[proto/velocity_sensor_config.proto, line 13 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DR8p-DZAnSSItMrj7:-L-DcizFKAOL8Oc1JD4k:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed8be86dd963c09c22e4fe98d6b7592daf53d968/proto/velocity_sensor_config.proto#L13)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

remove this if not used
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148)*

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[proto/velocity_sensor_config.proto, line 10 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DhHvbpvpS34rx7DaJ:-L-DhHve04DOZBzdVyQV:bljob9k) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/33e5751892d8c51b3d8c551dce27feac65f98241/proto/velocity_sensor_config.proto#L10)):*
> ```protobuf
>   optional config.Transform sensor_transform = 1;
>   /**
>   * @brief maximum allowed divergence from gps data
> ```

fix doc

---

*[tests/sensors/velocity_sensor_tests.cpp, line 63 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DhXc5OmiBhMGhpwFs:-L-DhXc5OmiBhMGhpwFt:bd0zrj7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/33e5751892d8c51b3d8c551dce27feac65f98241/tests/sensors/velocity_sensor_tests.cpp#L63)):*
> ```cpp
>   ros::Duration(0.01).sleep();
>   ros::spinOnce();
> ```

Check it is true here before the sleep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148)*

**Comment by sohampatkar10** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[proto/velocity_sensor_config.proto, line 10 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DhHvbpvpS34rx7DaJ:-L-DjKvHarJ3c6K8RiWm:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/33e5751892d8c51b3d8c551dce27feac65f98241/proto/velocity_sensor_config.proto#L10)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done.

---

*[tests/sensors/velocity_sensor_tests.cpp, line 63 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148#-L-DhXc5OmiBhMGhpwFs:-L-DlVZyVYQj8LouEYK-:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/33e5751892d8c51b3d8c551dce27feac65f98241/tests/sensors/velocity_sensor_tests.cpp#L63)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Check it is true here before the sleep
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/148)*

**Pull request merged**
