### PR TITLE
Add verbose controller status

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/80)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 5 of 16 files at r1.
Review status: 5 of 16 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/common/controller_status.h, line 3 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krfl-mJpL4nZ4k3Dv2t:-Krfl-mJpL4nZ4k3Dv2u:b-53hldo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/common/controller_status.h#L3)):*
> ```objc
> #pragma once
> // Html utils
> #include <aerial_autonomy/common/html_utils.h>
> ```

use this include in the source file, not here

---

*[include/aerial_autonomy/common/controller_status.h, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krfl5Be3gV4PYCdEjBJ:-Krfl5Be3gV4PYCdEjBK:b-ejnhgp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/common/controller_status.h#L5)):*
> ```objc
> #include <aerial_autonomy/common/html_utils.h>
> // Ostream
> #include <iostream>
> ```

this too

---

*[include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h, line 100 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krflc7SPhklPRcq6nrD:-Krflc7SPhklPRcq6nrE:bj7pu2l) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h#L100)):*
> ```objc
>     // Check if controller converged
>     if (controller_.isConverged(sensor_data, controller_description)) {
>       setStatus(ControllerStatus::Completed, "Completed Controller");
> ```

use "Controller converged"

---

*[include/aerial_autonomy/controllers/base_controller.h, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrfmVY1hc3resBiYVSC:-KrfmVY1hc3resBiYVSD:b6uqp8b) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/controllers/base_controller.h#L40)):*
> ```objc
>   */
>   bool isConverged(SensorDataType sensor_data, std::stringstream &description) {
>     return isConvergedImplementation(sensor_data, goal_, description);
> ```

not sure about this... possibly better for isConvergedImplemention to return a class instance that holds a status enum and string desciption (similatr to ControllerStatus)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80)*

**Comment by msheckells** [comment]
Reviewed 11 of 16 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80)*

**Comment by garimellagowtham** [comment]
Install googletest release 1.8.0. This version fixes a bug with ASSERT_TRUE as explained here. To install googletest, follow these steps
```
git  clone https://github.com/google/googletest.git
cd googletest
git checkout release-1.8.0
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_GMOCK=ON -DBUILD_GTEST=ON
make
sudo make install
sudo ldconfig
```

---

Review status: 1 of 25 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-:-Krxdl2IW0sUmlTe7OuA:bfk2d9v)*

**Comment by garimellagowtham** [comment]
Review status: 1 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/common/controller_status.h, line 3 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krfl-mJpL4nZ4k3Dv2t:-Krxdxc3MlggTrv5oiJm:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/common/controller_status.h#L3)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

use this include in the source file, not here
</blockquote></details>

Done.

---

*[include/aerial_autonomy/common/controller_status.h, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krfl5Be3gV4PYCdEjBJ:-KrxdyTUutqRGuYLXmg0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/common/controller_status.h#L5)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

this too
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h, line 100 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krflc7SPhklPRcq6nrD:-Krxe5xrRrv7QJdfWkVT:b-eyt3u2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h#L100)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

use "Controller converged"
</blockquote></details>

this is done inside controller `isConverged` function.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrfmVY1hc3resBiYVSC:-KrxeGGJyXzDwk61x8g9:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/015381e4759a6f68af870e40074076504349b43a/include/aerial_autonomy/controllers/base_controller.h#L40)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

not sure about this... possibly better for isConvergedImplemention to return a class instance that holds a status enum and string desciption (similatr to ControllerStatus)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80)*

**Comment by msheckells** [comment]
Reviewed 24 of 24 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[CMakeLists.txt, line 219 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxwTp6571rCtAM3rAv:-KrxwTp6571rCtAM3rAw:b1kw8f0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/CMakeLists.txt#L219)):*
> ```CMake
> )
> add_dependencies(aerial_autonomy proto)
> target_link_libraries(aerial_autonomy proto ${catkin_LIBRARIES} ${PROTOBUF_LIBRARIES} ${GLOG_LIBRARIES} ${Boost_LIBRARIES})
> ```

Didn't you tell me not to link libs to libs for some reason previously?

---

*[include/aerial_autonomy/common/controller_status.h, line 3 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxwwQmkGab6N0g7dEq:-KrxwwQmkGab6N0g7dEr:b-892zmq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/common/controller_status.h#L3)):*
> ```objc
> #pragma once
> // set precision
> #include <iomanip>
> ```

is this needed in the header or can it be moved to source?

---

*[include/aerial_autonomy/common/controller_status.h, line 118 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krxx6TUnlc0Cs7XJ_-A:-Krxx6TUnlc0Cs7XJ_-B:b-83sjoh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/common/controller_status.h#L118)):*
> ```objc
>    * This is pretty useful to check controller status implies controller
>    * convergence or not. For example:
>    * if(controller_status) { do something} can be used to perform
> ```

Nice!

---

*[include/aerial_autonomy/common/thread_safe_state_machine.h, line 32 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxxLM27fpnt6dXYn8x:-KrxxLM27fpnt6dXYn8y:b-if91pd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/common/thread_safe_state_machine.h#L32)):*
> ```objc
>   mutable boost::recursive_mutex
>       process_event_mutex_; ///< Mutex to synchronize process event functions
>                             /**
> ```

weird indentation here

---

*[include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h, line 82 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxxsKbpI8vBVbNrkQO:-KrxxsKbpI8vBVbNrkQP:b-jdhzml) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h#L82)):*
> ```objc
>     // run the controller
>     // send the data back to hardware manager
>     SensorDataType sensor_data; // Declare sensor data
> ```

I know this has nothing to do with your PR....but when did we ever add comments about declaring a variable.  That's so weird...

---

*[include/aerial_autonomy/controllers/base_controller.h, line 37 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxyNZoyLGPFarlks3h:-KrxyNZoyLGPFarlks3i:b-ckm2ev) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/controllers/base_controller.h#L37)):*
> ```objc
>   * checking
>   *
>   * @return status that contains different states the controller and debug info.
> ```

"states the controller"?

---

*[src/controllers/constant_heading_depth_controller.cpp, line 46 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krxz_wnGf-Vv3sK00_M:-Krxz_wnGf-Vv3sK00_N:bnvumkm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/src/controllers/constant_heading_depth_controller.cpp#L46)):*
> ```cpp
>   // Add optional description
>   ControllerStatus status(ControllerStatus::Active);
>   status << " Error pos, Yaw: " << error.x << error.y << error.z << error_yaw;
> ```

Error Position

---

*[src/controllers/relative_pose_controller.cpp, line 27 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxzYT52OIJ0umUQzPY:-KrxzPkAHqY2qEW7xZav:bnvumkm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/src/controllers/relative_pose_controller.cpp#L27)):*
> ```cpp
>   // Add optional description
>   ControllerStatus status(ControllerStatus::Active);
>   status << "Error Pos, Rotation: " << abs_error_position.x()
> ```

Error Position

---

*[src/controllers/relative_pose_controller.cpp, line 37 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxzLcN3FIvBJSFGRvl:-KrxzLcO5QGqUU7b-CxQ:b-9jetiq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/src/controllers/relative_pose_controller.cpp#L37)):*
> ```cpp
>     VLOG(1) << "Reached goal";
>     status.setStatus(ControllerStatus::Completed, "Reached goal");
>     return status;
> ```

unnecessary return statement

---

*[tests/common/controller_status_tests.cpp, line 72 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krxzv1zZq95U-SynV0K:-Krxzv1zZq95U-SynV0L:b4i7sxc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/tests/common/controller_status_tests.cpp#L72)):*
> ```cpp
>   EXPECT_EQ(controller_status_1, controller_status_3);
>   EXPECT_NE(controller_status_1, controller_status_2);
> }
> ```

Test if(controller_status) with Completed returns true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80)*

**Comment by garimellagowtham** [comment]
Review status: 12 of 25 files reviewed at latest revision, 10 unresolved discussions.

---

*[CMakeLists.txt, line 219 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxwTp6571rCtAM3rAv:-Krzbiwh2sIhvL6ITYmp:b-vc4xs4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/CMakeLists.txt#L219)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Didn't you tell me not to link libs to libs for some reason previously?
</blockquote></details>

We were already linking catkin_LIBRARIES. I added the remaining ones. I don't know of any side-effects of doing this.

---

*[include/aerial_autonomy/common/controller_status.h, line 3 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxwwQmkGab6N0g7dEq:-KrzhN0U6WwO20-BHt4d:ba3dfob) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/common/controller_status.h#L3)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

is this needed in the header or can it be moved to source?
</blockquote></details>

Removed

---

*[include/aerial_autonomy/common/thread_safe_state_machine.h, line 32 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxxLM27fpnt6dXYn8x:-KrzhLAuXzup-4-DlUdO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/common/thread_safe_state_machine.h#L32)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

weird indentation here
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h, line 82 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxxsKbpI8vBVbNrkQO:-KrzhJsFoqqBDg6HvxmX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/controller_hardware_connectors/base_controller_hardware_connector.h#L82)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I know this has nothing to do with your PR....but when did we ever add comments about declaring a variable.  That's so weird...
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 37 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxyNZoyLGPFarlks3h:-KrzhHhkUqjpZw8p1Ia9:bjhuysu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/include/aerial_autonomy/controllers/base_controller.h#L37)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

"states the controller"?
</blockquote></details>

Fixed comment

---

*[src/controllers/constant_heading_depth_controller.cpp, line 46 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krxz_wnGf-Vv3sK00_M:-KrzhGnQxIkAKf61CV44:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/src/controllers/constant_heading_depth_controller.cpp#L46)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Error Position
</blockquote></details>

Done.

---

*[src/controllers/relative_pose_controller.cpp, line 27 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxzYT52OIJ0umUQzPY:-KrzkEPp9A53dGkGn0Ey:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/src/controllers/relative_pose_controller.cpp#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Error Position
</blockquote></details>

Done.

---

*[src/controllers/relative_pose_controller.cpp, line 37 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-KrxzLcN3FIvBJSFGRvl:-KrzhBJmTkB8V0CuRVud:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/src/controllers/relative_pose_controller.cpp#L37)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

unnecessary return statement
</blockquote></details>

Done.

---

*[tests/common/controller_status_tests.cpp, line 72 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80#-Krxzv1zZq95U-SynV0K:-KrzhAFX4lLVyfUFbKEz:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fbf86df6d78d1f338e4ae70d18f4acb84ee4e9e1/tests/common/controller_status_tests.cpp#L72)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Test if(controller_status) with Completed returns true
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80)*

**Comment by msheckells** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/80)*

**Pull request merged**
