### PR TITLE
Updates for building with ROS melodic on ubuntu 18.04

### PR DESCRIPTION
**Pull request by cdimmig**
Additionally updated launching the simulation and added a cmake option for compiling with arm plugins

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223)

### CODE REVIEW

**Review by gbaraban — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @cdimmig)

___
*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 416 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223#-MbHf3Um8jVr_bfPSNOV:-MbHf3Um8jVr_bfPSNOW:bg4myvz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c5be724c5aabd9c4c4205304cf36e5eb4e2335b1/include/aerial_autonomy/actions_guards/pick_place_functors.h#L416)):*
> ```objc
>    * @return state config
>    */
>   // template <class FSM>
> ```

These functions are needed for the FollowingWaypointState to work.  My guess from the error message is that there's a bug earlier that's leading to the templates being improperly parsed by the compiler.  That's been my experience with other headers in the past.

**Review by gbaraban — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223)* status: all files reviewed, 1 unresolved discussion (waiting on @cdimmig)

**Review by cdimmig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @gbaraban)

___
*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 416 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223#-MbHf3Um8jVr_bfPSNOV:-MbOFKlx5Mb04TgdG057:bb2py9a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/c5be724c5aabd9c4c4205304cf36e5eb4e2335b1/include/aerial_autonomy/actions_guards/pick_place_functors.h#L416)):*
<details><summary><i>Previously, gbaraban wrote…</i></summary><blockquote>

These functions are needed for the FollowingWaypointState to work.  My guess from the error message is that there's a bug earlier that's leading to the templates being improperly parsed by the compiler.  That's been my experience with other headers in the past.
</blockquote></details>

Added those sections back in and figured out the issue!

**Review by gbaraban — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cdimmig)

**Pull request merged**
