### PR TITLE
Doxygen documentation

### PR DESCRIPTION
**Pull request by garimellagowtham**
Create pre-push hook to check there is enough documentation.
This ensures that we have enough documentation before pushing to server.
You can have local commits without documentation. This lets one write the features
first and work on documentation later. But the code on the server should be well documented.

Add scripts to generate document coverage report
Add documentation to improve the coverage to desired value

If branch name starts with `develop` as in `develop_my_branch`, the pre-push script will not perform any checks.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/18)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 8 of 36 files at r1.
Review status: 8 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18)*

**Comment by msheckells** [comment]
Reviewed 27 of 37 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 22 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeVEDCIgii6a5cYeFTI:-KeVEDCJV1MKZHUZmiX_:b-e0whma) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/README.md#L22)):*
> ```Markdown
> 
> ## Documentation Coverage
> Use coverxygen to generate documentation coverage for the doc: https://github.com/psycofdj/coverxygen
> ```

Should add a note saying that the user must have lcov and coverxygen installed

---

*[include/aerial_autonomy/common/type_map.h, line 14 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeV9EK74DWJbnUp1AsE:-KeV9EK74DWJbnUp1AsF:b-jqcb78) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/include/aerial_autonomy/common/type_map.h#L14)):*
> ```objc
> template <class GenericObjectT> class TypeMap {
>   /**
>   * @brief Map to store the controller to hardware connectors
> ```

It isn't specific to ControllerHardwareConnectors.  It's just a map that uses a type as a key.

---

*[setup/hooks/pre-push, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeVC4v1BICs5CoJKafg:-KeVC4v1BICs5CoJKafh:bxozh98) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/setup/hooks/pre-push#L6)):*
> ```
> if [[ $branch_name == develop* ]];
> then
>   echo "Development branch no push checks"
> ```

If we push a dev branch to the remote which bypasses this check, isn't it still possible to merge it into master (using github) without ever running this check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18)*

**Comment by msheckells** [comment]
Tested to make sure it is working.  Did not see any issues.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-:-KeVIeYO4Da6wDAdVO0o:b-h6y0j1)*

**Comment by garimellagowtham** [comment]
Review status: 35 of 37 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 22 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeVEDCIgii6a5cYeFTI:-KeWXRhSXR5G7pdLgEkc:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/README.md#L22)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Should add a note saying that the user must have lcov and coverxygen installed
</blockquote></details>

Done.

---

*[include/aerial_autonomy/common/type_map.h, line 14 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeV9EK74DWJbnUp1AsE:-KeWXXzYor1Zx9YTVeFt:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/include/aerial_autonomy/common/type_map.h#L14)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

It isn't specific to ControllerHardwareConnectors.  It's just a map that uses a type as a key.
</blockquote></details>

Done.

---

*[setup/hooks/pre-push, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeVC4v1BICs5CoJKafg:-KeWXZ2vY_4einPlhUSt:b-s3favy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/setup/hooks/pre-push#L6)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

If we push a dev branch to the remote which bypasses this check, isn't it still possible to merge it into master (using github) without ever running this check?
</blockquote></details>

Yes! But we cannot merge until we do a code review. So I am assuming we will not let develop branches to merge into master without manually performing these checks.

To be fair, one can always skip these checks using --no-verify option while pushing and we will not know that the branch did not pass the tests. 

I am not sure but we can use some integration service like reviewable to stop pull requests from merging without enough code coverage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18)*

**Comment by msheckells** [comment]
Review status: 35 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

*[setup/hooks/pre-push, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18#-KeVC4v1BICs5CoJKafg:-KeWjNj2bMAx5-v1XKhQ:b9z5zk3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/80c74ed98acd32930b7bb3a5ba552b77c4bb3953/setup/hooks/pre-push#L6)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Yes! But we cannot merge until we do a code review. So I am assuming we will not let develop branches to merge into master without manually performing these checks.

To be fair, one can always skip these checks using --no-verify option while pushing and we will not know that the branch did not pass the tests. 

I am not sure but we can use some integration service like reviewable to stop pull requests from merging without enough code coverage.

</blockquote></details>

Yeah, I think a code review should catch it.  We will have to manually check tests on dev branches before merge is all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/18)*

**Pull request merged**
