### PR TITLE
Add uav arm system

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/65)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Remove "UAV" and use "robot" in the PositionControllerConfig proto file since the config is also used for arm system.

---

Reviewed 19 of 21 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[CMakeLists.txt, line 331 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGaZ4kEf82v3288QLs:-KnGaZ4kEf82v3288QLt:b-8fslph) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/CMakeLists.txt#L331)):*
> ```CMake
>   target_link_libraries(${PROJECT_NAME}-uav-system-test aerial_autonomy proto ${catkin_LIBRARIES} ${QUAD_SIM_PARSER_LIBS} ${Boost_LIBRARIES} ${PROTOBUF_LIBRARIES} ${GLOG_LIBRARIES})
> endif()
> if(TARGET ${PROJECT_NAME}-uav-arm-system-test)
> ```

We should add a macro for creating a new test since the code is repeated a lot. Something like
`ADD_TEST([source_name], [ADDITIONAL_LIBS])` can automatically create the catkin_add_gtest with target-name extracted from source name.

---

*[include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h, line 12 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGiQH4tSEjRqGcXxwX:-KnGiQH4tSEjRqGcXxwY:b-k2f7ou) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h#L12)):*
> A visual servoing controller that uses a tracker output as feedback
and moves the arm to a goal location relative to a target.

---

*[include/aerial_autonomy/robot_systems/arm_system.h, line 21 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGlKVdpR5xHwDdDpka:-KnGlKVdpR5xHwDdDpkb:bnv1g0w) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/robot_systems/arm_system.h#L21)):*
> ```objc
>   */
>   ArmParser &arm_hardware_;
>   /// \todo Add controllers, controller connectors, config if needed
> ```

Is this comment still needed?

---

*[include/aerial_autonomy/robot_systems/uav_arm_system.h, line 42 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGrXZixFW6gFFuwUB-:-KnGrXZjEjz4-GQr9bHy:burn9ds) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/robot_systems/uav_arm_system.h#L42)):*
> ```objc
>   * @return string representation of the UAV system state
>   */
>   std::string getSystemStatus() const { return UAVSystem::getSystemStatus(); }
> ```

Add arm status too.

---

*[src/controller_hardware_connectors/visual_servoing_controller_arm_connector.cpp, line 22 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGtHVdoF46Gk_Ajr7l:-KnGtHVe_nSKc5fohnzV:bkfc4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/src/controller_hardware_connectors/visual_servoing_controller_arm_connector.cpp#L22)):*
> ```cpp
>     Position controls) {
>   Eigen::Matrix4d pose;
>   pose.setIdentity();
> ```

This should be calculated based on object pose. For matrice, this will be ok, but for Octocopter, this will not work. We can have a pre-defined orientation of the object in the global frame (gravity aligned and not care about yaw). Then the arm orientation can be computed based on camera transform, UAV orientation, and object transform. This should be added to the RelativePositionController(renamed in this case) though.

---

*[tests/robot_systems/arm_system_tests.cpp, line 13 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGxjYU3XqxwgoJDC5N:-KnGxjYU3XqxwgoJDC5O:b2uk2zz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/tests/robot_systems/arm_system_tests.cpp#L13)):*
> ```cpp
>   ASSERT_NO_THROW(new ArmSystem(arm));
> }
> /// \todo Add tests for arm system using a simulated arm hardware
> ```

we still have to do this though! Maybe in a later PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-:-KnGa-qn-80UsqjXT_RL:b-4ktagb)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/robot_systems/uav_arm_system.h, line 42 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGrXZixFW6gFFuwUB-:-KnLaPgetpledI_Hm2Yr:b-ahlwpo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/robot_systems/uav_arm_system.h#L42)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add arm status too.
</blockquote></details>

Can you add a few lines to the function ArmSystem::getSystemStatus() so that its not empty. For example
Arm end effector transform, arm enabled/disabled, arm command status

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65)*

**Comment by msheckells** [comment]
Done

---

Review status: 13 of 27 files reviewed at latest revision, 7 unresolved discussions.

---

*[CMakeLists.txt, line 331 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGaZ4kEf82v3288QLs:-KnH0HECetHUCQ4DRAGC:b-y7t5pt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/CMakeLists.txt#L331)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We should add a macro for creating a new test since the code is repeated a lot. Something like
`ADD_TEST([source_name], [ADDITIONAL_LIBS])` can automatically create the catkin_add_gtest with target-name extracted from source name.
</blockquote></details>

Agreed, can do in a different PR

---

*[include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h, line 12 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGiQH4tSEjRqGcXxwX:-KnKduFN2k-AqPk4Utyx:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h#L12)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

> A visual servoing controller that uses a tracker output as feedback
and moves the arm to a goal location relative to a target.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/arm_system.h, line 21 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGlKVdpR5xHwDdDpka:-KnKe-JRFHVZjYiMq-nE:bu2j3sr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/robot_systems/arm_system.h#L21)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Is this comment still needed?
</blockquote></details>

Nope. Removed.

---

*[include/aerial_autonomy/robot_systems/uav_arm_system.h, line 42 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGrXZixFW6gFFuwUB-:-KnKeB53w3KlGi8EzZpA:bk6ku26) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/include/aerial_autonomy/robot_systems/uav_arm_system.h#L42)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can you add a few lines to the function ArmSystem::getSystemStatus() so that its not empty. For example
Arm end effector transform, arm enabled/disabled, arm command status
</blockquote></details>

Done. Will fill ArmSystem::getSystemStatus in another PR

---

*[src/controller_hardware_connectors/visual_servoing_controller_arm_connector.cpp, line 22 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGtHVdoF46Gk_Ajr7l:-KnLbZj8-PlQHkSxqB8I:bm12jb0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/src/controller_hardware_connectors/visual_servoing_controller_arm_connector.cpp#L22)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This should be calculated based on object pose. For matrice, this will be ok, but for Octocopter, this will not work. We can have a pre-defined orientation of the object in the global frame (gravity aligned and not care about yaw). Then the arm orientation can be computed based on camera transform, UAV orientation, and object transform. This should be added to the RelativePositionController(renamed in this case) though.
</blockquote></details>

Now called RelativePoseController.  Object is assumed to have gravity aligned frame with yaw the same as the UAV.  Goal pose is specified relative to object frame.

---

*[tests/robot_systems/arm_system_tests.cpp, line 13 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnGxjYU3XqxwgoJDC5N:-KnH0aexjparg11TnBlq:b-rzfhde) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/78928d1a6d4899f5014eb599eed6c4701526162e/tests/robot_systems/arm_system_tests.cpp#L13)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

we still have to do this though! Maybe in a later PR.
</blockquote></details>

Yes, agreed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-:-KnKdhwUUom9SpAYxMx7:bb6un1j)*

**Comment by garimellagowtham** [comment]
Reviewed 14 of 17 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h, line 5 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnLtLfIzsx_nsJkL-SH:-KnLtLfIzsx_nsJkL-SI:b-60phyo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h#L5)):*
> ```objc
> #include "aerial_autonomy/controllers/relative_pose_controller.h"
> #include "aerial_autonomy/trackers/base_tracker.h"
> #include "aerial_autonomy/types/position.h"
> ```

Is this header still needed?

---

*[include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h, line 15 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnLthgoZ4ruSO0x90B8:-KnLthgoZ4ruSO0x90B9:b-3hqkph) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h#L15)):*
> ```objc
> /**
>  * @brief A visual servoing controller that uses a tracker output as feedback
>  * and moves the arm to a goal location relative to the tracked target
> ```

"to a goal pose"

---

*[src/controllers/relative_pose_controller.cpp, line 21 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnPOjYLtiwQ6y3nO4pF:-KnPONmLUrXfx05toR9A:bv2mkg9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/src/controllers/relative_pose_controller.cpp#L21)):*
> ```cpp
>   tf::Quaternion relative_quat = relative_pose.getRotation();
>   tf::Quaternion goal_quat = goal.getRotation();
>   double rot_diff = (relative_quat.inverse() * goal_quat).getAngle();
> ```

we want to use `getAngleShortestPath` to ensure 2Pi is mapped to 0.

---

*[tests/state_machines/uav_state_machine_tests.cpp, line 95 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnPZ2TTX-i4CmZid8g8:-KnPZ2TUY76k0GY5JNhF:b-xds7d0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/tests/state_machines/uav_state_machine_tests.cpp#L95)):*
> ```cpp
> TEST_F(StateMachineTests, TakeoffManualControlAbort) {
>   drone_hardware.setBatteryPercent(100);
>   // Takeoff
> ```

Is this a tab? Should we be consistent and just use spaces everywhere and expand all tabs to spaces?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65)*

**Comment by msheckells** [comment]
Review status: 24 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h, line 5 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnLtLfIzsx_nsJkL-SH:-KnXD6Czr2lik4ijzgT0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h#L5)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Is this header still needed?
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h, line 15 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnLthgoZ4ruSO0x90B8:-KnXD9JB31RYhjASVIkk:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/include/aerial_autonomy/controller_hardware_connectors/visual_servoing_controller_arm_connector.h#L15)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

"to a goal pose"
</blockquote></details>

Done.

---

*[src/controllers/relative_pose_controller.cpp, line 21 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnPOjYLtiwQ6y3nO4pF:-KnXDtpeMzXSLdsGO50C:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/src/controllers/relative_pose_controller.cpp#L21)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

we want to use `getAngleShortestPath` to ensure 2Pi is mapped to 0.
</blockquote></details>

Done.

---

*[tests/state_machines/uav_state_machine_tests.cpp, line 95 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-KnPZ2TTX-i4CmZid8g8:-KnXE81IvzywtzZD-Zjt:bmpged4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5a543c7926c956fc9f35722c6b88ba1134ac0a2/tests/state_machines/uav_state_machine_tests.cpp#L95)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Is this a tab? Should we be consistent and just use spaces everywhere and expand all tabs to spaces?
</blockquote></details>

It looks like spaces to me.  This only got changed because of clang-format I think.  I have been using spaces everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65)*

**Comment by garimellagowtham** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/65#-:-KnZvR-VJ8jqDW4LZgna:bnfp4nl)*

**Pull request merged**
