### PR TITLE
Add rpyt based relative pose controller

### PR DESCRIPTION
**Pull request by garimellagowtham**
Added controller, tests.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/138)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/common/controller_status.h, line 35 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KzipVzJNVSaB_TolcdW:-KzipVzK367NeixIj8rt:b-vbd8n6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/include/aerial_autonomy/common/controller_status.h#L35)):*
> ```objc
>                    * debug header and debug info in the specified order.
>                    */
>   std::vector<std::tuple<Status, std::string, std::string, std::vector<double>>>
> ```

Is it worth it to just make this tuple a struct of its own?  Could also just typedef it

---

*[include/aerial_autonomy/controllers/rpyt_based_relative_pose_controller.h, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KziquN3XVZN78UHdBql:-KziquN406fyiqoihM2z:b-h12usr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/include/aerial_autonomy/controllers/rpyt_based_relative_pose_controller.h#L49)):*
> ```objc
> protected:
>   /**
>    * @brief Run the control loop.  Uses a velocity controller to keep a desired
> ```

Uses a rpyt controller

---

*[src/common/controller_status.cpp, line 66 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KzivU56uodRhmyUjZH3:-KzivU56uodRhmyUjZH4:b-yarrrf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/src/common/controller_status.cpp#L66)):*
> ```cpp
>   // - If both rhs status and lhs status are complete, resulting
>   //   status is complete too.
>   if (rhs_status.status_ == ControllerStatus::Critical) {
> ```

Is it more clear to write
`if(rhs_status.status_ == ControllerStatus::Critical || this->status_ == ControllerStatus::Critical) { 
  status_ = ControllerStatus::Critical;
} else if (rhs_status.status_ == ControllerStatus::Completed && this->status_ == ControllerStatus::Completed) {
  status_ = ControllerStatus::Completed; 
} else {
  status_ = ControllerStatus::Active;
}`

---

*[tests/common/controller_status_tests.cpp, line 153 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KzitNWjGNwrQTZSah6G:-KzitNWjGNwrQTZSah6H:b1lj7n2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/tests/common/controller_status_tests.cpp#L153)):*
> ```cpp
>   // Combine
>   controller_status += ControllerStatus(ControllerStatus::Active, "active");
>   ASSERT_EQ(controller_status, ControllerStatus::Active);
> ```

Why would the controller be active while its inner or outer loop is NotEngaged?

---

*[tests/controllers/rpyt_based_relative_pose_controller_tests.cpp, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KziuUoidg9dYkrpg98E:-KziuUoidg9dYkrpg98F:b-kok2zb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/tests/controllers/rpyt_based_relative_pose_controller_tests.cpp#L88)):*
> ```cpp
>           std::abs(current_acceleration[i]) > 1e-6) {
>         ASSERT_FALSE(std::signbit(desired_acceleration_direction[i] *
>                                   current_acceleration[i]));
> ```

can't you normalize current_acceleration and desired_acceleration_direction and then compare the vectors directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138)*

**Comment by garimellagowtham** [comment]
Review status: 7 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/common/controller_status.h, line 35 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KzipVzJNVSaB_TolcdW:-KzjNqTsQK6DE1-z-nbX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/include/aerial_autonomy/common/controller_status.h#L35)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Is it worth it to just make this tuple a struct of its own?  Could also just typedef it
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/rpyt_based_relative_pose_controller.h, line 49 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KziquN3XVZN78UHdBql:-KzjNrPzNRlb_3Ehqfc2:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/include/aerial_autonomy/controllers/rpyt_based_relative_pose_controller.h#L49)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Uses a rpyt controller
</blockquote></details>

Done.

---

*[src/common/controller_status.cpp, line 66 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KzivU56uodRhmyUjZH3:-KzjNzu940B7u4eLNthy:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/src/common/controller_status.cpp#L66)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Is it more clear to write
`if(rhs_status.status_ == ControllerStatus::Critical || this->status_ == ControllerStatus::Critical) { 
  status_ = ControllerStatus::Critical;
} else if (rhs_status.status_ == ControllerStatus::Completed && this->status_ == ControllerStatus::Completed) {
  status_ = ControllerStatus::Completed; 
} else {
  status_ = ControllerStatus::Active;
}`
</blockquote></details>

Done.

---

*[tests/common/controller_status_tests.cpp, line 153 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KzitNWjGNwrQTZSah6G:-KzjNt-tpzTXluo6rTRD:b-gtud1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/tests/common/controller_status_tests.cpp#L153)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why would the controller be active while its inner or outer loop is NotEngaged?
</blockquote></details>

As long as one controller is active, the net controller is active.

---

*[tests/controllers/rpyt_based_relative_pose_controller_tests.cpp, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138#-KziuUoidg9dYkrpg98E:-KzjNxNzJNGn244Iu0b-:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2b83c24fc0771e6f83214b8a6bd4b701787d16c1/tests/controllers/rpyt_based_relative_pose_controller_tests.cpp#L88)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

can't you normalize current_acceleration and desired_acceleration_direction and then compare the vectors directly?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138)*

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/138)*

**Pull request merged**
