### PR TITLE
Post pick action

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/115)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 1 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[events/pick_place_events, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn3LpSJcwZz1NP6fCg:-Ktn3LpSJcwZz1NP6fCh:byp18fd) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/events/pick_place_events#L6)):*
> ```
>   visual_servoing_events/VisualServoingEventManager/GoHome
>   Pick
>   RecordPointA
> ```

Remove

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 109 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn3QAn-3nuOtm9rOoI:-Ktn3QAn-3nuOtm9rOoJ:b-n162ym) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/include/aerial_autonomy/actions_guards/pick_place_functors.h#L109)):*
> ```objc
> 
> /**
> * @brief Action to reach a pre designated point A
> ```

pre-designated waypoint

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 228 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn4ZVPzMseRBO8GoJJ:-Ktn4ZVQsOPmBl3VyJTf:b-dar8lw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L228)):*
> ```objc
> * @brief state names to get name based on state id
> */
> static constexpr std::array<const char *, 13> state_names = {
> ```

update vector size

---

*[proto/uav_arm_system_config.proto, line 30 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn4hNWzOKtgqwRT_0K:-Ktn4hNWzOKtgqwRT_0L:byv4c2k) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/proto/uav_arm_system_config.proto#L30)):*
> ```protobuf
> 
>   /**
>   * @brief Point where to leave object
> ```

I think saying "List of waypoints used in state machine" might be more accurate since only one of the waypoints is used for dropping the object

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115)*

**Comment by garimellagowtham** [comment]
Review status: 4 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[events/pick_place_events, line 6 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn3LpSJcwZz1NP6fCg:-Ktn8khkZHlNqeWrfA9e:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/events/pick_place_events#L6)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 109 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn3QAn-3nuOtm9rOoI:-Ktn8s83Z-j1ry_RqzZl:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/include/aerial_autonomy/actions_guards/pick_place_functors.h#L109)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

pre-designated waypoint
</blockquote></details>

Done.

---

*[proto/uav_arm_system_config.proto, line 30 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-Ktn4hNWzOKtgqwRT_0K:-Ktn9X6rdF5uNPMktHHp:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0233cd7f0ebeabc3dce3a916c4004da85ffca26f/proto/uav_arm_system_config.proto#L30)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I think saying "List of waypoints used in state machine" might be more accurate since only one of the waypoints is used for dropping the object
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115)*

**Comment by msheckells** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAe3DTNSKw9OY8h93:-KtnAe3HZbew_q4N5hvA:b-wlrdve) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L13)):*
> ```objc
>  * @brief Manages communication between a drone plugin and a position controller
>  * that outputs
>  * position commands.
> ```

velocity commands

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 36 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAm8MPn3xccCX3YI5:-KtnAm8MPn3xccCX3YI6:b-592qr2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L36)):*
> ```objc
> protected:
>   /**
>    * @brief  does not extract any data since nothing is needed
> ```

extracts position

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 45 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAkj_xFAJdhxYJQLt:-KtnAkj_xFAJdhxYJQLu:bgiuw2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L45)):*
> ```objc
> 
>   /**
>    * @brief  Send position commands to hardware
> ```

velocity

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 47 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAjMZJNz4HSdffmVt:-KtnAjM_9pqkcqdRhS5M:bgiuw2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L47)):*
> ```objc
>    * @brief  Send position commands to hardware
>    *
>    * @param controls position command to send to UAV
> ```

velocity

---

*[src/controller_hardware_connectors/velocity_based_position_controller_drone_connector.cpp, line 19 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAztDQ_3Az7LCibZR:-KtnAztDQ_3Az7LCibZS:b-s7pa3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/src/controller_hardware_connectors/velocity_based_position_controller_drone_connector.cpp#L19)):*
> ```cpp
>   velocity_cmd.z = controls.z;
>   drone_hardware_.cmdvel_yaw_rate_guided(velocity_cmd, controls.yaw_rate);
> }
> ```

add TODO somewhere for adding connector tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115)*

**Comment by garimellagowtham** [comment]
Review status: 12 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 13 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAe3DTNSKw9OY8h93:-KtnJ5ZS4EM06J4bFojO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L13)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

velocity commands
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 36 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAm8MPn3xccCX3YI5:-KtnJ6468l8aHG2P8KS0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L36)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

extracts position
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 45 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAkj_xFAJdhxYJQLt:-KtnJ3zzlmV2kliI9b69:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L45)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

velocity
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h, line 47 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAjMZJNz4HSdffmVt:-KtnJ4Lk3sEuCZglsZaX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/include/aerial_autonomy/controller_hardware_connectors/velocity_based_position_controller_drone_connector.h#L47)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

velocity
</blockquote></details>

Done.

---

*[src/controller_hardware_connectors/velocity_based_position_controller_drone_connector.cpp, line 19 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115#-KtnAztDQ_3Az7LCibZR:-KtnI9Em_q2S-h0jwhGi:b3aiz4g) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fdd069c1efedcf58a3b47ed1aaad6d4170af6be2/src/controller_hardware_connectors/velocity_based_position_controller_drone_connector.cpp#L19)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

add TODO somewhere for adding connector tests.
</blockquote></details>

Done in the header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115)*

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/115)*

**Pull request merged**
