### PR TITLE
Pick place test

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/104)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 3 of 12 files at r3, 9 of 11 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 126 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWyeLX7-hfroFj6s3t:-KtWyeLY4XunDB-t2Hpq:b-ad4zdb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L126)):*
> ```objc
>   // Guards
>   /**
>   * @brief Guard to stop pick place if arm is not powered or vision is not
> ```

update comment since we are not checking for vision in this guard

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 20 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWymRQLvlSkr9gGLzY:-KtWymRQLvlSkr9gGLzZ:b-3tdjv3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/include/aerial_autonomy/trackers/alvar_tracker.h#L20)):*
> ```objc
>   */
>   AlvarTracker(ros::NodeHandle &nh)
>       : BaseTracker(new ClosestTrackingStrategy(25)), nh_(nh),
> ```

Ideally should be part of protobuf. Add todo

---

*[launch/matrice_visual_servoing_alvar.launch, line 30 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWz3HnekT3OeD9nPXA:-KtWz3HnekT3OeD9nPXB:b-8172vu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/launch/matrice_visual_servoing_alvar.launch#L30)):*
> ```XML
>   
>   <include file="$(find ar_track_alvar)/launch/pr2_indiv_no_kinect.launch">
>     <arg name="marker_size" value="10" />
> ```

I think it is 8 or something now??

---

*[param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt, line 38 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWzjgUhQtw4g-zFh9X:-KtWzUf2VT1dDxthVMhu:b-5fhoxy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt#L38)):*
> ```
>     tracker_type: "Alvar"
> 
>     camera_transform: 0.2093
> ```

This should be changed in a lot of protbufs. Based on a quick grep:
```
./matrice_pick_place_roi_config.pbtxt
./matrice_visual_servoing_config.pbtxt
./matrice_visual_servoing_config_pointgrey.pbtxt
./matrice_pick_place_alvar_config.pbtxt
./matrice_hil_pick_place_alvar_pointgrey_config.pbtxt
./visual_servoing_config.pbtxt
./matrice_visual_servoing_config_hil_pointgrey.pbtxt
./matrice_pick_place_alvar_pointgrey_config.pbtxt
./matrice_hil_pick_place_alvar_config.pbtxt
./pick_place_simulator_config.pbtxt
```

---

*[param/matrice_visual_servoing_config_hil_pointgrey.pbtxt, line 32 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtYBZkZKD1lHQmI2jyH:-KtYBZkZKD1lHQmI2jyI:b-dgjtyv) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/param/matrice_visual_servoing_config_hil_pointgrey.pbtxt#L32)):*
> ```
>     tracker_type: "Alvar"
> 
>     camera_transform: 0.18
> ```

wrong camera transform

---

*[param/matrice_visual_servoing_config_pointgrey.pbtxt, line 33 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWzbMUU6WJcpsfWA9J:-KtWzbMUU6WJcpsfWA9K:b-92fi0e) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/param/matrice_visual_servoing_config_pointgrey.pbtxt#L33)):*
> ```
>     tracker_type: "Alvar"
> 
>     camera_transform: 0.18
> ```

should match pick_place one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104)*

**Comment by msheckells** [comment]
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 126 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWyeLX7-hfroFj6s3t:-KtYKtbUn4WVWybf4Wet:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L126)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

update comment since we are not checking for vision in this guard
</blockquote></details>

Done.

---

*[include/aerial_autonomy/trackers/alvar_tracker.h, line 20 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWymRQLvlSkr9gGLzY:-KtYL2M7Gw-DnvcTXTRb:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/include/aerial_autonomy/trackers/alvar_tracker.h#L20)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Ideally should be part of protobuf. Add todo
</blockquote></details>

Done.

---

*[launch/matrice_visual_servoing_alvar.launch, line 30 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWz3HnekT3OeD9nPXA:-KtYLFnOTreG3rYO9zBf:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/launch/matrice_visual_servoing_alvar.launch#L30)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I think it is 8 or something now??
</blockquote></details>

Done.

---

*[param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt, line 38 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWzjgUhQtw4g-zFh9X:-KtYMEubI6ed6KCGA4sW:bum2s0k) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/param/matrice_hil_pick_place_alvar_pointgrey_config.pbtxt#L38)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This should be changed in a lot of protbufs. Based on a quick grep:
```
./matrice_pick_place_roi_config.pbtxt
./matrice_visual_servoing_config.pbtxt
./matrice_visual_servoing_config_pointgrey.pbtxt
./matrice_pick_place_alvar_config.pbtxt
./matrice_hil_pick_place_alvar_pointgrey_config.pbtxt
./visual_servoing_config.pbtxt
./matrice_visual_servoing_config_hil_pointgrey.pbtxt
./matrice_pick_place_alvar_pointgrey_config.pbtxt
./matrice_hil_pick_place_alvar_config.pbtxt
./pick_place_simulator_config.pbtxt
```

</blockquote></details>

Camera transform only needs to be changed in the pointgrey-specific configs.

---

*[param/matrice_visual_servoing_config_hil_pointgrey.pbtxt, line 32 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtYBZkZKD1lHQmI2jyH:-KtYLoTBDbDxyv4afJeZ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/param/matrice_visual_servoing_config_hil_pointgrey.pbtxt#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

wrong camera transform
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104)*

**Comment by msheckells** [comment]
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions.

---

*[param/matrice_visual_servoing_config_pointgrey.pbtxt, line 33 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104#-KtWzbMUU6WJcpsfWA9J:-KtYOgPVQcUyg_2dXRGK:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b5916ffa879f17ca2784cd5bb8417c9bdc0ad4/param/matrice_visual_servoing_config_pointgrey.pbtxt#L33)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

should match pick_place one
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104)*

**Comment by garimellagowtham** [comment]
Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/104)*

**Pull request merged**
