### PR TITLE
Disengage connector when its aborted

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188)

### CODE REVIEW

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[tests/controller_connectors/controller_connector_tests.cpp, line 145 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188#-LDrYe362Ma5zL7WA_Sj:-LDrYe362Ma5zL7WA_Sk:bs2ite6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/08a4c1aa4c5b8eab8fee2f855a9f8a64adec27ac/tests/controller_connectors/controller_connector_tests.cpp#L145)):*
> ```cpp
>             ControllerStatus::NotEngaged);
>   // Running controller does not change the control
>   robot_system.runActiveController(ControllerGroup::UAV);
> ```

should be ControllerGroup::Arm

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188)*

**Comment by garimellagowtham** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/controller_connectors/controller_connector_tests.cpp, line 145 at r1](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188#-LDrYe362Ma5zL7WA_Sj:-LDs89eT7ZT6To9MpJS-:b-bttoee) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/08a4c1aa4c5b8eab8fee2f855a9f8a64adec27ac/tests/controller_connectors/controller_connector_tests.cpp#L145)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

should be ControllerGroup::Arm
</blockquote></details>

Added comment

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188)*

**Comment by msheckells** [comment]
test_results/aerial_autonomy/gtest-aerial_autonomy-pick-place-state-machine-test.xml: 11 tests, 0 errors, 1 failures
test_results/aerial_autonomy/gtest-aerial_autonomy-relative-pose-visual-servoing-drone-connector-test.xml: 5 tests, 0 errors, 1 failures
test_results/aerial_autonomy/gtest-aerial_autonomy-rpyt-relative-pose-visual-servoing-connector-test.xml: 5 tests, 0 errors, 1 failures
test_results/aerial_autonomy/gtest-aerial_autonomy-visual-servoing-arm-connector-test.xml: 4 tests, 0 errors, 1 failures
test_results/aerial_autonomy/gtest-aerial_autonomy-visual-servoing-drone-connector-test.xml: 4 tests, 0 errors, 1 failures

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188#-:-LDsE-Pp8criwJyBUACW:boz6gg5)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 82 at r2](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188#-LDspKhQ5LyhPmrOGUX7:-LDwpfip1Ot0kZi1zmHE:b-4a2kzp) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/fb0d977bd3cf44ddfd6cab26ab179a02e796d947/include/aerial_autonomy/robot_systems/base_robot_system.h#L82)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

> pick
@msheckells This line is causing the tests to fail.
Explanation:
The above line aborts the previous controller in the controller group before re-enabling the new controller. The problem comes in when the new controller is the same as old controller. Between this line and the next line, the state machine checks for the status of the controller and aborts the internal action functor as it sees the status is not engaged. We cannot block the state machine from here

Partial solution:
Check that controller is the same as the new one. If it is same do not abort the previous controller. In the example I am testing i.e pick_place_state_machine_test, the test fails for waypoint following in which both the aborted and activated controllers are the same.
But this does not work with controllers with dependent connectors.

Complete Solution:
The correct solution is to stop state machine from executing its timer while setGoal function is being executed. I am not sure why the state machine timer is running while setGoal function is being executed. 
</blockquote></details>

This is fixed

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 80 at r3](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188#-LDwpY5MAL_hiPpzrjqy:-LDwpY5MAL_hiPpzrjqz:b6njrc5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a053c210f9bdceb2d528cb893b9e7cd870f39968/include/aerial_autonomy/robot_systems/base_robot_system.h#L80)):*
> ```objc
>         controller_connector_container_.getObject<ControllerConnectorT>();
>     ControllerGroup controller_group =
>         controller_connector->getControllerGroup();
> ```

should probably check if controller_connector == nullptr here as well

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188)*

**Comment by garimellagowtham** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/robot_systems/base_robot_system.h, line 80 at r3](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188#-LDwpY5MAL_hiPpzrjqy:-LDwsTp7CdHshHGgP2l7:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/a053c210f9bdceb2d528cb893b9e7cd870f39968/include/aerial_autonomy/robot_systems/base_robot_system.h#L80)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

should probably check if controller_connector == nullptr here as well
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/188)*

**Pull request merged**
