### PR TITLE
Remove extra function calls in onboard system handler

### PR DESCRIPTION
**Pull request by garimellagowtham**
Remove functions and move everything to initializer lists

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/22)

### CODE REVIEW

**Comment by msheckells** [comment]
*[include/aerial_autonomy/onboard_system_handler.h, line 55 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22#-KeiP9ob47Lvr8U0bsaN:-KeiP9ob47Lvr8U0bsaO:bmf88l3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d83592239afbcf81faded9c93a5b8f883f260725/include/aerial_autonomy/onboard_system_handler.h#L55)):*
> ```objc
>     // TODO Gowtham: Make parser plugin throw exception if it cannot initialize
>     uav_hardware_->initialize(nh);
> ```

Are you changing the parsers to take care of timing out internally?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22)*

**Comment by garimellagowtham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/onboard_system_handler.h, line 55 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22#-KeiP9ob47Lvr8U0bsaN:-KeiRoE4sg4BqPP95ig7:bxxy64g) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d83592239afbcf81faded9c93a5b8f883f260725/include/aerial_autonomy/onboard_system_handler.h#L55)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Are you changing the parsers to take care of timing out internally?
</blockquote></details>

I will change parser to throw exception if it cannot initialize the parser

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 170 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22#-KeiamChB0BnMOMzqmh7:-KeiamCicA_dcj9T-N21:bo6umg8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d83592239afbcf81faded9c93a5b8f883f260725/CMakeLists.txt#L170)):*
> ```CMake
> )
> 
> #target_link_libraries(aerial_autonomy ${Boost_LIBRARIES})
> ```

Remove comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22)*

**Comment by msheckells** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22#-:-KeibO4RI-2em_ynpOsv:bnfp4nl)*

**Comment by garimellagowtham** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 170 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22#-KeiamChB0BnMOMzqmh7:-Keic2QZUmtPd3ju7qzC:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d83592239afbcf81faded9c93a5b8f883f260725/CMakeLists.txt#L170)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Remove comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/22)*

**Pull request merged**
