### PR TITLE
Add external quad simulator to all tests

### PR DESCRIPTION
**Pull request by garimellagowtham**
This is connected with another merge request in quad_sim_parser package: https://git.lcsr.jhu.edu/ggarime1/rqt_quadcopter_parsers/merge_requests/1

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/23)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/controller_hardware_connectors/manual_rpyt_controller_drone_connector_tests.cpp, line 77 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23#-Keo46UDfJ_kXofA8Hbt:-Keo46UDfJ_kXofA8Hbu:b-z5fro8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/82941e3a6167c24b07a904e0ff6fbc493195d2f1/tests/controller_hardware_connectors/manual_rpyt_controller_drone_connector_tests.cpp#L77)):*
> ```cpp
> 
>   //\todo (matt) : Need to test thrust.  Could test if we have a parser with
>   // dynamics
> ```

We can check localpos.z now right?  We have actual thrust dynamics with the simulator

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 26 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23#-Keo4VSIYR0e1yhNISIB:-Keo4VSIYR0e1yhNISIC:bqfr4ac) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/82941e3a6167c24b07a904e0ff6fbc493195d2f1/CMakeLists.txt#L26)):*
> ```CMake
> find_package(Protobuf REQUIRED) 
> 
> # Quad simulator parser dependencies
> ```

Shouldn't we just link all of these libs to quad_simulator_parser when it is built?  It doesn't seem right that we would have to know the dependencies of another package in order to use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23)*

**Comment by garimellagowtham** [comment]
Review status: 14 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 26 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23#-Keo4VSIYR0e1yhNISIB:-KeoB6VKBICZt0McHvQi:bm7yx9k) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/82941e3a6167c24b07a904e0ff6fbc493195d2f1/CMakeLists.txt#L26)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Shouldn't we just link all of these libs to quad_simulator_parser when it is built?  It doesn't seem right that we would have to know the dependencies of another package in order to use it.
</blockquote></details>

You mean to add to a catkin_package LIBRARIES. I thought this will add the same libraries multiple times. I was even considering copying the quad simulator files from gcop to avoid using gcop libraries. We can also create a static library if we have all the source files together.

---

*[tests/controller_hardware_connectors/manual_rpyt_controller_drone_connector_tests.cpp, line 77 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23#-Keo46UDfJ_kXofA8Hbt:-KeoI0LFZvPi1vLbBm1h:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/82941e3a6167c24b07a904e0ff6fbc493195d2f1/tests/controller_hardware_connectors/manual_rpyt_controller_drone_connector_tests.cpp#L77)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We can check localpos.z now right?  We have actual thrust dynamics with the simulator
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23)*

**Comment by msheckells** [comment]
*[CMakeLists.txt, line 26 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23#-Keo4VSIYR0e1yhNISIB:-KeoLzxL7kMbLkWY4nrY:baqc138) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/82941e3a6167c24b07a904e0ff6fbc493195d2f1/CMakeLists.txt#L26)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

You mean to add to a catkin_package LIBRARIES. I thought this will add the same libraries multiple times. I was even considering copying the quad simulator files from gcop to avoid using gcop libraries. We can also create a static library if we have all the source files together.
</blockquote></details>

add a catkin_package LIBRARIES for what? It looks like all the dependencies for quad_simulator are already linked to quad_simulator when it is built in the quad_simulator_parser package.  ldd on the .so shows gcop and tinyxml.  Why do we have to link them again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 26 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23#-Keo4VSIYR0e1yhNISIB:-Kepw97RkCkM0Q3a5P0P:bx2bu8g) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/82941e3a6167c24b07a904e0ff6fbc493195d2f1/CMakeLists.txt#L26)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

add a catkin_package LIBRARIES for what? It looks like all the dependencies for quad_simulator are already linked to quad_simulator when it is built in the quad_simulator_parser package.  ldd on the .so shows gcop and tinyxml.  Why do we have to link them again?
</blockquote></details>

Without linking these libraries, the build fails with undefined references. Shared libraries do not include dependent libraries. we have to link them manually.  The linking of libraries to libraries is only a flag for cmake to ensure all dependent executables also link to the dependent libraries.  This feature does not work for executables outside the project. 
```
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-pos-ctrlr-drone-cnctr-test
/usr/bin/ld: CMakeFiles/aerial_autonomy-builtin-vel-ctrlr-drone-cnctr-test.dir/tests/controller_hardware_connectors/builtin_velocity_controller_drone_connector_tests.cpp.o: undefined reference to symbol '_ZN4gcop3SO38InstanceEv'
//usr/local/lib/libgcop_utils.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [/home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-builtin-vel-ctrlr-drone-cnctr-test] Error 1
make[2]: *** [CMakeFiles/aerial_autonomy-builtin-vel-ctrlr-drone-cnctr-test.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/aerial_autonomy-pos-ctrlr-drone-cnctr-test.dir/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp.o: undefined reference to symbol '_ZN4gcop3SO38InstanceEv'
//usr/local/lib/libgcop_utils.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [/home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-pos-ctrlr-drone-cnctr-test] Error 1
make[2]: *** [CMakeFiles/aerial_autonomy-pos-ctrlr-drone-cnctr-test.dir/all] Error 2
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-manual-rpyt-ctrlr-drone-cnctr-test
/usr/bin/ld: CMakeFiles/aerial_autonomy-manual-rpyt-ctrlr-drone-cnctr-test.dir/tests/controller_hardware_connectors/manual_rpyt_controller_drone_connector_tests.cpp.o: undefined reference to symbol '_ZN4gcop3SO38InstanceEv'
//usr/local/lib/libgcop_utils.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [/home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-manual-rpyt-ctrlr-drone-cnctr-test] Error 1
make[2]: *** [CMakeFiles/aerial_autonomy-manual-rpyt-ctrlr-drone-cnctr-test.dir/all] Error 2
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-state-machine-gui-connector-pose-test
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-uav-system-test
/usr/bin/ld: CMakeFiles/aerial_autonomy-uav-system-test.dir/tests/robot_systems/uav_system_tests.cpp.o: undefined reference to symbol '_ZN4gcop3SO38InstanceEv'
//usr/local/lib/libgcop_utils.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [/home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-uav-system-test] Error 1
make[2]: *** [CMakeFiles/aerial_autonomy-uav-system-test.dir/all] Error 2
[ 96%] Built target aerial_autonomy-state-machine-gui-connector-pose-test
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-basic-functor-tests
/usr/bin/ld: CMakeFiles/aerial_autonomy-basic-functor-tests.dir/tests/actions_guards/basic_functor_tests.cpp.o: undefined reference to symbol '_ZN4gcop3SO38InstanceEv'
//usr/local/lib/libgcop_utils.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [/home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-basic-functor-tests] Error 1
make[2]: *** [CMakeFiles/aerial_autonomy-basic-functor-tests.dir/all] Error 2
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-basic-state-machine-test
/usr/bin/ld: CMakeFiles/aerial_autonomy-basic-state-machine-test.dir/tests/state_machines/basic_state_machine_tests.cpp.o: undefined reference to symbol '_ZN4gcop3SO38InstanceEv'
//usr/local/lib/libgcop_utils.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [/home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-basic-state-machine-test] Error 1
make[2]: *** [CMakeFiles/aerial_autonomy-basic-state-machine-test.dir/all] Error 2
Linking CXX executable /home/gowtham/indigo_workspace/devel/lib/aerial_autonomy/aerial_autonomy-onboard-system-handler-test
[ 96%] Built target aerial_autonomy-onboard-system-handler-test
make[1]: *** [CMakeFiles/run_tests.dir/rule] Error 2
make: *** [run_tests] Error 2
[aerial_autonomy] <== '/home/gowtham/indigo_workspace/build/aerial_autonomy/build_env.sh /usr/bin/make run_tests --jobserver-fds=3,5 -j' failed with return code '2'
                                                  
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/23)*

**Pull request merged**
