### PR TITLE
Add data logger

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/86)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/log/data_stream.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFO3Ld1PbQvfERVtoI:-KsFO3Ld1PbQvfERVtoJ:bvmlioz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/include/aerial_autonomy/log/data_stream.h#L1)):*
> ```objc
> #pragma once
> ```

Add stream modifier called header

---

*[include/aerial_autonomy/log/log.h, line 64 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFHlC-dhs64mqRN5rn:-KsFHlC011k6jZY8Pzwf:br8tt13) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/include/aerial_autonomy/log/log.h#L64)):*
> ```objc
> 
>   LogConfig config_;
>   std::map<std::string, DataStream> streams_;
> ```

Use unordered_map: http://en.cppreference.com/w/cpp/container/unordered_map

---

*[src/common/async_timer.cpp, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFS_8UZIg_yFRyTYIF:-KsFS_8V2eIbYHZfNGiL:bv1pc75) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/common/async_timer.cpp#L40)):*
> ```cpp
>   } else {
>     throw std::logic_error(
>         "Cannot set AsyncTimer duration while it is running");
> ```

Stop the timer, set timer duration and start the timer again.

---

*[src/log/data_stream.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFG_N8fHV5Ga0pvfo2:-KsFDywG4ViX-NNZpcNY:b-rwm8z8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/data_stream.cpp#L32)):*
> ```cpp
>   fs_.flush();
>   buffer_.str(std::string());
>   buffer_.clear();
> ```

Add a function to reset stringstream.

---

*[src/log/log.cpp, line 3 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFHUu1ov3XAB9bWqKF:-KsFHUu1ov3XAB9bWqKG:b-yu96xv) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L3)):*
> ```cpp
> #include "aerial_autonomy/log/log.h"
> 
> #include <boost/filesystem.hpp>
> ```

Can use std filesystem (http://en.cppreference.com/w/cpp/experimental/fs/create_directory)

---

*[src/log/log.cpp, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFLhqghqtC0HsLsPvw:-KsFLhqghqtC0HsLsPvx:bc30cv4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L27)):*
> ```cpp
> }
> 
> void Log::configureStreams(LogConfig config) {
> ```

Add a function to add stream which takes in a Datastreamconfig.

---

*[src/log/log.cpp, line 37 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFIe25BtqQtm_fFIKr:-KsFIe26aNEQitO4MHax:b-7820ty) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L37)):*
> ```cpp
>     streams_.emplace(
>         stream_config.stream_id(),
>         DataStream(config_.directory() + "/" + stream_config.stream_id(),
> ```

Can use filesystem::path (http://en.cppreference.com/w/cpp/experimental/fs/path)

---

*[tests/common/async_timer_tests.cpp, line 42 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFCQCpBxC7JuXZPBmC:-KsFCQCqqXp_CWbbRVaG:bvngp29) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/common/async_timer_tests.cpp#L42)):*
> ```cpp
>   std::this_thread::sleep_for(std::chrono::milliseconds(1000));
>   ASSERT_GE(this->x, 50);
>   timer.stop();
> ```

Assert ranges instead of GE, LE

---

*[tests/log/log_tests.cpp, line 35 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFV4K2rYKQQxddNZO2:-KsFV4K2rYKQQxddNZO3:b-nf96ae) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L35)):*
> ```cpp
> 
>   template <typename T>
>   void verifyData(std::vector<std::vector<T>> log, std::string path,
> ```

This looks very much like the verifyData from datastream_tests except for the file path. You can use a common header with this function and test for file path separately maybe?

---

*[tests/log/log_tests.cpp, line 106 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFW74p-v0Kg0yfOx1g:-KsFW74p-v0Kg0yfOx1h:b-n8z0ru) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L106)):*
> ```cpp
> 
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
>   verifyData(data0, Log::instance()["stream0"].path(),
> ```

Use waitUntilResult from test_utils if possible

---

*[tests/log/log_tests.cpp, line 132 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFVqHJFv5FLYVLXhnT:-KsFVqHJFv5FLYVLXhnU:b-n8z0ru) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L132)):*
> ```cpp
>              Log::instance()["stream1"].configuration().delimiter());
>   // Wait for write
>   std::this_thread::sleep_for(std::chrono::milliseconds(500));
> ```

Use waitUntilResult from test_utils if possible

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[include/aerial_autonomy/log/log.h, line 64 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFHlC-dhs64mqRN5rn:-KsFwOVj2KY47vQosyKc:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/include/aerial_autonomy/log/log.h#L64)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Use unordered_map: http://en.cppreference.com/w/cpp/container/unordered_map
</blockquote></details>

Done.

---

*[src/common/async_timer.cpp, line 40 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFS_8UZIg_yFRyTYIF:-KsFwkitLcEUcgmaqewa:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/common/async_timer.cpp#L40)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Stop the timer, set timer duration and start the timer again.
</blockquote></details>

Done.

---

*[src/log/data_stream.cpp, line 32 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFG_N8fHV5Ga0pvfo2:-KsFxezAK9WNmbKT7wXs:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/data_stream.cpp#L32)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add a function to reset stringstream.
</blockquote></details>

Done.

---

*[src/log/log.cpp, line 3 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFHUu1ov3XAB9bWqKF:-KsFyKbTjQJLF5DX02AN:bgcddi7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L3)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can use std filesystem (http://en.cppreference.com/w/cpp/experimental/fs/create_directory)
</blockquote></details>

It doesn't look like experimental/filesystem  is in C++11 unless I'm missing something

---

*[src/log/log.cpp, line 27 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFLhqghqtC0HsLsPvw:-KsFz-KVtgbQPjoHqJlZ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L27)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add a function to add stream which takes in a Datastreamconfig.
</blockquote></details>

Done.

---

*[tests/common/async_timer_tests.cpp, line 42 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFCQCpBxC7JuXZPBmC:-KsG1X0yEn0oRjDH9tOo:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/common/async_timer_tests.cpp#L42)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Assert ranges instead of GE, LE
</blockquote></details>

Done.

---

*[tests/log/log_tests.cpp, line 35 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFV4K2rYKQQxddNZO2:-KsG5tl-bhuffWtx7GOe:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L35)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This looks very much like the verifyData from datastream_tests except for the file path. You can use a common header with this function and test for file path separately maybe?
</blockquote></details>

Done.

---

*[tests/log/log_tests.cpp, line 106 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFW74p-v0Kg0yfOx1g:-KsG1bGAaSLv1y48FDd_:bqlgrwb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L106)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Use waitUntilResult from test_utils if possible
</blockquote></details>

There isn't really a result to wait for.  I could wait until verifyData returns true if that's what you mean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Comment by garimellagowtham** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/log/log.cpp, line 37 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFIe25BtqQtm_fFIKr:-KsH0bTMzlMPoSUfxn8s:b-8rflci) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L37)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can use filesystem::path (http://en.cppreference.com/w/cpp/experimental/fs/path)
</blockquote></details>

There is also boost filesystem path (https://theboostcpplibraries.com/boost.filesystem-paths)

---

*[tests/common/async_timer_tests.cpp, line 1 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsH1y8PovoLMB-LL2_k:-KsH1y8QpbLRPwhAMN60:bogpgil) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/3e586e98392e2d09e273646310aa1bd35d7b2b13/tests/common/async_timer_tests.cpp#L1)):*
> ```cpp
> #include <gmock/gmock.h>
> ```

Do u need gmock?

---

*[tests/log/log_tests.cpp, line 106 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFW74p-v0Kg0yfOx1g:-KsH3bpSymBB-YfOwSMl:b-abdxag) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L106)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

There isn't really a result to wait for.  I could wait until verifyData returns true if that's what you mean.
</blockquote></details>

You can wait for verifyFileData to return true. You only have to wait for the first instance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/log/log.cpp, line 37 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFIe25BtqQtm_fFIKr:-KsJen54u8lWyQLhBl5v:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/src/log/log.cpp#L37)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

There is also boost filesystem path (https://theboostcpplibraries.com/boost.filesystem-paths)
</blockquote></details>

Done.

---

*[tests/common/async_timer_tests.cpp, line 1 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsH1y8PovoLMB-LL2_k:-KsJerRkDQcojJ5vk_3W:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/3e586e98392e2d09e273646310aa1bd35d7b2b13/tests/common/async_timer_tests.cpp#L1)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Do u need gmock?
</blockquote></details>

Done.

---

*[tests/log/log_tests.cpp, line 106 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFW74p-v0Kg0yfOx1g:-KsJfC7qPa0HiRa_ZMTk:b9er2fj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L106)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

You can wait for verifyFileData to return true. You only have to wait for the first instance.
</blockquote></details>

The problem is that verifyFileData does not return a bool.  It has a bunch of internal asserts that it calls, which would cause it to fail before anything gets written to the log file.  I could remove the internal asserts, but they were quite useful in determining where bugs were

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Comment by garimellagowtham** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/log/data_stream_tests.cpp, line 45 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsJj2BRMdnpd628wwoM:-KsJj2BRMdnpd628wwoN:bh2ay01) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4e71e6bd00cf949ee37c6ad648564d6d24fb0faa/tests/log/data_stream_tests.cpp#L45)):*
> ```cpp
>   ds->write();
> 
>   test_utils::verifyFileData(data, ds->path().string(), config_.delimiter());
> ```

use filepath in the function definition instead of here.

---

*[tests/log/log_tests.cpp, line 106 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFW74p-v0Kg0yfOx1g:-KsJjK5_S-waFV1OQSpS:b-f7w2hm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/tests/log/log_tests.cpp#L106)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

The problem is that verifyFileData does not return a bool.  It has a bunch of internal asserts that it calls, which would cause it to fail before anything gets written to the log file.  I could remove the internal asserts, but they were quite useful in determining where bugs were
</blockquote></details>

I think its fine the way it is!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Comment by msheckells** [comment]
Review status: 8 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/log/data_stream.h, line 1 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsFO3Ld1PbQvfERVtoI:-KsJx67bpfkEZrBQeKLq:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/cf7c7c13ac024577ceb195118e71553c1f738e07/include/aerial_autonomy/log/data_stream.h#L1)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add stream modifier called header
</blockquote></details>

Done.

---

*[tests/log/data_stream_tests.cpp, line 45 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86#-KsJj2BRMdnpd628wwoM:-KsJx4fvAEuqtUNwg6_k:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4e71e6bd00cf949ee37c6ad648564d6d24fb0faa/tests/log/data_stream_tests.cpp#L45)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

use filepath in the function definition instead of here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Comment by garimellagowtham** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/86)*

**Pull request merged**
