### PR TITLE
Add marker direction estimator

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/161)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CMakeLists.txt, line 493 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161#-L-csEri6tSVFkln7NEd:-L-csEri6tSVFkln7NEe:b-uto9mm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52edf59cc9ca5ef261cb62f9a3126b503b6e2eac/CMakeLists.txt#L493)):*
> ```CMake
>   target_link_libraries(${PROJECT_NAME}-thrust-gain-estimator-test aerial_autonomy)
> endif()
> if(TARGET ${PROJECT_NAME}-thrust-gain-estimator-test)
> ```

wrong test in if

---

*[include/aerial_autonomy/estimators/ar_marker_direction_estimator.h, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161#-L-csLaYGWX8MRkXFYUx:-L-csLaZOPiI2OHxEvjN:brsjr21) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52edf59cc9ca5ef261cb62f9a3126b503b6e2eac/include/aerial_autonomy/estimators/ar_marker_direction_estimator.h#L17)):*
> ```objc
> *
> */
> class ARMarkerDirectionEstimator {
> ```

This isn't specific to AR markers.  It can take any tracking vector.  Maybe call it something more general

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Comment by msheckells** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/controller_hardware_connectors/rpyt_relative_pose_visual_servoing_connector.cpp, line 9 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161#-L-d-a40LFXfIzNairxB:-L-d-a41LX_8S-QO7boH:b2ve7gl) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/70b41e38d9177a74e34c5ab93b029f6249ea5128/src/controller_hardware_connectors/rpyt_relative_pose_visual_servoing_connector.cpp#L9)):*
> ```cpp
>   drone_hardware_.getquaddata(quad_data);
>   tf::Transform tracking_pose;
>   if (!getTrackingTransformRotationCompensatedQuadFrame(tracking_pose)) {
> ```

we should add a way to check whether the tracking_pose we are retrieving is new or old.  If it is old (and we've already used it in the KF during a previous step) then we should not use the pose in the estimate function.  It could cause issues when we lose track of the marker since the inconsistency will propagate to our velocity estimate.  This is one motivation to have a separate correct step for velocity and position.  An alternative solution is to increase the position measurement covariance temporarily when we haven't received a new measurement since the last estimate call.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Comment by msheckells** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Comment by garimellagowtham** [comment]
Review status: 4 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[CMakeLists.txt, line 493 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161#-L-csEri6tSVFkln7NEd:-L-ghw8AgQ3cOzPsQApE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52edf59cc9ca5ef261cb62f9a3126b503b6e2eac/CMakeLists.txt#L493)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

wrong test in if
</blockquote></details>

Done.

---

*[include/aerial_autonomy/estimators/tracking_vector_estimator.h, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161#-L-csLaYGWX8MRkXFYUx:-L-gvxvcStA65UZO6gSg:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/52edf59cc9ca5ef261cb62f9a3126b503b6e2eac/include/aerial_autonomy/estimators/tracking_vector_estimator.h#L17)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

This isn't specific to AR markers.  It can take any tracking vector.  Maybe call it something more general
</blockquote></details>

Done.

---

*[src/controller_hardware_connectors/rpyt_relative_pose_visual_servoing_connector.cpp, line 9 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161#-L-d-a40LFXfIzNairxB:-L-gvw8y3Um6-weSdo6r:b-iw1i2d) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/70b41e38d9177a74e34c5ab93b029f6249ea5128/src/controller_hardware_connectors/rpyt_relative_pose_visual_servoing_connector.cpp#L9)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

we should add a way to check whether the tracking_pose we are retrieving is new or old.  If it is old (and we've already used it in the KF during a previous step) then we should not use the pose in the estimate function.  It could cause issues when we lose track of the marker since the inconsistency will propagate to our velocity estimate.  This is one motivation to have a separate correct step for velocity and position.  An alternative solution is to increase the position measurement covariance temporarily when we haven't received a new measurement since the last estimate call.
</blockquote></details>

Added todo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Comment by msheckells** [comment]
Reviewed 14 of 14 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Comment by msheckells** [comment]
Reviewed 7 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/161)*

**Pull request merged**
