### PR TITLE
Add thrust gain estimator and tests

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/149)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 10 of 11 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dpw7S68_ix6FDSxRa:-L-Dpw7TPY00Am27me1a:b-b7ego1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L88)):*
> ```objc
>    * @brief get current thrust gain
>    * @return  current thrust gain
>    */
> ```

note that the estimator takes into account delay between thrust and acceleration measurements by using a buffer

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 100 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DnQq-Da4_yhTJ921w:-L-DnQq-Da4_yhTJ921x:b-gma35l) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L100)):*
> ```objc
>    * @return estimated thrust gain
>    */
>   double processSensorThrustPair(double roll, double pitch, double body_z_acc,
> ```

is this only used internally?  If so make private

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 112 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dq29oTKAHaJqtbQla:-L-Dq29oTKAHaJqtbQlb:b-onv3vw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L112)):*
> ```objc
>   double thrust_gain_;
>   double mixing_gain_;
>   unsigned int buffer_size_;
> ```

maybe call this delay buffer just to clarify?

---

*[proto/thrust_gain_estimator_config.proto, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DneS7uyPEtQBEw9Bm:-L-DneS7uyPEtQBEw9Bn:bvtcot9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/proto/thrust_gain_estimator_config.proto#L16)):*
> ```protobuf
>   * will
>   * follow the estimated thrust gain closely. The mixing gain has to be between
>   * 0
> ```

has to be between 0 and 1

---

*[proto/thrust_gain_estimator_config.proto, line 20 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DnlMu1rYNx9nh7qLr:-L-DnlMu1rYNx9nh7qLs:bljob9k) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/proto/thrust_gain_estimator_config.proto#L20)):*
> ```protobuf
>   optional double mixing_gain = 2 [ default = 0.1 ];
>   /**
>   * @brief Maximum commanded velocity along each axis in m/s
> ```

fix doc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149)*

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/estimators/thrust_gain_estimator.cpp, line 62 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DsAPmScXVblrHRl5E:-L-DsAPmScXVblrHRl5F:b-1ajce4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b7867dc4ada733adb3540127d5011dc5edd463/src/estimators/thrust_gain_estimator.cpp#L62)):*
> ```cpp
> 
> void ThrustGainEstimator::addThrustCommand(double thrust_command) {
>   if (thrust_command_queue_.size() == buffer_size_) {
> ```

check thrust is positive

---

*[tests/estimators/thrust_gain_estimator_tests.cpp, line 60 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DsZWInjyQXG1mcO9v:-L-DsZWInjyQXG1mcO9w:b-ubmnhm) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b7867dc4ada733adb3540127d5011dc5edd463/tests/estimators/thrust_gain_estimator_tests.cpp#L60)):*
> ```cpp
>   ASSERT_NEAR(thrust_gain_estimator.processSensorThrustPair(
>                   M_PI / 2.0, 0, body_z_acc, thrust_command),
>               0.16, 1e-8);
> ```

use thrust_gain instead of 0.16

---

*[tests/estimators/thrust_gain_estimator_tests.cpp, line 63 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dsb8kLpmqHY7SwPip:-L-Dsb8kLpmqHY7SwPiq:bnj7hl0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b7867dc4ada733adb3540127d5011dc5edd463/tests/estimators/thrust_gain_estimator_tests.cpp#L63)):*
> ```cpp
>   ASSERT_NEAR(thrust_gain_estimator.processSensorThrustPair(
>                   0, M_PI / 2.0, body_z_acc, thrust_command),
>               0.16, 1e-8);
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149)*

**Comment by garimellagowtham** [comment]
Review status: 3 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dpw7S68_ix6FDSxRa:-L-E64A2wa2YWIra3Ix-:b32vmt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L88)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

note that the estimator takes into account delay between thrust and acceleration measurements by using a buffer
</blockquote></details>

??

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 100 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DnQq-Da4_yhTJ921w:-L-E629WrDYqPrwDLvCO:bxaexye) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L100)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

is this only used internally?  If so make private
</blockquote></details>

I use it in tests

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 112 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dq29oTKAHaJqtbQla:-L-E6V6bD8nA3yGAkqp3:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L112)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

maybe call this delay buffer just to clarify?
</blockquote></details>

Done

---

*[proto/thrust_gain_estimator_config.proto, line 16 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DneS7uyPEtQBEw9Bm:-L-E6ZtRjFxsd81OdjvX:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/proto/thrust_gain_estimator_config.proto#L16)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

has to be between 0 and 1
</blockquote></details>

Done

---

*[proto/thrust_gain_estimator_config.proto, line 20 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DnlMu1rYNx9nh7qLr:-L-E77C-lUA1Y2m0EI7s:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/proto/thrust_gain_estimator_config.proto#L20)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

fix doc
</blockquote></details>

Done

---

*[src/estimators/thrust_gain_estimator.cpp, line 62 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DsAPmScXVblrHRl5E:-L-E78BeYRJVF7aLZdHK:b-wv4j1q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b7867dc4ada733adb3540127d5011dc5edd463/src/estimators/thrust_gain_estimator.cpp#L62)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

check thrust is positive
</blockquote></details>

I check for that in the computation of expected thrust gain. I have min thrust tolerance which is pretty small like 1e-2 or something.

---

*[tests/estimators/thrust_gain_estimator_tests.cpp, line 60 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-DsZWInjyQXG1mcO9v:-L-E7RLenP35mJBpVLLM:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b7867dc4ada733adb3540127d5011dc5edd463/tests/estimators/thrust_gain_estimator_tests.cpp#L60)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

use thrust_gain instead of 0.16
</blockquote></details>

Done

---

*[tests/estimators/thrust_gain_estimator_tests.cpp, line 63 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dsb8kLpmqHY7SwPip:-L-E7W0DZOkJ20bHfZU4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/06b7867dc4ada733adb3540127d5011dc5edd463/tests/estimators/thrust_gain_estimator_tests.cpp#L63)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149)*

**Comment by garimellagowtham** [comment]
Review status: 3 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 88 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149#-L-Dpw7S68_ix6FDSxRa:-L-E8lEvaRsoI-McldqE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/5775aade8b433a74a081be3c81a20316bd5f50bc/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L88)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149)*

**Comment by msheckells** [comment]
Reviewed 10 of 10 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/149)*

**Pull request merged**
