### PR TITLE
Create a state machine for basic events

### PR DESCRIPTION
**Pull request by garimellagowtham**
A simple state machine that can takeoff, land, go to a position goal.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/9)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/state_machines/basic_state_machine.h, line 33 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiNwzsYcMtIgpnrEb4:-KdiNwztZaGo9P8Nal0h:b-wfjtl9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/basic_state_machine.h#L33)):*
> ```objc
> 
> // Robot System used
> #include <aerial_autonomy/robot_systems/quadrotor_system.h>
> ```

now uav_system

---

*[include/aerial_autonomy/state_machines/basic_state_machine.h, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiO-dO3OofJvkgihGw:-KdiO-dO3OofJvkgihGx:b-hmpa30) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/basic_state_machine.h#L56)):*
> ```objc
> 
> protected:
>   QuadRotorSystem &robot_system_;
> ```

UAVSystem

---

*[include/aerial_autonomy/state_machines/basic_state_machine.h, line 67 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiNz8chm8bDiSZSLpq:-KdiNz8chm8bDiSZSLpr:b-hmpa30) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/basic_state_machine.h#L67)):*
> ```objc
> 
>   // Constructor with arguments to store robot system
>   LogicStateMachineFrontEnd(QuadRotorSystem &quadrotor_system)
> ```

UAVSystem

---

*[include/aerial_autonomy/state_machines/state_machine_gui_connector.h, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiOMZ-TQv0jJyd3bTz:-KdiOMZ-TQv0jJyd3bU-:b7cndl1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/state_machine_gui_connector.h#L5)):*
> ```objc
> #include <std_msgs/String.h>
> 
> template <EventManagerT> class StatemMachineGUIConnector {
> ```

looks like a typo. should be StateMachineGUIConnector

---

*[include/aerial_autonomy/state_machines/state_machine_gui_connector.h, line 14 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiOp-iDCTUfVPre8R6:-KdiOp-iDCTUfVPre8R7:blakb4n) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/state_machine_gui_connector.h#L14)):*
> ```objc
>     event_manager_.triggerEvent(event_data->data);
>   }
>   EventManagerT &event_manager_;
> ```

If I remember correctly, we also wanted to use this class for receiving ROS messages to trigger events from other sources (like rviz).  I guess we can add that functionality in a future PR.

---

*[tests/state_machines/basic_state_machine_tests.cpp, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiOceCZkM_d9DZFj73:-KdiOceCZkM_d9DZFj74:ba6r89j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/tests/state_machines/basic_state_machine_tests.cpp#L5)):*
> ```cpp
> #include <ros/ros.h>
> 
> class TestQuad : public parsernode::Parser {
> ```

There is already a SampleParser class for testing in includes/aerial_autonomy/tests.  Should probably edit and use that instead.

---

*[tests/state_machines/basic_state_machine_tests.cpp, line 67 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiPsIoNbPaLIy0hQle:-KdiPsIoNbPaLIy0hQlf:bj9rccz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/tests/state_machines/basic_state_machine_tests.cpp#L67)):*
> ```cpp
>   // Check if we end up in right state
>   // Print state
>   pstate(logic_state_machine);
> ```

We can get the quadstate from the quad_system to assert that the appropriate state is set

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by msheckells** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by msheckells** [comment]
Reviewed 13 of 13 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 27 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdnKoPqsG1RpuaoV_R5:-KdnKoPqsG1RpuaoV_R6:b-6q0nre) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b165e05560a56f9ec558ebacbcfe2c679c789c55/include/aerial_autonomy/actions_guards/land_functors.h#L27)):*
> ```objc
>            LogicStateMachineT &logic_state_machine) {
>     parsernode::common::quaddata data = robot_system.getUAVData();
>     std::cout << data.altitude << std::endl;
> ```

Remove print

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by garimellagowtham** [comment]
Review status: 8 of 20 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/actions_guards/land_functors.h, line 27 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdnKoPqsG1RpuaoV_R5:-KdoM0Y4e6ynFys7Cr4H:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b165e05560a56f9ec558ebacbcfe2c679c789c55/include/aerial_autonomy/actions_guards/land_functors.h#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Remove print
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/basic_state_machine.h, line 33 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiNwzsYcMtIgpnrEb4:-KdoM3DVC4S86HDwOmfZ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/basic_state_machine.h#L33)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

now uav_system
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/basic_state_machine.h, line 56 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiO-dO3OofJvkgihGw:-KdoM44a49mcs5IDGPGU:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/basic_state_machine.h#L56)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

UAVSystem
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/basic_state_machine.h, line 67 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiNz8chm8bDiSZSLpq:-KdoM4kzKettYYVS442B:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/basic_state_machine.h#L67)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

UAVSystem
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/state_machine_gui_connector.h, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiOMZ-TQv0jJyd3bTz:-KdoMbHCqhNzii4PoWcm:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/state_machine_gui_connector.h#L5)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

looks like a typo. should be StateMachineGUIConnector
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/state_machine_gui_connector.h, line 14 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiOp-iDCTUfVPre8R6:-KdoMd1KHzQAis49GpXP:b-ba7jcz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/include/aerial_autonomy/state_machines/state_machine_gui_connector.h#L14)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

If I remember correctly, we also wanted to use this class for receiving ROS messages to trigger events from other sources (like rviz).  I guess we can add that functionality in a future PR.
</blockquote></details>

Sounds good to me.

---

*[tests/state_machines/basic_state_machine_tests.cpp, line 5 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiOceCZkM_d9DZFj73:-KdoMgvHCtY6CQph3Vaf:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/tests/state_machines/basic_state_machine_tests.cpp#L5)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

There is already a SampleParser class for testing in includes/aerial_autonomy/tests.  Should probably edit and use that instead.
</blockquote></details>

Done.

---

*[tests/state_machines/basic_state_machine_tests.cpp, line 67 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdiPsIoNbPaLIy0hQle:-KdoMrORJWc4v3WVHy09:b-48ksa4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0855c012421d964741763014f4b78ac79d852ddf/tests/state_machines/basic_state_machine_tests.cpp#L67)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We can get the quadstate from the quad_system to assert that the appropriate state is set
</blockquote></details>

Done. The new tests are much better and cover more scenarios.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by msheckells** [comment]
Reviewed 11 of 12 files at r4.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 82 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdqLYt0CaEp8Bq6YrXF:-KdqLYt0CaEp8Bq6YrXG:bnx6cj8) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/984a669bc865a774852d35ee88a4288af6b4bfeb/include/aerial_autonomy/actions_guards/base_functors.h#L82)):*
> ```objc
>   virtual ~GuardFunctor() {}
> };
> ```

It would be good to have a comment explaining the use of this class.  I'm assuming it's a base class for action functors that don't need to access the event struct that triggered the associated state

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by msheckells** [comment]
Reviewed 1 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by garimellagowtham** [comment]
Review status: 12 of 36 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[include/aerial_autonomy/actions_guards/base_functors.h, line 82 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9#-KdqLYt0CaEp8Bq6YrXF:-KdvNpWX0_F5UU2j9bNy:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/984a669bc865a774852d35ee88a4288af6b4bfeb/include/aerial_autonomy/actions_guards/base_functors.h#L82)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

It would be good to have a comment explaining the use of this class.  I'm assuming it's a base class for action functors that don't need to access the event struct that triggered the associated state
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/9)*

**Pull request merged**
