### PR TITLE
Add velocity controller state and commands from GUI

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/103)

### CODE REVIEW

**Comment by msheckells** [comment]
On compile missing file "tests/state_machines/state_machine_gui_connector_velocity_tests.test"

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/velocity_control_functors.h, line 38 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8lz5XLsQrnMaqppSF:-Kt8lz5XLsQrnMaqppSG:bl6z532) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/include/aerial_autonomy/actions_guards/velocity_control_functors.h#L38)):*
> ```objc
>     : GuardFunctor<VelocityYaw, UAVSystem, LogicStateMachineT> {
>   bool guard(const VelocityYaw &goal, UAVSystem &robot_system) {
>     parsernode::common::quaddata data = robot_system.getUAVData();
> ```

unused variable?

---

*[msg/VelocityYaw.msg, line 5 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8oNgxcagaZZkiDewO:-Kt8oNgxcagaZZkiDewP:b3kt0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/msg/VelocityYaw.msg#L5)):*
> ```
> 
> float64 vx  # Velocity in x direction
> float64 vy  # Velocity in x direction
> ```

y

---

*[msg/VelocityYaw.msg, line 6 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8oODhoCHnw1jOTSyz:-Kt8oODhoCHnw1jOTSz-:b3kt1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/msg/VelocityYaw.msg#L6)):*
> ```
> float64 vx  # Velocity in x direction
> float64 vy  # Velocity in x direction
> float64 vz  # Velocity in x direction
> ```

z

---

*[tests/actions_guards/uav_basic_functor_tests.cpp, line 448 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8ttuU02bQCKHGHFYx:-Kt8ttuVouCNjuqVqQfj:b-slt3rk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/tests/actions_guards/uav_basic_functor_tests.cpp#L448)):*
> ```cpp
>   uav_control_abort_action_functor(be::Abort(), sample_logic_state_machine,
>                                    dummy_start_state, dummy_target_state);
>   // Since the controller is aborted, will not run the controller
> ```

can you check if controller is not engaged?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-:-Kt8vcPx-AwmLbe2PVny:bkibfpf)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103)*

**Comment by msheckells** [comment]
Getting build error
`/home/matt/catkin_ws/src/aerial_autonomy/src/tests/event_publish_node.cpp:1:41: fatal error: aerial_autonomy/VelocityYaw.h: No such file or directory
 #include <aerial_autonomy/VelocityYaw.h>`

Need to add message as dependency.

---

Review status: 33 of 36 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-:-KtD6IDC01Q4Lvihg8CP:b7zu0ds)*

**Comment by msheckells** [comment]
The labels and sliders in the new tab have a lot of space in between them?  Is there an easy way to make them closer together?

---

Reviewed 3 of 3 files at r5.
Review status: 35 of 36 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 135 at r6](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-KtDAvvvS0fkGLdyjLhs:-KtDAvvvS0fkGLdyjLht:b5w56z0) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9954e4273c8679c23886741bed650d758626f79d/src/aerial_autonomy/aerial_autonomy_gui.py#L135)):*
> ```Python
>         self.velocity_command_labels = []
>         self._additional_commands_layout.addWidget(
>             QLabel('velocity Command (m/s), Yaw (deg)'))
> ```

capitalize Velocity

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 153 at r6](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-KtDAfLJ38BShUHVNpYN:-KtDAfLKAHHMmGQvUo5k:bi6v3zu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9954e4273c8679c23886741bed650d758626f79d/src/aerial_autonomy/aerial_autonomy_gui.py#L153)):*
> ```Python
>             # label to display velocity command from rviz to user
>             self.velocity_command_labels.append(
>                 QLabel("v{0}: {1:.2f}".format(
> ```

Can this be vx, vy, vz instead of v0, v1, v2?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-:-KtDB9Lm487ji4AJU2J8:b2gl6jq)*

**Comment by garimellagowtham** [comment]
Review status: 35 of 36 files reviewed at latest revision, 6 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/velocity_control_functors.h, line 38 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8lz5XLsQrnMaqppSF:-KtDE5IxynOwIaHUAhLu:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/include/aerial_autonomy/actions_guards/velocity_control_functors.h#L38)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

unused variable?
</blockquote></details>

Done.

---

*[msg/VelocityYaw.msg, line 5 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8oNgxcagaZZkiDewO:-KtDE3WI4cFiRv7ws4Xi:bb6un1j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/msg/VelocityYaw.msg#L5)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

y
</blockquote></details>

Done

---

*[msg/VelocityYaw.msg, line 6 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8oODhoCHnw1jOTSyz:-KtDE4dvqNyZgl1wvmWO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/msg/VelocityYaw.msg#L6)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

z
</blockquote></details>

Done.

---

*[tests/actions_guards/uav_basic_functor_tests.cpp, line 448 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103#-Kt8ttuU02bQCKHGHFYx:-KtDECuXCM8W9opHUlD2:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d7eb3a2b2e216f864bb77e8107804a88ceaed439/tests/actions_guards/uav_basic_functor_tests.cpp#L448)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

can you check if controller is not engaged?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/103)*

**Pull request merged**
