### PR TITLE
Visual servoing arm state machine

### PR DESCRIPTION
**Pull request by garimellagowtham**
Added state machine, necessary functors for pick-place.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/64)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 2 of 3 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 2 of 3 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 26 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAdZuzTWQVTmtE2Fk2:-KnAdZuzTWQVTmtE2Fk3:b-ba8221) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/actions_guards/pick_place_functors.h#L26)):*
> ```objc
>     robot_system.abortController(HardwareType::UAV);
>     robot_system.abortController(HardwareType::Arm);
>     ///\todo Add code to pick an object
> ```

Why abort both controllers while gripping?  Wouldn't we do that after the object is gripped?

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 121 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAhS2xIE32wVYab8z3:-KnAhS2xIE32wVYab8z4:b-ip0qf4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L121)):*
> ```objc
>                       psa::TakeoffAction, psa::TakeoffGuard>,
>             //        +--------------+-------------+--------------+---------------------+---------------------------+
>             msmf::Row<psa::ArmFolding, be::Abort, psa::Landed, psa::ArmPoweroff,
> ```

What happens if we are in ArmFolding while flying and then it gets aborted?  Will it enter Landed?  If so, that does not seem correct.  Might need a separate ArmFoldingLanded and ArmFoldingHovering state.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 146 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAi-3vjWxTrJNsGNXr:-KnAi-3vjWxTrJNsGNXs:b-vbqh6z) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L146)):*
> ```objc
>                       psa::LandingAction, msmf::none>,
>             //        +--------------+-------------+--------------+---------------------+---------------------------+
>             msmf::Row<psa::ArmFolding, be::Abort, psa::Landing,
> ```

As mentioned in above comment, there are currently two transitions defined for ArmFolding and Abort, which might mess things up

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64)*

**Comment by garimellagowtham** [comment]
Review status: 16 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 26 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAdZuzTWQVTmtE2Fk2:-KnH-0HfpOpGKGgvCkQ1:b-5timmg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/actions_guards/pick_place_functors.h#L26)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Why abort both controllers while gripping?  Wouldn't we do that after the object is gripped?
</blockquote></details>

I am just afraid UAV may go crazy when the arm is blocking the object and tracking goes bad.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 121 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAhS2xIE32wVYab8z3:-KnHIC2ELV0Wc1Y03jgf:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L121)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

What happens if we are in ArmFolding while flying and then it gets aborted?  Will it enter Landed?  If so, that does not seem correct.  Might need a separate ArmFoldingLanded and ArmFoldingHovering state.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 146 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAi-3vjWxTrJNsGNXr:-KnHIErAnntS0MhGvL16:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L146)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

As mentioned in above comment, there are currently two transitions defined for ArmFolding and Abort, which might mess things up
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64)*

**Comment by msheckells** [comment]
*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 26 at r7](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64#-KnAdZuzTWQVTmtE2Fk2:-KnLcS8aH3S-lxgI0r7n:b-krd42) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/b27b18076f11b1c1244d3891d622c6f0484c541b/include/aerial_autonomy/actions_guards/pick_place_functors.h#L26)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I am just afraid UAV may go crazy when the arm is blocking the object and tracking goes bad.
</blockquote></details>

It could still go crazy for that reason before this action is called.  I think this is fine for now though.  It will have to change if we want feedback on the gripper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64)*

**Comment by msheckells** [comment]
Reviewed 3 of 3 files at r8.
Review status: 19 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/64)*

**Pull request merged**
