### PR TITLE
Add manual rpyt mode

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/170)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/actions_guards/manual_control_functors.h, line 124 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170#-L96dsna2FjquVomwaKP:-L96dsna2FjquVomwaKQ:bbj5vhr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/45893624b386ab634b6ddd951a3361933078f6f8/include/aerial_autonomy/actions_guards/manual_control_functors.h#L124)):*
> ```objc
> 
> /**
> * @brief State that uses velocity control functor to track commanded velocity
> ```

not tracking commanded velocity, just rpyt

---

*[param/mocap_log_config.pbtxt, line 1 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170#-L96h3iN9niSKPTsxtb7:-L96h3iPBlSqQvDrFIo3:b-86uwbc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/45893624b386ab634b6ddd951a3361933078f6f8/param/mocap_log_config.pbtxt#L1)):*
> ```
> # This file is automatically generated! Make changes to log_config.pbtxt.in
> ```

Are you generating this manually? This does not have config for mocap_logger

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170)*

**Comment by garimellagowtham** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/manual_control_functors.h, line 124 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170#-L96dsna2FjquVomwaKP:-L96oLGL5GYUQG02eiv5:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/45893624b386ab634b6ddd951a3361933078f6f8/include/aerial_autonomy/actions_guards/manual_control_functors.h#L124)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

not tracking commanded velocity, just rpyt
</blockquote></details>

Done.

---

*[param/mocap_log_config.pbtxt, line 1 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170#-L96h3iN9niSKPTsxtb7:-L96q40h5sdndaruedgP:bo8ufoh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/45893624b386ab634b6ddd951a3361933078f6f8/param/mocap_log_config.pbtxt#L1)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Are you generating this manually? This does not have config for mocap_logger
</blockquote></details>

Removed file

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170)*

**Comment by msheckells** [comment]
Reviewed 1 of 2 files at r2.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170)*

**Comment by msheckells** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/170)*

**Pull request merged**
