### PR TITLE
Pick place with multiple destinations

### PR DESCRIPTION
**Pull request by msheckells**
ObjectId message now stores the ID of the picked object.  This is passed to the place state, where the object id is mapped to a destination id based on the state machine config.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/163)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 11 of 16 files at r1.
Review status: 11 of 16 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 388 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-d3FMxpnRONdj7rBYh:-L-d3FMxpnRONdj7rBYi:bh8cgoy) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/actions_guards/pick_place_functors.h#L388)):*
> ```objc
> template <class LogicStateMachineT, int StartIndex, int EndIndex>
> struct ReachingPostPickWaypoint_
>     : public FollowingWaypointSequence_<LogicStateMachineT, StartIndex,
> ```

Use typedef instead of full definition.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 186 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-gTxoCJ7i7zNQvTfnW:-L-gTxoCJ7i7zNQvTfnX:b-qzfszw) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L186)):*
> ```objc
>   using ReachingPostPickWaypoint =
>       ReachingPostPickWaypoint_<LogicStateMachineT, 0, 0>;
>   using ReachingPostPickWaypointBase =
> ```

Add doc

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 90 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-gU3Aw4kK4n91Dsrkz:-L-gU3Aw4kK4n91Dsrl-:b-7pu24g) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L90)):*
> ```objc
> 
> /**
> * @brief Action for initializing relative pose visual servoing for specific
> ```

guard

---

*[include/aerial_autonomy/types/object_id.h, line 4 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-d-vxqsR0siWp61dN6:-L-d-vxqsR0siWp61dN7:b-oqajdu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/types/object_id.h#L4)):*
> ```objc
> 
> struct ObjectId {
>   ObjectId(uint32_t id_) : id(id_) {}
> ```

You can add a default value for id_ = 0 and remove the other constructor.

---

*[include/aerial_autonomy/types/object_id.h, line 6 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-d-q-cguCpUqKbHG40:-L-d-q-cguCpUqKbHG41:bcbniyg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/types/object_id.h#L6)):*
> ```objc
>   ObjectId(uint32_t id_) : id(id_) {}
>   ObjectId() : ObjectId(0) {}
>   uint32_t id = 0;
> ```

You don't need to initialize id again here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163)*

**Comment by garimellagowtham** [comment]
Reviewed 5 of 16 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 111 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-g_63eB51cYZW4Nb0k:-L-g_63fgcblMxo8fGRb:bvmhmtc) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L111)):*
> ```objc
>       : BaseStateMachine(uav_system, state_machine_config) {
>     auto pick_state_machine_config =
>         state_machine_config.visual_servoing_state_machine_config()
> ```

Add basic logic explanation as in how does the state machine progress from hovering - > pick -> reaching -> place in A/B back to -> pick.

---

*[proto/grip_config.proto, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-gZpPwnqKsAiMenmIk:-L-gZpPwnqKsAiMenmIl:b3krh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/proto/grip_config.proto#L17)):*
> ```protobuf
>   repeated uint32 group_a_ids = 3;
>   /**
>   * @brief List of item IDs in group A
> ```

B

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163)*

**Comment by msheckells** [comment]
Review status: 11 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 388 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-d3FMxpnRONdj7rBYh:-L-gdUMU8mAOmGSQbdCx:b-apc9ai) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/actions_guards/pick_place_functors.h#L388)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Use typedef instead of full definition.
</blockquote></details>

Actually, I don't think we need to do that.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 186 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-gTxoCJ7i7zNQvTfnW:-L-gddLyAyR5ii7nMvZs:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L186)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add doc
</blockquote></details>

Done.

---

*[include/aerial_autonomy/actions_guards/visual_servoing_functors.h, line 90 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-gU3Aw4kK4n91Dsrkz:-L-geyPOQwW7Tcf56PMi:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/actions_guards/visual_servoing_functors.h#L90)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

guard
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 111 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-g_63eB51cYZW4Nb0k:-L-ghZ7eEp9cqL0F1dgR:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L111)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add basic logic explanation as in how does the state machine progress from hovering - > pick -> reaching -> place in A/B back to -> pick.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/types/object_id.h, line 4 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-d-vxqsR0siWp61dN6:-L-gf3vMjl1iUoaAAupo:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/types/object_id.h#L4)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

You can add a default value for id_ = 0 and remove the other constructor.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/types/object_id.h, line 6 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-d-q-cguCpUqKbHG40:-L-gf69QpvrKIjZ5c-6K:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/include/aerial_autonomy/types/object_id.h#L6)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

You don't need to initialize id again here.
</blockquote></details>

Done.

---

*[proto/grip_config.proto, line 17 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163#-L-gZpPwnqKsAiMenmIk:-L-gfBd0_bCxCK6_QOCI:ba3dfob) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bc4146d28efd0006a30081974a6e75a5ea5466ff/proto/grip_config.proto#L17)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

B
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163)*

**Comment by garimellagowtham** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/163)*

**Pull request merged**
