### PR TITLE
Sync icra changes

### PR DESCRIPTION
**Pull request by msheckells**
I've updated the tests so that they pass and are valid with respect to the current state machine.  First, we can merge all the changes I've made into repeat-pick-place (the branch that has the full pick-place logic loop).  Then, we can merge repeat-pick-place into master without review since we've reviewed the changes as they went into repeat-pick-place.   From there, we can make more changes to "un-hack" some of our icra modifications.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/123)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 1 of 6 files at r3, 29 of 29 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 143 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-Kv2kd8PELQB5WUCJj3q:-Kv2kd8PELQB5WUCJj3r:bob47a7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/pick_place_functors.h#L143)):*
> ```objc
>   bool run(UAVArmSystem &robot_system, LogicStateMachineT &logic_state_machine,
>            WaitingForPick_<LogicStateMachineT> &state) {
>     logic_state_machine.process_event(pick_place_events::Pick());
> ```

I am not sure if we want some logic here for checking the object to pick is within workspace or not and if any object is available to pick at all? If no object is available, this state should abort and go back to hovering. The way it is setup now, the user has to press abort which is not good.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 129 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-Kv2lomGyQG0xBuQD5FU:-Kv2lomGyQG0xBuQD5FV:br8jck9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L129)):*
> ```objc
> 
>   /**
>   * @brief Check tracking is valid and arm is enabled for pre-pick
> ```

There is no pre-pick.

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 75 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTlhVsS1NUade8FEQg:-KvTlhVsS1NUade8FEQh:b-s4zyn7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/position_control_functors.h#L75)):*
> ```objc
>     parsernode::common::quaddata data = robot_system.getUAVData();
>     geometry_msgs::Vector3 current_vel = data.linvel;
>     const double tolerance_vel = .03;
> ```

I don't think this needs to be changed.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 44 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTlt50mj28Aqh_LJEb:-KvTlt51soGx-4-36VMT:b-d3lbm1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L44)):*
> ```objc
>         // same for all tracked objects
>         tracking_offset_transform_(tracking_offset_transform),
>         use_explicit_id_(false) {}
> ```

Are we adding the explicit ID hack? I thought we are supposed to use different switchable tracking strategies!

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 167 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTpultRTSV47aTCgeH:-KvTpultRTSV47aTCgeI:b-4jtv3q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L167)):*
> ```
>         yaw: 3.141
>       }
>       way_points {
> ```

Waypoints are for repeat pick-place

---

*[proto/pose_controller_config.proto, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTqA8DRuh5KsWNh5lE:-KvTqA8DRuh5KsWNh5lF:b-uc5pfg) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/proto/pose_controller_config.proto#L16)):*
> ```protobuf
>   * the goal is reached.
>   */
>   required double goal_rotation_tolerance = 2 [ default = 0.1 ];
> ```

If it is required, I do not know how the default value will work? Same for other places too.

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 60 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTr2YyLRggZlCSNVHH:-KvTr2YyLRggZlCSNVHI:b-gwksfl) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/actions_guards/pick_place_functor_tests.cpp#L60)):*
> ```cpp
>     uav_arm_system_config->add_arm_transform(0);
>     uav_arm_system_config->add_arm_transform(0);
>     // Arm goal transform xyz(-0.2,0,0), rpy(0,0,0):
> ```

Wrong number -0.2. Can just say xyz, rpy

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 175 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTt1BRPlfCHgQb7Xp6:-KvTt1BRPlfCHgQb7Xp7:b-l6mwxj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/actions_guards/pick_place_functor_tests.cpp#L175)):*
> ```cpp
>   uav_arm_system->power(true);
> 
>   // \todo Test gripping internal action
> ```

remove

---

*[tests/actions_guards/uav_basic_functor_tests.cpp, line 237 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTtgK_mvjEtPN1oQKr:-KvTtgKatsTQo_Y5CmyW:b-j1lzbv) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b5fc27885722433d95b21cc337ed48b0c1e4286/tests/actions_guards/uav_basic_functor_tests.cpp#L237)):*
> ```cpp
>       uav_system.getGoal<PositionControllerDroneConnector, PositionYaw>();
>   ASSERT_EQ(goal, resulting_goal);
>   uav_system.runActiveController(HardwareType::UAV);
> ```

We still need to run the controller and check the UAV is reaching the resulting goal right?

---

*[tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp, line 31 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTuW9EcivyCBET7R07:-KvTuW9EcivyCBET7R08:b56vw4u) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp#L31)):*
> ```cpp
>     auto position_controller_config =
>         config.mutable_velocity_based_position_controller_config();
>     position_controller_config->set_position_gain(30.0);
> ```

Why are these gains so big??

---

*[tests/controllers/velocity_based_position_controller_tests.cpp, line 17 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTvHROgS8SVUDePCf6:-KvTvHROgS8SVUDePCf7:b-ii8bqo) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/controllers/velocity_based_position_controller_tests.cpp#L17)):*
> ```cpp
>   PositionYaw sensor_data(0, 0, 0, 0);
>   PositionYaw goal(1, -1, 0.5, 0.1);
>   controller.setGoal(goal, false);
> ```

We probably can reset integrator (second argument) and maybe even remove the reset integrator.

---

*[tests/state_machines/pick_place_state_machine_tests.cpp, line 62 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTvv-M0Tr0ETSF42GC:-KvTvv-NCCYCKzuQgNOY:bp5ql5x) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/state_machines/pick_place_state_machine_tests.cpp#L62)):*
> ```cpp
>     auto pos_controller_config =
>         config_.mutable_velocity_based_position_controller_config();
>     pos_controller_config->set_position_gain(10.);
> ```

Maybe reduce the gains a little bit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Comment by msheckells** [comment]
Review status: 24 of 28 files reviewed at latest revision, 12 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 143 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-Kv2kd8PELQB5WUCJj3q:-KvX_cHob4EAOkKCj4aC:b-a90qr3) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/pick_place_functors.h#L143)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I am not sure if we want some logic here for checking the object to pick is within workspace or not and if any object is available to pick at all? If no object is available, this state should abort and go back to hovering. The way it is setup now, the user has to press abort which is not good.
</blockquote></details>

We have it setup so that the guard checks if the object is available to pick.  It only actually transitions to pick when the object is there.  We could also have the guard check if the object is in the workspace 

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 129 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-Kv2lomGyQG0xBuQD5FU:-KvXa9-nXVnwEOOQ64a4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L129)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

There is no pre-pick.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h, line 44 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTlt50mj28Aqh_LJEb:-KvXaKY-CmBxCIZWpVia:b-x5bznf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/controller_hardware_connectors/relative_pose_visual_servoing_controller_drone_connector.h#L44)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Are we adding the explicit ID hack? I thought we are supposed to use different switchable tracking strategies!
</blockquote></details>

For now I am keeping the hack.  This PR is just meant to update the tests, to get the tests to pass ,and to clean up some of the old pick/place state machine stuff.  If I fix the tracking stuff in this branch, the PR will be even more massive.  I'll do it in a different PR.  However, we can fix the tracking stuff before we merge everything to master if that makes sense

---

*[param/matrice_pick_place_alvar_pointgrey_config.pbtxt, line 167 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTpultRTSV47aTCgeH:-KvXdEgu1fmAndeRkXaX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/param/matrice_pick_place_alvar_pointgrey_config.pbtxt#L167)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Waypoints are for repeat pick-place
</blockquote></details>

Done.

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 60 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTr2YyLRggZlCSNVHH:-KvXeI7UHk1Oj0b4BxqH:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/actions_guards/pick_place_functor_tests.cpp#L60)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Wrong number -0.2. Can just say xyz, rpy
</blockquote></details>

Done.

---

*[tests/actions_guards/pick_place_functor_tests.cpp, line 175 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTt1BRPlfCHgQb7Xp6:-KvXeSDgPMy0DkrWS9AS:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/actions_guards/pick_place_functor_tests.cpp#L175)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

---

*[tests/actions_guards/uav_basic_functor_tests.cpp, line 237 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTtgK_mvjEtPN1oQKr:-KvXkYIAp6-aXIEzwIZm:by6fhop) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/9b5fc27885722433d95b21cc337ed48b0c1e4286/tests/actions_guards/uav_basic_functor_tests.cpp#L237)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We still need to run the controller and check the UAV is reaching the resulting goal right?
</blockquote></details>

The controller tests already check whether the controller is able to reach a specified goal.  Testing it again here seems redundant.  The functor's job is simply to set the goal, so the test should just check whether the correct goal is set.

---

*[tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp, line 31 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTuW9EcivyCBET7R07:-KvXkxRu4rYyoEzc2fP_:bndx3ad) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/controller_hardware_connectors/relative_pose_visual_servoing_drone_connector_tests.cpp#L31)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why are these gains so big??
</blockquote></details>

It makes the tests go faster. I don't see a negative side-effect for having big gains here.

---

*[tests/controllers/velocity_based_position_controller_tests.cpp, line 17 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTvHROgS8SVUDePCf6:-KvXqhZqom5CKCaV3gH9:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/controllers/velocity_based_position_controller_tests.cpp#L17)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

We probably can reset integrator (second argument) and maybe even remove the reset integrator.
</blockquote></details>

Done.

---

*[tests/state_machines/pick_place_state_machine_tests.cpp, line 62 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTvv-M0Tr0ETSF42GC:-KvXqjqzMST0xk854rmK:br1uorr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/tests/state_machines/pick_place_state_machine_tests.cpp#L62)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Maybe reduce the gains a little bit?
</blockquote></details>

Why? It will just make the test run slower

---

*[include/aerial_autonomy/actions_guards/position_control_functors.h, line 75 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTlhVsS1NUade8FEQg:-KvXaErgzP9duXHkQk7r:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/position_control_functors.h#L75)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I don't think this needs to be changed.
</blockquote></details>

Done.

---

*[proto/pose_controller_config.proto, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTqA8DRuh5KsWNh5lE:-KvXdTwGZrrsMgKDk0pR:b2thir7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/proto/pose_controller_config.proto#L16)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

If it is required, I do not know how the default value will work? Same for other places too.
</blockquote></details>

I think I changed this when I was trying to fix another bug... I'll change it back.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Comment by garimellagowtham** [comment]
Reviewed 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 143 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-Kv2kd8PELQB5WUCJj3q:-KvYHMCZ8rbVL55UH924:b-ewi55c) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/pick_place_functors.h#L143)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

We have it setup so that the guard checks if the object is available to pick.  It only actually transitions to pick when the object is there.  We could also have the guard check if the object is in the workspace 
</blockquote></details>

Maybe add a todo about checking if the object is in the workspace. 

---

*[proto/pose_controller_config.proto, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTqA8DRuh5KsWNh5lE:-KvYH0x9ALswaFVd_Lcc:bjscykh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/proto/pose_controller_config.proto#L16)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

I think I changed this when I was trying to fix another bug... I'll change it back.
</blockquote></details>

There are other places where you changed optional to required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 143 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-Kv2kd8PELQB5WUCJj3q:-KvY_WyX5Z2oxvancgAr:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/include/aerial_autonomy/actions_guards/pick_place_functors.h#L143)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Maybe add a todo about checking if the object is in the workspace. 
</blockquote></details>

Done.

---

*[proto/pose_controller_config.proto, line 16 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvTqA8DRuh5KsWNh5lE:-KvY_Y0q2wn_u1nfbEfQ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/193511b275243353171f28759f3ae0396c0d9233/proto/pose_controller_config.proto#L16)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

There are other places where you changed optional to required
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 134 at r6](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvYgVdjfmua7oj9io3w:-KvYgVdkjwhJGN5nm0C1:bjnajf9) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7e3f1351f2955e060966a30bb919383eb9d71d9b/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L134)):*
> ```objc
>       bAnd<typename vsa::RelativePoseVisualServoingTransitionGuard,
>            ArmTrackingGuardFunctor_<LogicStateMachineT>>;
>   // \todo Check if tracked objetc is in workspace
> ```

tracked object :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 134 at r6](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123#-KvYgVdjfmua7oj9io3w:-KvYjJOHQFpfpE-nIcte:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/7e3f1351f2955e060966a30bb919383eb9d71d9b/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L134)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

tracked object :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/123)*

**Pull request merged**
