### PR TITLE
Add reset picking if visual servoing is lost or placing is complete

### PR DESCRIPTION
**Pull request by garimellagowtham**
The reset state checks for reached goal and tries to enter pick
again if reaching goal is complete

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/120)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 227 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/120#-Kty9P1YGwr198Y8Npyb:-Kty9P1YGwr198Y8Npyc:b56tj1f) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/601bbac4d344dcdffef6a3e31af03a33db479341/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L227)):*
> ```objc
>             //        +--------------+-------------+--------------+---------------------+---------------------------+
>             msmf::Row<psa::ReachingPostPlaceWaypoint, Completed,
>                       psa::ResetVisualServoing, msmf::none, msmf::none>,
> ```

still have to abort the arm and uav controller i think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/120)*

**Comment by garimellagowtham** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/state_machines/pick_place_state_machine.h, line 227 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/120#-Kty9P1YGwr198Y8Npyb:-KtyIbzeMDSiTlpxRLaZ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/601bbac4d344dcdffef6a3e31af03a33db479341/include/aerial_autonomy/state_machines/pick_place_state_machine.h#L227)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

still have to abort the arm and uav controller i think
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/120)*

**Comment by msheckells** [comment]
Reviewed 1 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/120)*

**Comment by msheckells** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/120)*

**Pull request merged**
