### PR TITLE
Create BuiltInPositionController

### PR DESCRIPTION
**Pull request by msheckells**
Creates a position controller that uses a drone parser's built-in waypoint commands.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/3)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[CMakeLists.txt, line 192 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUnV7QVJzpB_CSSgtJ:-KcUnV7QVJzpB_CSSgtK:b-y6bymk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2a786561f9bd8f5109ba0bf920e303dde35b3925/CMakeLists.txt#L192)):*
> ```CMake
> catkin_add_gtest(${PROJECT_NAME}-ctrlr-hrdwr-cnctr-test tests/controller_hardware_connectors/control_hardware_tests.cpp)
> catkin_add_gtest(${PROJECT_NAME}-pos-ctrlr-drone-cnctr-test tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp)
> target_link_libraries(${PROJECT_NAME}-pos-ctrlr-drone-cnctr-test aerial_autonomy)
> ```

Add target_link_libraries similar to the example below. The tests are not usually built when invoking regular catkin build. So no target will exist to target_link_libraries, I think.

---

*[CMakeLists.txt, line 145 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUqy-fCVp6z-iKBF8E:-KcUqy-fCVp6z-iKBF8F:b6zjhj1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/CMakeLists.txt#L145)):*
> ```CMake
> 
> ## Specify libraries to link a library or executable target against
> target_link_libraries(aerial_autonomy
> ```

This is not needed. We link catkin libraries to the executable anyway.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 18 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUrlsCsE5VTGjxlwwa:-KcUrlsD2TP7xhJweSv2:b-8nd0p) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/controllers/base_controller.h#L18)):*
> ```objc
>    */
>   virtual void setGoal(GoalType goal) {
>     goal_ = goal;
> ```

No internal locking between setGoal and run functions?

---

*[include/aerial_autonomy/controllers/builtin_position_controller.h, line 10 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV-Z4-n35a4sxTEgp6:-KcV-Z4-n35a4sxTEgp7:b-54ad21) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/controllers/builtin_position_controller.h#L10)):*
> ```objc
>  * @brief A position controller that simply outputs the set goal position
>  */
> class BuiltInPositionController : public Controller<NoSensor, PositionYaw, PositionYaw> {
> ```

Can we use `using NoSensor = std_msgs::Empty;` to not create the classes.

---

*[include/aerial_autonomy/types/no_sensor.h, line 2 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUpJZawkFi_sb8lj6d:-KcUpJZawkFi_sb8lj6e:ba9hre) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2a786561f9bd8f5109ba0bf920e303dde35b3925/include/aerial_autonomy/types/no_sensor.h#L2)):*
> ```objc
> #pragma once
> struct NoSensor {
> ```

May be call this EmptySensor

---

*[include/aerial_autonomy/types/position.h, line 2 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUrSIaLWWAiNtttxUq:-KcUrSIaLWWAiNtttxUr:bxk018a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/types/position.h#L2)):*
> ```objc
> #pragma once
> struct Position {
> ```

Can we use geometry_msgs/Position to avoid code duplication

---

*[src/controllers/builtin_position_controller.cpp, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV-z3ylAJnY6MVB-ud:-KcV-z3ylAJnY6MVB-ue:bh48q8c) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/src/controllers/builtin_position_controller.cpp#L3)):*
> ```cpp
> #include "aerial_autonomy/controllers/builtin_position_controller.h"
> 
> PositionYaw BuiltInPositionController::run(NoSensor sensor_data) {
> ```

If not using argument, can specify the function `(NoSensor)`

---

*[src/controllers/builtin_position_controller.cpp, line 4 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV03eQrjvl79OvQh10:-KcV03eQrjvl79OvQh11:bupwrrk) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/src/controllers/builtin_position_controller.cpp#L4)):*
> ```cpp
> 
> PositionYaw BuiltInPositionController::run(NoSensor sensor_data) {
>   return goal_;
> ```

You will need to lock this

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 57 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV13rvKhiAJJFU8jw9:-KcV13rvKhiAJJFU8jwA:b-y0xhg1) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L57)):*
> ```cpp
> /// \brief Test BuiltInPositionController
> TEST(PositionControllerDroneConnectorTests, Constructor) {
>   TestQuad tq;
> ```

test_quad

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 72 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV1HTefuZOSGkzk96I:-KcV1HTefuZOSGkzk96J:b-ppaebt) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L72)):*
> ```cpp
>   // Create controller and connector
>   BuiltInPositionController position_controller;
>   auto pos_controller_connector =
> ```

Why use a pointer?

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 73 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV1TJsoht6uM9fx0UF:-KcV1TJsoht6uM9fx0UG:bqlz828) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L73)):*
> ```cpp
>   BuiltInPositionController position_controller;
>   auto pos_controller_connector =
>       new PositionControllerDroneConnector(drone_hardware, position_controller);
> ```

Can you send tq directly as an argument why do we need drone_hardware?

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 77 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV1jbWfbFllwwRCGnB:-KcV1jbWfbFllwwRCGnC:b-o8y6ow) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L77)):*
> ```cpp
>   // Test set goal
>   PositionYaw goal(10, 10, 10, 0.1);
>   pos_controller_connector->setGoal(goal);
> ```

Assert goal is being set. May be need to add a getter to controller to get a const ref to goal. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by msheckells** [comment]
Review status: 12 of 14 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 192 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUnV7QVJzpB_CSSgtJ:-KcWHAIQGtodK3iwGyJO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2a786561f9bd8f5109ba0bf920e303dde35b3925/CMakeLists.txt#L192)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add target_link_libraries similar to the example below. The tests are not usually built when invoking regular catkin build. So no target will exist to target_link_libraries, I think.
</blockquote></details>

Done.

---

*[CMakeLists.txt, line 145 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUqy-fCVp6z-iKBF8E:-KcWH9-8bkW4rm13HX3I:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/CMakeLists.txt#L145)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This is not needed. We link catkin libraries to the executable anyway.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by msheckells** [comment]
Review status: 2 of 15 files reviewed at latest revision, 10 unresolved discussions.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 18 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUrlsCsE5VTGjxlwwa:-KcWQhkIDFtqeXKcR1gx:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/controllers/base_controller.h#L18)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

No internal locking between setGoal and run functions?
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/builtin_position_controller.h, line 10 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV-Z4-n35a4sxTEgp6:-KcWQl9MxQuQAGBx7-CR:b-gg4xwf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/controllers/builtin_position_controller.h#L10)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can we use `using NoSensor = std_msgs::Empty;` to not create the classes.
</blockquote></details>

For now I will leave it as EmptySensor, we should think about using new types vs existing types in more detail

---

*[include/aerial_autonomy/types/empty_sensor.h, line 2 at r2](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUpJZawkFi_sb8lj6d:-KcWQkO979fQ8Yt-w8ep:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2a786561f9bd8f5109ba0bf920e303dde35b3925/include/aerial_autonomy/types/empty_sensor.h#L2)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

May be call this EmptySensor
</blockquote></details>

Done.

---

*[include/aerial_autonomy/types/position.h, line 2 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUrSIaLWWAiNtttxUq:-KcWR-BejAeLzKIPptxv:b-c5s6xe) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/types/position.h#L2)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can we use geometry_msgs/Position to avoid code duplication
</blockquote></details>

leaving for now

---

*[src/controllers/builtin_position_controller.cpp, line 3 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV-z3ylAJnY6MVB-ud:-KcWR_QHPgBv7upzAXDX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/src/controllers/builtin_position_controller.cpp#L3)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

If not using argument, can specify the function `(NoSensor)`
</blockquote></details>

Done.

---

*[src/controllers/builtin_position_controller.cpp, line 4 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV03eQrjvl79OvQh10:-KcWR3gDtrO5goyh4PDv:bslmhnj) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/src/controllers/builtin_position_controller.cpp#L4)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

You will need to lock this
</blockquote></details>

Locking now done in base class run function.

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 57 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV13rvKhiAJJFU8jw9:-KcWR8zZ414AdFg4JPgX:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L57)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

test_quad
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 72 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV1HTefuZOSGkzk96I:-KcWR9ja6OB2Iht9Jp2J:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L72)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Why use a pointer?
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 73 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV1TJsoht6uM9fx0UF:-KcWRAijUp8WPe-5dcfO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L73)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can you send tq directly as an argument why do we need drone_hardware?
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 77 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcV1jbWfbFllwwRCGnB:-KcWRBf60ZQOR29FGAnA:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L77)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Assert goal is being set. May be need to add a getter to controller to get a const ref to goal. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 2 files at r4, 14 of 14 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 53 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWTlOPvxdK1eJpWzlw:-KcWTlOPvxdK1eJpWzlx:blx6zie) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/include/aerial_autonomy/controllers/base_controller.h#L53)):*
> ```objc
>    * @return Control values to send to hardware
>    */
>   virtual ControlType runImpl(SensorDataType sensor_data, GoalType goal) = 0;
> ```

Marin would like full names: `runImplicit` or something

---

*[include/aerial_autonomy/controllers/base_controller.h, line 56 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWXW2F0fmwbi1REAwi:-KcWXW2F0fmwbi1REAwj:b-4gpi9l) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/include/aerial_autonomy/controllers/base_controller.h#L56)):*
> ```objc
> 
> private:
>   boost::mutex goal_mutex;
> ```

goal_mutex_

---

*[include/aerial_autonomy/types/position.h, line 2 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcUrSIaLWWAiNtttxUq:-KcWU0L0-_i9aM9Axng2:bxctweq) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/eb4e11c7b458093b10264b62345981ed968675ae/include/aerial_autonomy/types/position.h#L2)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

leaving for now
</blockquote></details>

I think its ok to create our own types for now. I am not sure, but `protobufs` can also be used for these and thereby not depend on ROS.

For sensor data types we should also provide operations on the data so using existing types like Eigen vectors and matrices internal to the class will be usefuly. 

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 31 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWUNl3AY1NOSIm1nss:-KcWUNl3AY1NOSIm1nst:boqwrdz) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L31)):*
> ```cpp
>     return true;
>   }
>   virtual bool cmdwaypoint(geometry_msgs::Vector3 &desired_pos,
> ```

commandwaypoint

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 69 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWYIScxQdmHQhE2G73:-KcWYISdt9KFRCkL1Wif:b1tib4r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L69)):*
> ```cpp
>   // Create controller and connector
>   BuiltInPositionController position_controller;
>   PositionControllerDroneConnector pos_controller_connector(drone_hardware, position_controller);
> ```

position_controller_connector

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by msheckells** [comment]
Review status: 11 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 53 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWTlOPvxdK1eJpWzlw:-KcYtKCejGpKNVaSQjmD:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/include/aerial_autonomy/controllers/base_controller.h#L53)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Marin would like full names: `runImplicit` or something
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/base_controller.h, line 56 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWXW2F0fmwbi1REAwi:-KcYtKa6Fq_jgXwU7weR:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/include/aerial_autonomy/controllers/base_controller.h#L56)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

goal_mutex_
</blockquote></details>

Done.

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 31 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWUNl3AY1NOSIm1nss:-KcYtQtNJ8OYH_LqV7tg:bc08q8j) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L31)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

commandwaypoint
</blockquote></details>

Since this is a function overriding a pure virtual in Parser, I would have to change the code in Parser to fix this.  All of this would be fixed if/when we decide to update the parser code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by msheckells** [comment]
Review status: 10 of 17 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp, line 69 at r5](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-KcWYIScxQdmHQhE2G73:-KcYuDBqhzB6OVe_ztP4:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/4280d3e5abcbcd6bd9a1d574faae1e3c8aac68d1/tests/controller_hardware_connectors/position_controller_drone_connector_tests.cpp#L69)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

position_controller_connector
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 7 files at r6.
Review status: 11 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by garimellagowtham** [comment]
Reviewed 6 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3)*

**Comment by garimellagowtham** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/3#-:-KcYwIUfrUiFD58f7y11:bnfp4nl)*

**Pull request merged**
