### PR TITLE
Add pre pick position

### PR DESCRIPTION
**Pull request by msheckells**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/82)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
:lgtm:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 104 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Krm7XxStWAZwUfpf7aw:-Krm7XxTxW71rpSkfSJp:b5cyrh7) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/include/aerial_autonomy/actions_guards/pick_place_functors.h#L104)):*
> ```objc
>                              PickInternalActionFunctor_<LogicStateMachineT>>;
> 
> template <class LogicStateMachineT>
> ```

Add comment

---

*[include/aerial_autonomy/common/math.h, line 61 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Krm8gSP3ByBy2tTU76R:-Krm8gSP3ByBy2tTU76S:bawrwke) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/include/aerial_autonomy/common/math.h#L61)):*
> ```objc
> * @return vector of tf::Transform
> */
> template <class T> std::vector<tf::Transform> getTransformsFromVector(const T &input) {
> ```

Make it getTransformFromProto and do not use vectors

---

*[launch/matrice_pick_place_alvar.launch, line 37 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-KrmCMzc3eYBb5FEvAwj:-KrmCMzd28ppwCSK8dZ7:b-3ldcjr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/launch/matrice_pick_place_alvar.launch#L37)):*
> ```XML
>     <arg name="cam_info_topic"  value="/duo3d_camera/left/camera_info" />
>     <arg name="output_frame"    value="/duo3d_camera" />
>   </include>
> ```

Remove commented duo stuff

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-:-Krq-pflDCUVopfWegjW:bnfp4nl)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_functors.h, line 104 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Krm7XxStWAZwUfpf7aw:-Krxt5qxJlTM42mBX_R0:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/include/aerial_autonomy/actions_guards/pick_place_functors.h#L104)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.

---

*[include/aerial_autonomy/common/math.h, line 61 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Krm8gSP3ByBy2tTU76R:-KrxsZ3j5qBK3qrDrqXV:b6w1f27) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/include/aerial_autonomy/common/math.h#L61)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Make it getTransformFromProto and do not use vectors
</blockquote></details>

Are you saying don't make it templated? Only have it accept proto? Where should I not use vectors?

---

*[launch/matrice_pick_place_alvar.launch, line 37 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-KrmCMzc3eYBb5FEvAwj:-KrxtDpHy6OvVzRX3t4E:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/launch/matrice_pick_place_alvar.launch#L37)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Remove commented duo stuff
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82)*

**Comment by msheckells** [comment]
For some reason a bunch of files weren't passing the clang-format check on my computer.  Are we using different versions of clang-format?

---

Review status: 8 of 20 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-:-Krxvu3MpMpGaV68v8No:bc2yycl)*

**Comment by garimellagowtham** [comment]
I am also having that issue. I am using clang-format version 3.8.0-2ubuntu3~trusty4

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/common/math.h, line 61 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Krm8gSP3ByBy2tTU76R:-KrzaakohAAqR3SNrZLm:bbssdij) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/include/aerial_autonomy/common/math.h#L61)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Are you saying don't make it templated? Only have it accept proto? Where should I not use vectors?
</blockquote></details>

I am thinking of not using a template. We can get a vector of tf transforms from a vector of proto transforms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-:-KrzaPCKpMcV7mBq_VTz:bomqfut)*

**Comment by msheckells** [comment]
Review status: 19 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/common/math.h, line 61 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Krm8gSP3ByBy2tTU76R:-Ks4kqVpYF6GvWzMemWK:bj67okr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/bdb36c4df782862568f558d7a46953022c88388b/include/aerial_autonomy/common/math.h#L61)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

I am thinking of not using a template. We can get a vector of tf transforms from a vector of proto transforms.
</blockquote></details>

added todo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82)*

**Comment by garimellagowtham** [comment]
Reviewed 4 of 6 files at r5, 1 of 2 files at r7, 1 of 1 files at r8.
Review status: 24 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/controllers/constant_heading_depth_controller.h, line 7 at r8](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Ks4sUbw6ov1kBxKjEKy:-Ks4sUbxsDH6uydfCkbC:b-a9qpve) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f9639dd27fae6307c1ac3ca25081f8f0eaedf48d/include/aerial_autonomy/controllers/constant_heading_depth_controller.h#L7)):*
> ```objc
> #include "constant_heading_depth_controller_config.pb.h"
> #include <chrono>
> #include <ctime>
> ```

Are these headers needed. I don't see used in the cpp file changes

---

*[tests/common/math_tests.cpp, line 106 at r8](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Ks4rb-JfQBcKbTEV6dN:-Ks4rb-JfQBcKbTEV6dO:b-5asf5m) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f9639dd27fae6307c1ac3ca25081f8f0eaedf48d/tests/common/math_tests.cpp#L106)):*
> ```cpp
>     tf::Matrix3x3 input_basis;
>     input_basis.setEulerYPR(input[6*i+5], input[6*i+4], input[6*i+3]);
>     tf::Matrix3x3 expected_identity = input_basis.transpose() * out.getBasis();
> ```

It might be easier to just compare the matrices themselves. Like for (row, col ): input_basis[i, j] == out_basis[i, j];

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82)*

**Comment by msheckells** [comment]
Review status: 23 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/common/math_tests.cpp, line 106 at r8](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Ks4rb-JfQBcKbTEV6dN:-Ks4uuqDR93oftPcKZb3:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f9639dd27fae6307c1ac3ca25081f8f0eaedf48d/tests/common/math_tests.cpp#L106)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

It might be easier to just compare the matrices themselves. Like for (row, col ): input_basis[i, j] == out_basis[i, j];
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/constant_heading_depth_controller.h, line 7 at r8](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82#-Ks4sUbw6ov1kBxKjEKy:-Ks4tokouBikr40ZfVtZ:b8oea8y) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f9639dd27fae6307c1ac3ca25081f8f0eaedf48d/include/aerial_autonomy/controllers/constant_heading_depth_controller.h#L7)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Are these headers needed. I don't see used in the cpp file changes
</blockquote></details>

Done. They were there for the old logging (which I removed for this PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r9, 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/82)*

**Pull request merged**
