### PR TITLE
Add integrator to velocity based position controller

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/110)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/types/position_yaw.h, line 121 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtYDecYX-kGsxPR-Gy6:-KtYDecYX-kGsxPR-Gy7:b1rucgu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0b79d1fb2cd521db9b41a3cbc2572dbc521ce7ae/include/aerial_autonomy/types/position_yaw.h#L121)):*
> ```objc
>   */
>   PositionYaw operator*(const double &m) const {
>     return PositionYaw(this->x * m, this->y * m, this->z * m, this->yaw * m);
> ```

wrap yaw

---

*[src/controllers/velocity_based_position_controller.cpp, line 33 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtYEYmwFOfSu8_UUAwJ:-KtYEYmwFOfSu8_UUAwK:b-towi0a) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0b79d1fb2cd521db9b41a3cbc2572dbc521ce7ae/src/controllers/velocity_based_position_controller.cpp#L33)):*
> ```cpp
>   cumulative_error = cumulative_error + i_position_diff * dt;
> 
>   control.x = backCalculate(cumulative_error.x, p_position_diff.x,
> ```

This is treating each component separately, so each component could be max_velocity at the same time. The means the total velocity will be greater than max_velocity. Shouldn't we look at limiting the whole vector magnitude instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by garimellagowtham** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/types/position_yaw.h, line 121 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtYDecYX-kGsxPR-Gy6:-KtYHfuzMBI8X_RTM80M:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0b79d1fb2cd521db9b41a3cbc2572dbc521ce7ae/include/aerial_autonomy/types/position_yaw.h#L121)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

wrap yaw
</blockquote></details>

Done.

---

*[src/controllers/velocity_based_position_controller.cpp, line 33 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtYEYmwFOfSu8_UUAwJ:-KtYHY64R5SnYbIilnkG:b4cpdwr) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/0b79d1fb2cd521db9b41a3cbc2572dbc521ce7ae/src/controllers/velocity_based_position_controller.cpp#L33)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

This is treating each component separately, so each component could be max_velocity at the same time. The means the total velocity will be greater than max_velocity. Shouldn't we look at limiting the whole vector magnitude instead?
</blockquote></details>

Changed protobuf documentation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by msheckells** [comment]
Reviewed 3 of 5 files at r3.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[proto/velocity_based_position_controller_config.proto, line 41 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtbpPqIhB75s5oISDGo:-KtbpPqIhB75s5oISDGp:b-o2ra3w) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/663aaa47ee4413aebde598655df30a83591e820c/proto/velocity_based_position_controller_config.proto#L41)):*
> ```protobuf
>   * @brief Gain on saturating cumulative error in back calculation
>   * This gain is multiplied by the i gain. When controller
>   * saturates, the actual control value will be saturated value
> ```

the desired control value

---

*[proto/velocity_based_position_controller_config.proto, line 42 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtbpS9203I2AAIqsVO1:-KtbpS9203I2AAIqsVO2:b-r2yko5) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/663aaa47ee4413aebde598655df30a83591e820c/proto/velocity_based_position_controller_config.proto#L42)):*
> ```protobuf
>   * This gain is multiplied by the i gain. When controller
>   * saturates, the actual control value will be saturated value
>   * + (1/gain)*goal_difference_error; So higher the gain,the
> ```

A larger gain keeps the desired control closer to the control limit and results in a quicker controller response as the desired control moves away from the control limit.  

Any advantages for a smaller gain?  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by msheckells** [comment]
Reviewed 1 of 5 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 31 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtbqVeSeSXwdU7MS-BC:-KtbqVeTd9Ktg12nnUf_:b-j414uh) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/663aaa47ee4413aebde598655df30a83591e820c/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L31)):*
> ```objc
> 
>     position_saturation_gain_ =
>         config_.integrator_saturation_gain() * config_.position_i_gain() * dt;
> ```

assert positive gains and dt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by msheckells** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by garimellagowtham** [comment]
Review status: 6 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 31 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtbqVeSeSXwdU7MS-BC:-Ktc1wEhINjOfub0AREO:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/663aaa47ee4413aebde598655df30a83591e820c/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L31)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

assert positive gains and dt
</blockquote></details>

Done.

---

*[proto/velocity_based_position_controller_config.proto, line 41 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtbpPqIhB75s5oISDGo:-Ktc1f_40YqMOt8Gs6eZ:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/663aaa47ee4413aebde598655df30a83591e820c/proto/velocity_based_position_controller_config.proto#L41)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

the desired control value
</blockquote></details>

Done.

---

*[proto/velocity_based_position_controller_config.proto, line 42 at r3](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-KtbpS9203I2AAIqsVO1:-Ktc1fEYmRJPDVMafXPt:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/663aaa47ee4413aebde598655df30a83591e820c/proto/velocity_based_position_controller_config.proto#L42)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

A larger gain keeps the desired control closer to the control limit and results in a quicker controller response as the desired control moves away from the control limit.  

Any advantages for a smaller gain?  
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 37 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-Ktc2MfuwoLMx8SshbRy:-Ktc2MfuwoLMx8SshbRz:b-mxceo2) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed67e050a8c46d5c94ff9a091ce60898d2e2f53c/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L37)):*
> ```objc
>     CHECK(config_.position_gain() > 0) << "Gain should be non-negative";
>     CHECK(config_.yaw_gain() > 0) << "Gain should be non-negative";
>     CHECK(config_.max_velocity() > 0) << "Gain should be non-negative";
> ```

Max velocity

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 38 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-Ktc2NdYUIxsDiRzagmG:-Ktc2NdYUIxsDiRzagmH:b8u9dxu) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed67e050a8c46d5c94ff9a091ce60898d2e2f53c/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L38)):*
> ```objc
>     CHECK(config_.yaw_gain() > 0) << "Gain should be non-negative";
>     CHECK(config_.max_velocity() > 0) << "Gain should be non-negative";
>     CHECK(config_.max_yaw_rate() > 0) << "Gain should be non-negative";
> ```

Max yaw rate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by garimellagowtham** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 37 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-Ktc2MfuwoLMx8SshbRy:-Ktc41Q3uBSxrFV8mCwP:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed67e050a8c46d5c94ff9a091ce60898d2e2f53c/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L37)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Max velocity
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/velocity_based_position_controller.h, line 38 at r4](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110#-Ktc2NdYUIxsDiRzagmG:-Ktc41yE8Z0pZJRGM8fE:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/ed67e050a8c46d5c94ff9a091ce60898d2e2f53c/include/aerial_autonomy/controllers/velocity_based_position_controller.h#L38)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Max yaw rate
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Comment by msheckells** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/110)*

**Pull request merged**
