### PR TITLE
Print Controller Status

### PR DESCRIPTION
**Pull request by msheckells**
Add fuction to get active controller status.  Add controller status to system status

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/59)

### CODE REVIEW

**Comment by garimellagowtham** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/common/system_status_publisher.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59#-Khz7fKmO7El0OKuzMu0:-Khz7fKmO7El0OKuzMu1:b382cb6) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/3488c566fdaf957f4cc52d4d01a22189270bbe95/include/aerial_autonomy/common/system_status_publisher.h#L38)):*
> ```objc
>     bool hasActiveController = robot_system_.getActiveControllerStatus(
>         HardwareType::UAV, controller_status);
>     if (hasActiveController) {
> ```

Can combine above statement with if statement.

---

*[include/aerial_autonomy/common/system_status_publisher.h, line 48 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59#-Khz7YygrMVsexZHWvF4:-Khz7YygrMVsexZHWvF5:bpwu238) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/3488c566fdaf957f4cc52d4d01a22189270bbe95/include/aerial_autonomy/common/system_status_publisher.h#L48)):*
> ```objc
>       case ControllerStatus::Critical:
>         controller_status_str = "Critical";
>         break;
> ```

add default as controller status not understood!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59)*

**Comment by msheckells** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[include/aerial_autonomy/common/system_status_publisher.h, line 38 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59#-Khz7fKmO7El0OKuzMu0:-Ki0UnSdB2tBIQWRPqzT:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/3488c566fdaf957f4cc52d4d01a22189270bbe95/include/aerial_autonomy/common/system_status_publisher.h#L38)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Can combine above statement with if statement.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/common/system_status_publisher.h, line 48 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59#-Khz7YygrMVsexZHWvF4:-Ki0Uo9tIwGS5n7-sQGh:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/3488c566fdaf957f4cc52d4d01a22189270bbe95/include/aerial_autonomy/common/system_status_publisher.h#L48)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

add default as controller status not understood!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 1 files at r3.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 2 files at r4.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59)*

**Comment by garimellagowtham** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/59)*

**Pull request merged**
