### PR TITLE
Fix documentation and remove robot system access to base state

### PR DESCRIPTION
**Pull request by garimellagowtham**
Please run tests before merging!

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/168)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 32 of 32 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 109 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95wV_iCS81YTbWiw7U:-L95wV_iCS81YTbWiw7V:bk3zz56) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L109)):*
> ```objc
>   /**
>    * @brief Action sequence to ungrip object and go to home location and
>    * fold the arm to rightangle
> ```

right angle

---

*[include/aerial_autonomy/controllers/rpyt_based_position_controller.h, line 27 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95x0wR08hV25jqnOdv:-L95x0wR08hV25jqnOdw:b-o622ho) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/controllers/rpyt_based_position_controller.h#L27)):*
> ```objc
>    *
>    * @param config A config containing position based vel controller and
>    * velocity
> ```

weird new line here

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 140 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95xNyXA06Q6JtwHCkr:-L95xNyXA06Q6JtwHCks:b-uf8ok4) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L140)):*
> ```objc
>   /**
>    * @brief Assuming quad command is at 50 Hz, the buffer size is delay between
>    * when
> ```

weird new line

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 149 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95xUyg7TbDCxy46irB:-L95xUyg7TbDCxy46irC:b5lqc7s) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L149)):*
> ```objc
>   const double gravity_magnitude_;
>   /**
>    * @brief Clip the minimum thrust command
> ```

incorrect doc

---

*[include/aerial_autonomy/robot_systems/uav_vision_system.h, line 98 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95y0Kc-lEe0Q-pFEKk:-L95y0Kc-lEe0Q-pFEKl:b8y4mtf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/robot_systems/uav_vision_system.h#L98)):*
> ```objc
> 
>   /**
>    * @brief Initialize the internal tracker usually called before tracking
> ```

this is two sentences

---

*[include/aerial_autonomy/state_machines/base_state_machine.h, line 53 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95y5wD9Gt-GAy2F73Q:-L95y5wD9Gt-GAy2F73R:b18xgpf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/state_machines/base_state_machine.h#L53)):*
> ```objc
> 
>   /**
>    * @brief config that store statemachine related configs. Also contains
> ```

state machine

---

*[include/aerial_autonomy/state_machines/base_state_machine.h, line 54 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95y7hc3Hbjpb0ZjfCn:-L95y7hc3Hbjpb0ZjfCo:b18xgpf) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/state_machines/base_state_machine.h#L54)):*
> ```objc
>   /**
>    * @brief config that store statemachine related configs. Also contains
>    * other statemachine configs embedded inside
> ```

state machine

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168)*

**Comment by msheckells** [comment]
All tests pass

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-:-L962nT5DpOOivSM58Rt:bcsb184)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[include/aerial_autonomy/actions_guards/pick_place_states_actions.h, line 109 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95wV_iCS81YTbWiw7U:-L967a9B5TYLDpqmbs_6:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/actions_guards/pick_place_states_actions.h#L109)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

right angle
</blockquote></details>

Done.

---

*[include/aerial_autonomy/controllers/rpyt_based_position_controller.h, line 27 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95x0wR08hV25jqnOdv:-L967ybR8fBSTPG5BByz:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/controllers/rpyt_based_position_controller.h#L27)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

weird new line here
</blockquote></details>

Done.

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 140 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95xNyXA06Q6JtwHCkr:-L968a3c0lgvB254eSdh:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L140)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

weird new line
</blockquote></details>

Done.

---

*[include/aerial_autonomy/estimators/thrust_gain_estimator.h, line 149 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95xUyg7TbDCxy46irB:-L968Aas1_ftrIfPIgQ0:bs7wumb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/estimators/thrust_gain_estimator.h#L149)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

incorrect doc
</blockquote></details>

Done.

---

*[include/aerial_autonomy/robot_systems/uav_vision_system.h, line 98 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95y0Kc-lEe0Q-pFEKk:-L968RV6AYYYLMxBuWsM:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/robot_systems/uav_vision_system.h#L98)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

this is two sentences
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/base_state_machine.h, line 53 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95y5wD9Gt-GAy2F73Q:-L968YC7C6H2EBFK9xMd:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/state_machines/base_state_machine.h#L53)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

state machine
</blockquote></details>

Done.

---

*[include/aerial_autonomy/state_machines/base_state_machine.h, line 54 at r1](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168#-L95y7hc3Hbjpb0ZjfCn:-L968ZlKBIvpqdt9njkB:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/e77bb1dfbbc2c5e216375cc1837ac00023d437bb/include/aerial_autonomy/state_machines/base_state_machine.h#L54)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

state machine
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168)*

**Comment by msheckells** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/jhu-asco/aerial_autonomy/168)*

**Pull request merged**
