### PR TITLE
Fix textbox height and width

### PR DESCRIPTION
**Pull request by garimellagowtham**
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/91)

### CODE REVIEW

**Comment by msheckells** [comment]
There seems to be a bug when I run it on my system.  The width of the text box slowly grows over time.

I'm running simulator.launch and remote.launch

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/91#-:-KsQ0IAO3fDcMey4gf4L:bksx5w1)*

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 198 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/91#-KsQ0ZA6MhYw1Yd4lNVh:-KsQ0ZA6MhYw1Yd4lNVi:bml616q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/da43e04ea91fad34d5a248ca8a8432cc57c5b453/src/aerial_autonomy/aerial_autonomy_gui.py#L198)):*
> ```Python
>             text_box.setHtml(status)
>             doc_size = text_box.document().size()
>             text_box.setFixedHeight(doc_size.height() + 10)
> ```

causes gui to grow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/91)*

**Comment by garimellagowtham** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/aerial_autonomy/aerial_autonomy_gui.py, line 198 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/91#-KsQ0ZA6MhYw1Yd4lNVh:-KsQA56HuLAioudwgxHB:b-pnxs5r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/da43e04ea91fad34d5a248ca8a8432cc57c5b453/src/aerial_autonomy/aerial_autonomy_gui.py#L198)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

causes gui to grow
</blockquote></details>

Removed setting width

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/91)*

**Comment by msheckells** [comment]
:lgtm: Tested on my system

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/91#-:-KsdGNyLY3MwhhGAgcM3:b-yfu6da)*

**Pull request merged**
