### PR TITLE
Add status message from uav system, state machine

### PR DESCRIPTION
**Pull request by garimellagowtham**
Removed arm text box. The status message is divided into
robot sysytem message and state machine status.
The robot system status consists of sensor data, controller goals,
and sub system state. The state machine status provides
the current state of the state machine, and the last event
that tiggered no transition in the state machine.

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/29)

### CODE REVIEW

**Comment by msheckells** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/onboard_system_handler.h, line 101 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29#-Kf3fdvbHUr3f-3F4XTd:-Kf3fdvcJYZx8OG2UJCz:bacex7n) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ccddfddf903439874074188b8be0e5039d8c27f/include/aerial_autonomy/onboard_system_handler.h#L101)):*
> ```objc
>   * to automatically add table lines
>   */
>   void updateStatus() {
> ```

Maybe we should move this functionality into its own class: SystemStatusPublisher or something.  That way OnboardSystemHandler doesn't take on multiple responsibilities.  OnboardSystemHandler could then just own a SystemStatusPublisher and call its publish function on a timer.

---

*[include/aerial_autonomy/onboard_system_handler.h, line 112 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29#-Kf3g8t3zNiCCGGzdJF-:-Kf3g8t46PVCUwMfL5ke:b3i9h3r) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/2ccddfddf903439874074188b8be0e5039d8c27f/include/aerial_autonomy/onboard_system_handler.h#L112)):*
> ```objc
>     status.data += "Current state:\t" + current_state_name + "\n";
>     status.data +=
>         "Last event without transition:\t" + no_transition_event_name + "\n";
> ```

Could we also print the last event (regardless of whether it caused a transition or not)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29)*

**Comment by garimellagowtham** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[include/aerial_autonomy/onboard_system_handler.h, line 101 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29#-Kf3fdvbHUr3f-3F4XTd:-Kf8-8z3oVwhXa9AGXiz:b-896fix) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5747c25f32566f3fec502e4251f9a7e420a54cb/include/aerial_autonomy/onboard_system_handler.h#L101)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Maybe we should move this functionality into its own class: SystemStatusPublisher or something.  That way OnboardSystemHandler doesn't take on multiple responsibilities.  OnboardSystemHandler could then just own a SystemStatusPublisher and call its publish function on a timer.
</blockquote></details>

Done.

---

*[include/aerial_autonomy/onboard_system_handler.h, line 112 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29#-Kf3g8t3zNiCCGGzdJF-:-Kf8-AlhAd-UAUefnwsi:bhewqst) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5747c25f32566f3fec502e4251f9a7e420a54cb/include/aerial_autonomy/onboard_system_handler.h#L112)):*
<details><summary><i>Previously, msheckells (Matt Sheckells) wrote…</i></summary><blockquote>

Could we also print the last event (regardless of whether it caused a transition or not)?
</blockquote></details>

This can be done for thread_safe_state_machine since we are overwriting the process_event function. But will not extend to other state machines backends. Let me know if you want it still?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29)*

**Comment by msheckells** [comment]
Reviewed 1 of 4 files at r2.
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[include/aerial_autonomy/onboard_system_handler.h, line 112 at r1](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29#-Kf3g8t3zNiCCGGzdJF-:-Kf80zOtRC8o9RskYb14:bo3kerb) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/f5747c25f32566f3fec502e4251f9a7e420a54cb/include/aerial_autonomy/onboard_system_handler.h#L112)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

This can be done for thread_safe_state_machine since we are overwriting the process_event function. But will not extend to other state machines backends. Let me know if you want it still?
</blockquote></details>

We don't need it for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29)*

**Comment by msheckells** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29)*

**Comment by msheckells** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jhu-asco/aerial_autonomy/29)*

**Pull request merged**
