### PR TITLE
Test6 april 2018

### PR DESCRIPTION
**Pull request by garimellagowtham**
I think we somehow missed this branch. It has plotting scripts for the arm data and some fixes for the arm sysid state machine

---
This change is [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187)

### CODE REVIEW

**Comment by msheckells** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187)*

**Comment by msheckells** [comment]
ArmSineControllerTests fail

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187#-:-LDnIBtUE2S6jYoSmNQo:b-3e0e1v)*

**Comment by garimellagowtham** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[include/aerial_autonomy/state_machines/uav_arm_sysid_state_machine.h, line 114 at r3](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187#-LDnUwA73iayYus3f_57:-LDnUwA82JIbBpujWBbM:b-a8162q) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d73393f49b35e0d00aaa208c28cd81028d3c9128/include/aerial_autonomy/state_machines/uav_arm_sysid_state_machine.h#L114)):*
> ```objc
>                       usa::ManualControlSwitchGuard>,
>             msmf::Row<usa::ManualControlArmState, ue::ArmOscillate,
>                       usa::ArmStatus, usa::ArmSineTransitionFunctor,
> ```

Blocking comment because tests fail

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187)*

**Comment by garimellagowtham** [comment]
I fixed arm sine controller tests. Let me know if the tests still fail.

---

Review status: 14 of 15 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187#-:-LDnhGNMB0uxYC7EaYvP:b-gn9dld)*

**Comment by msheckells** [comment]
ArmSystemTests.JointAngles is also failing

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[include/aerial_autonomy/state_machines/uav_arm_sysid_state_machine.h, line 114 at r3](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187#-LDnUwA73iayYus3f_57:-LDrbWz6EC6-_rtUggMO:b-y3hu8d) ([raw file](https://github.com/jhu-asco/aerial_autonomy/blob/d73393f49b35e0d00aaa208c28cd81028d3c9128/include/aerial_autonomy/state_machines/uav_arm_sysid_state_machine.h#L114)):*
<details><summary><i>Previously, garimellagowtham (Gowtham Garimella) wrote…</i></summary><blockquote>

Blocking comment because tests fail
</blockquote></details>

Works now

---


*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187#-:-LDrbYajDZSwVBqPg3YB:b-6y3fma)*

**Comment by garimellagowtham** [comment]
Fixed the tests. @msheckells  please verify

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/jhu-asco/aerial_autonomy/187#-:-LDsewGiDFAYri6Jisha:bodr22x)*

**Pull request merged**
